### ISSUE TITLE
[Bug - Get employee/Search employee Leave Request] : General leave comment is not showing

### ISSUE THREAD

**Issue by janakapk** [orangehrm/orangehrm#103]
[Bug - Get employee/Search employee Leave Request] : General leave comment is not showing

1.Assign leave to Employee A with comment A
2.Once view the request comment A is not showing
3.Here showing if there are comment in detail view section

**Comment by lakshithaorange** [comment]
since we are now showing leaves , general leave comment is not showing , instead of that leave comment is there
