### ISSUE TITLE
Apply Leave Entitlement based on job status

### ISSUE THREAD

**Issue by CTJohnson** [orangehrm/orangehrm#1038]
Hello,

I would like to be able to apply leave entitlements based on an employee's job status.

For example, if the person is working 80%, then I would like to apply on 80% of the entitlement.

Thank you!

**Comment by KavindaK7** [comment]
Hi,

OrangeHRM Opensource version only supports assigning leave entitlements individually to each employee or bulk assign by sub unit and location (or a combination of both). 

Our commercial version, OrangeHRM Enterprise, can, nevertheless, complete your request in three simple steps.

1. Login as System Administrator and create leave types
2. Create a leave eligibility group where you may choose who is eligible for the leave (by employee status, location, sub unit, job title, job category, hired date and more)
3. Assign leave entitlements to the eligible group  

Do checkout the [free 30 day trial](https://www.orangehrm.com/orangehrm-30-day-trial/) of OrangeHRM Enterprise where you can experience the features with dummy data.
