### ISSUE TITLE
Stored XSS in FileName allows for arbitrary execution of JavaScript

### ISSUE THREAD

**Issue by noobpk** [orangehrm/orangehrm#1044]
**Environment details**
OrangeHRM: 4.9
OrangeHRM source: Release build from Sourceforge
Platform: Darwin Kernel Version 20.6.0
Php Version: 7.3.30
Database and version: MariaDB - 10.4.21
Web server: Apache - 2.4.48

If applicable:
Browser: Firefox 

**Describe the bug**
Stored XSS in FileName when create Job Title allows for arbitrary execution of JavaScript

**To Reproduce**
At menu choose Admin > Job > Job Titles

Add new Add Job Title and upload Job Specification with filename contain payload: `Sun'><img src=x onerror=alert(1)>set.jpg`

XSS will trigger when going to Edit job title just added

**Expected behavior**
The administrator may not notice something unusual in the file and upload it to the server. From which XSS can be executed

**What do you see instead:**
A potential danger can be used to steal cookie information from which attackers can gain unauthorized access to the system.

If issue related to installation:
- N/A

If issue related to any other
- N/A

**Screenshots**
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/31820707/145526701-ef7610ec-d608-43ce-bc4a-113d9fdfd608.png">

**Additional context**
This vulnerability is also report on huntr : [https://huntr.dev/bounties/726818aa-7f1a-4210-b603-6dd6bfd86c13](https://huntr.dev/bounties/726818aa-7f1a-4210-b603-6dd6bfd86c13)

**Comment by samanthajayasinghe** [comment]
Hi @vulf 
This issue is fixed on v4.10.1
https://github.com/orangehrm/orangehrm/releases/tag/v4.10.1
