### ISSUE TITLE
[Bug - PHP 5.6] : Once loading the leave list giving internal error

### ISSUE THREAD

**Issue by janakapk** [orangehrm/orangehrm#108]
[Bug - PHP 5.6] : Once loading the leave list giving internal error. Log report this as 
"
ERROR filter.ExceptionCatcherFilter - Uncaught Exception: exception 'Doctrine_Connection_Mysql_Exception' with message 'SQLSTATE[HY000]: General error: 3065 Expression #1 of ORDER BY clause is not in SELECT list, references column 'osbeta21.o6.date' which is not in SELECT list; this is incompatible with DISTINCT' in /var/www/html/beta21/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Connection.php:1082
"

Because of this Leave List API is not working. This issue happened only in php 5.6 instance.

**Comment by kavithagurusamy** [comment]
Issue is not reproducible in latest build.
