### ISSUE TITLE
PHP 7.4 support

### ISSUE THREAD

**Issue by dgomezleon** [orangehrm/orangehrm#1089]
PHP 7.3 reached its EOL on Dec 6th, 2021. However, the solution still requires PHP 7.0 - 7.3.

![image](https://user-images.githubusercontent.com/11521627/148920490-1dd94514-cf17-4f63-9449-df79433b6754.png)

Those versions are no longer supported and will not receive maintenance or security updates.

Do you plan to add support for PHP 7.4 in the short term?

**Comment by greenlanegreb** [comment]
I second this issue. This software is far too difficult to move and the upgrader is broken as well - i've never found that i've had to delete cache's manually just to move it to a different server too. I'm going to cut my losses and use sentrifugo which is also open source and far more sane.

**Comment by samanthajayasinghe** [comment]
Hi @dgomezleon 
We are actively working 5.x branch where it supports a new tech stack ( PHP 8.x + vue 3.0 ) .
You are welcome to test with https://github.com/orangehrm/orangehrm/releases/tag/v5.0-beta release.

**Comment by samanthajayasinghe** [comment]
Hi @greenlanegreb,
Thanks for your concerns and pls create a bug report for the upgrader issues. 
OrangeHRM maintains an active contribution over the past few years while sentrifugo didn't have any contribution after 2017
reference : [sentrifugo code frequency](https://github.com/sapplica/sentrifugo/graphs/code-frequency)

**Comment by RajithaKumara** [comment]
Hi @dgomezleon,
We made OrangeHRM 4.10 release with PHP 7.4 compatibility. Can find release 
https://sourceforge.net/projects/orangehrm/ & https://github.com/orangehrm/orangehrm/releases/tag/v4.10
