### ISSUE TITLE
[BUG] Upload Image in Buzz

### ISSUE THREAD

**Issue by la-hao** [orangehrm/orangehrm#1103]
I have some issues with uploading images in Buzz. There are 2 videos to describe how I have those bugs. I hope you see it helpful.
1. https://youtu.be/bJckLLRVL2o
2. https://youtu.be/fi9SvIh3eGY

**Comment by RajithaKumara** [comment]
Hi @ahl2811
Thanks for pointing this. Can provide if there is any console errors in browser console? And please provide log file (`<orangehrm>/symfony/log/orangehrm. log`). When you are providing log files make sure to remove sensitive data.

**Comment by ahl2811** [comment]
@RajithaKumara I've just seen this errors in browser console. But, I found nothing in orangehrm.log
![image](https://user-images.githubusercontent.com/49283968/150681073-75b60bce-4859-48cc-90e0-9310880c1cf4.png)
