### ISSUE TITLE
Why is OS version 3.3.3 and Paid version 6.2.1 ?

### ISSUE THREAD

**Issue by vikaskedia** [orangehrm/orangehrm#112]
![image](https://cloud.githubusercontent.com/assets/6703876/25005016/f8327fc8-200b-11e7-8ef6-0d69c6e0b713.png)

**Vs**

![image](https://cloud.githubusercontent.com/assets/6703876/25005035/050ff694-200c-11e7-8402-b764c2eb8502.png)

**Comment by samanthajayasinghe** [comment]
Hi .. 

Since paid version include more features rather than the open source  version it released with higher version numbers.

**Comment by vikaskedia** [comment]
so are they using the same source code base ?

**Comment by kavithagurusamy** [comment]
Enterprise or Professional customer don't get the source code. The different in the version gap is Enterprise version contains more advanced features than Open source.

Can you please contact sales@orangehrm.com if you have any further questions? Rather dropping it here. This is targetted for Opensource users.
