### ISSUE TITLE
Unable to login into https://opensource-demo.orangehrmlive.com/

### ISSUE THREAD

**Issue by SaranyaArunPrakash** [orangehrm/orangehrm#1150]
Hi

Unable to login into demo site https://opensource-demo.orangehrmlive.com/ using Admin/admin123.
I used this credentials until Friday but now not able to. Please provide credentials.

**Comment by RajithaKumara** [comment]
Hi @SaranyaArunPrakash,
The demo will reset every one hour. can you check now.

**Comment by SaranyaArunPrakash** [comment]
Hi Rajitha,

I am now getting an Account Disabled error when trying to login with
Admin/admin123.

Is there any valid credentials I can use?


Regards,
Saranya Arumugam

**Comment by Kruchy1980** [comment]
I have problem today to even open the https://opensource-demo.orangehrmlive.com/web/index.php/auth/login unfortunately :(
Anyone knows what is the time for fixing the issue??

Best regards and thank you for answer in advance<
Jakub
