### ISSUE TITLE
Referer header injection redirect vulnerability

### ISSUE THREAD

**Issue by vulf** [orangehrm/orangehrm#1174]
**Environment details**
OrangeHRM version: 4.10
OrangeHRM source: Release build from [Sourceforge](https://sourceforge.net/projects/orangehrm) or Git clone
Platform: Ubuntu
PHP version: 7.3.33
Database and version: MariaDB 10.3
Web server: Apache 2.4.52

If applicable:
Browser: Firefox

**Describe the bug**
This is similar to the Host header injection redirect vulnerability, except the issue lies in the **Referer** header and the vulnerable endpoints are **different**.

**To Reproduce**
1. Login to the OrangeHRM application
2. Navigate to "My Info"
3. Under "Add Attachment", click on "Add"
4. Turn on Intercept in Burp Suite (or any other web proxy)
5. Select any PNG file and Click on "Upload"
6. Change the value of the `Referer` header to `example.com`
7. Click on Forward in Burp and turn off Intercept
8. You will notice that the page gets redirected to `http://example.com/symfony/web/index.php/pim/viewPersonalDetails/empNumber/X`

**Expected behavior**
A 404 error.

**What do you see instead:**
 A 302 redirect to the malicious domain.

**Screenshots**
![image](https://user-images.githubusercontent.com/37404408/157671516-b90770ff-cb72-4e64-8124-14bd7b956669.png)

**Comment by samanthajayasinghe** [comment]
Hi @vulf 
It's recommended to deploy the application with the valid hostname 
```
eg: nginx 
server {
    listen 80 default_server;
    server_name mydomain.com;
   ...
}
```
