### ISSUE TITLE
Blank screen system check 

### ISSUE THREAD

**Issue by shanka12** [orangehrm/orangehrm#1186]
Version 4.10
Shared server

I got blank screen. I installed composer dependencies.

 ![screenshot_from_2022-03-18_19-12-56.png](https://user-images.githubusercontent.com/8470380/159014247-cb333190-23c1-4d93-b285-43036f776a5e.png)

**Comment by RajithaKumara** [comment]
Hi @shanka12 
Can you provide the following details,
- Platform: output of `uname -a` (UNIX), or version and 32 or 64-bit (Windows), or Docker
- PHP version: output of `php -v` **(required)**
- Database and version: [e.g. MySQL 5.7, MariaDB 10.2]
- Web server: [e.g. Apache 2.4, Nginx 1.4]

**Comment by shanka12** [comment]
It's fixed. Thanks

**Comment by RajithaKumara** [comment]
Can we know the fix? If it's an issue in the application we can address it.

**Comment by shanka12** [comment]
I run the symphony command again. 
But I couldn't enable mysql event scheduler status.
Also stuck with week password change 
![20220329_164248.jpg](https://user-images.githubusercontent.com/8470380/160599135-3bc72187-88ed-4f72-b078-a483c47c7e0c.jpg)

**Comment by shankar-bavan** [comment]
I got like this? is this works on shared hosting ?

![image](https://user-images.githubusercontent.com/48729909/160762244-938521bd-03dd-403e-8071-ef9344699a16.png)
