### ISSUE TITLE
Login Credentials invalid

### ISSUE THREAD

**Issue by KarlJasson** [orangehrm/orangehrm#1191]
Browser: Chromium 99.0.4844.51 on Ubuntu 18.04

**Describe the bug**
March 22, 2022: "Admin" and "admin123" credentials are invalidated

**Comment by samanthajayasinghe** [comment]
less reproduce steps

**Comment by KarlJasson** [comment]
Returning to this issue. Was able to login last week and yet the "Admin" and "admin123" credentials are considered invalid
