### ISSUE TITLE
Do professional / enterprise customers get the complete source code?

### ISSUE THREAD

**Issue by vikaskedia** [orangehrm/orangehrm#120]
I want to integrate orangehrm with my internal accounting software.

Will the professional / enterprise version give me access to the complete source code?

**Comment by samanthajayasinghe** [comment]
Hi .. 

You can integrate with latest REST api's in opensource version. API doc is [here](https://orangehrm.github.io/orangehrm-api-doc)

**Comment by vikaskedia** [comment]
So the source code is not given in the professional/enterprise  version ?

**Comment by kavithagurusamy** [comment]
Hi 

Please contact sales@orangehrm.com for further information of purchasing of enterprise version. I am closing this since this is not related to Open Source query.

**Comment by vikaskedia** [comment]
@kavithagurusamy This question is related to the open source version.

I have been asking on issue #112 also .. does the open source and enterprise version share the same code base ? 

Or does the enterprise and open source version have different code bases ?

The customization that I make to the open source version can I merge them in the enterprise version or not ?

Closing the issue without giving a straight answer .. does not look good ..
