### ISSUE TITLE
Internal Error Occurred

### ISSUE THREAD

**Issue by shankar-bavan** [orangehrm/orangehrm#1206]
I installed successfully and got Internal Error Occurred.

![image](https://user-images.githubusercontent.com/48729909/161078722-05042114-0e4f-4960-8910-456693874747.png)

Log file:-
`
 PDO Connection Error: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)`

but there is no issue with mysql password

**Comment by shanka12** [comment]
I found the issue. 
Mysql password included special characters. 
databases.yml file not accepting it.
