### ISSUE TITLE
css broken

### ISSUE THREAD

**Issue by shankar-bavan** [orangehrm/orangehrm#1228]
after making changes on branding, page styles broken

![image](https://user-images.githubusercontent.com/48729909/163563981-0b3b3a95-6219-4c63-bbf1-1e54f39b53a6.png)

**Comment by shankar-bavan** [comment]
![image](https://user-images.githubusercontent.com/48729909/163564061-608fc87a-ae14-45b5-90ec-ebf9f9694835.png)

**Comment by JustMitah** [comment]
@RajithaKumara is there a way to give them write permission? I tried chmod but I think I will have to restart the docker, anyway to make that permanent?
