### ISSUE TITLE
Installation Step 3 - Error - Create DB User

### ISSUE THREAD

**Issue by patrickmau** [orangehrm/orangehrm#1272]
**Environment details**
OrangeHRM version: 4.10
OrangeHRM source: Release build from [Sourceforge]
Platform: Ubuntu 20.04 LTS (GNU/Linux 5.4.0-1018-aws x86_64)
PHP version: PHP 7.4.3 (cli) (built: Mar  2 2022 15:36:52) ( NTS )
Database and version: 8.0.28-0ubuntu0.20.04.3 (Ubuntu)
Web server: Apache/2.4.41 (Ubuntu)

If applicable:
Browser: Safari

**Describe the bug**
Please describe what the bug is.

During installation step 'Fill default data into the database' wizard throws error 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IDENTIFIED BY 'orangehrm-user-password' at line 4'.

Installation is run with privileged user details of 'root' user, there should be no SQL restriction pertaining to this user, not sure what queries are run by the non-privileged OrangeHRM user account.

**To Reproduce**
Steps to reproduce the behavior.
Complete the installation wizard with default settings, including root user access and separate Orange HRM DB user account.

**Expected behavior**
Complete the wizard installation steps.

**What do you see instead:**
Error message during step 3: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IDENTIFIED BY 'Orange-HRM-db-user-account-password'' at line 4

If issue related to installation:
OrangeHRM Installation Log

Sun, 01 May 2022 18:24:59 +0000 DB Creation - Starting
Sun, 01 May 2022 18:24:59 +0000 DB Creation - Done
Sun, 01 May 2022 18:24:59 +0000 DB Creation - No Errors
Sun, 01 May 2022 18:25:01 +0000 Fill Data Phase 1 - Starting
Sun, 01 May 2022 18:25:01 +0000 Fill Data Phase 1 - Connected to the DB Server
Sun, 01 May 2022 18:25:01 +0000 Fill Data Phase 1 - Selected the DB
Sun, 01 May 2022 18:25:01 +0000 Fill Data Phase 1 - Reading DB Script
Sun, 01 May 2022 18:25:01 +0000 Fill Data Phase 1 - Opened DB Script
Sun, 01 May 2022 18:25:01 +0000 Fill Data Phase 1 - Read DB script
Sun, 01 May 2022 18:25:01 +0000 Fill Data Phase 1 - There are 325 Statements in the DB script
Sun, 01 May 2022 18:25:16 +0000 MySQL Procedure Error:No database selected
Sun, 01 May 2022 18:25:16 +0000 Fill Data Phase 1 - Done
Sun, 01 May 2022 18:25:16 +0000 Fill Data Phase 1 - No Errors
Sun, 01 May 2022 18:25:19 +0000 Fill Data Phase 2 - Starting
Sun, 01 May 2022 18:25:19 +0000 Fill Data Phase 2 - Connected to the DB Server
Sun, 01 May 2022 18:25:19 +0000 Fill Data Phase 2 - Selected the DB
Sun, 01 May 2022 18:25:19 +0000 Fill Data Phase 2 - Reading DB Script
Sun, 01 May 2022 18:25:19 +0000 Fill Data Phase 2 - Opened DB Script
Sun, 01 May 2022 18:25:19 +0000 Fill Data Phase 2 - Read DB script
Sun, 01 May 2022 18:25:19 +0000 Fill Data Phase 2 - There are 217 Statements in the DB script
Sun, 01 May 2022 18:25:20 +0000 MySQL Event Error:No database selected
Sun, 01 May 2022 18:25:20 +0000 Fill Data Phase 1 - Connected to the DB Server
Sun, 01 May 2022 18:25:20 +0000 Fill Data Phase 2 - Done
Sun, 01 May 2022 18:25:20 +0000 Fill Data Phase 2 - No Errors
Sun, 01 May 2022 18:25:23 +0000 Create DB user - Starting
Sun, 01 May 2022 18:25:23 +0000 Create DB user - Done
Sun, 01 May 2022 18:25:23 +0000 Create DB user - Errors
Sun, 01 May 2022 18:25:23 +0000 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IDENTIFIED BY 'Orange-HRM-db-user-account-password'' at line 4

**Comment by RajithaKumara** [comment]
Hi @patrickmau,
For the moment we did not test on MySQL 8.0.

But as per your error log;
You can create an empty database and create a user for the database. And you can use that database credentials in the OrangeHRM installer `Database Configuration` screen. Make sure to select `Existing Empty Database` from `Database to Use` dropdown.

**Comment by patrickmau** [comment]
This results in this error:

"Database `orangehrm_mysql` is not empty. Please use another empty database or cleanup the given database."

can you advise which table needs to be cleared please? Otherwise, could you provide an empty database backup of a sample company that I can use to at least get past the wizard?

Thanks

**Comment by patrickmau** [comment]
above workaround fixed the issue, simple need to create the DB without any tables after the error is encountered to circumvent the problem.

Thank you.

**Comment by RajithaKumara** [comment]
Thanks for reporting this issue.
Fixed with [OrangeHRM 5.1 release](https://sourceforge.net/projects/orangehrm/files/stable/5.1/orangehrm-5.1.zip/download)

**Comment by SonaPavi89** [comment]
![Image](https://github.com/user-attachments/assets/ff6dad17-3cc2-4d93-87d5-f4bde3799970)

I am getting this error! Please help me with this @RajithaKumara !
