### ISSUE TITLE
[Bug - Save work experience] :  Shows SQl error when try to add record to employee not in system

### ISSUE THREAD

**Issue by janakapk** [orangehrm/orangehrm#134]
Shows SQl error when try to add record to employee not in system.

Steps : 
"1.Save the data with
employee id = 5 (not in system ), company = orange, jobTitle = dew, fromDate = 2017-02-2
toDate =2017-03-05 and saved

2.It comes error ""SQLSTATE[23000]: Integrity constraint violation: 
1452 Cannot add or update a child row: a foreign key constraint fails 
(`os4`.`hs_hr_emp_work_experience`, CONSTRAINT 
`hs_hr_emp_work_experience_ibfk_1` FOREIGN KEY (`emp_number`) 
REFERENCES `hs_hr_employee` (`emp_number`) ON DELETE CASCADE)""

**Comment by kavithagurusamy** [comment]
Closed in Beta 3
