### ISSUE TITLE
[Bug : Save employee education] : It support up to 23 character for GPA, But front end support up to 25

### ISSUE THREAD

**Issue by janakapk** [orangehrm/orangehrm#136]
It support up to 23 character for GPA, But front end support up to 25

**Comment by lakshithaorange** [comment]
it is supporting 25 characters , 

this is for 26 characters 
{
  "error": {
    "status": "202",
    "text": "gpa must have a length between 1 and 25"
  }
}

**Comment by janakapk** [comment]
Validation is given like that. but it restricted from 23
