### ISSUE TITLE
attachment file size version 5.0

### ISSUE THREAD

**Issue by frapie** [orangehrm/orangehrm#1365]
**Environment details**
OrangeHRM version: 5.0
OrangeHRM source: Release build from [Sourceforge](https://sourceforge.net/projects/orangehrm)
Platform: xamp windows server
PHP version: 7.4.29
Database and version: MySQL 5.7
Web server: xamp

If applicable:
Browser: Chrome

**Describe the bug**
Cannot increase licensing qualification attachment size by updating previous version files or by updating this in configService.php public const MAX_ATTACHMENT_SIZE = 10000000; // 10 MB. This makes no difference and PHP is set at 40 MB

**To Reproduce**
change file and see results

**What do you see instead:**
continues to tell me the file is to large

**Additional context**
Trying to get support but no one will reply from ossupport@orangehrm.com when I email. received one reply and I sent an email back to ask for assistance but have not received any replies. Have sent a couple of emails now. **Please help**

![2mb file](https://user-images.githubusercontent.com/30099949/177226113-345eb294-797c-42fc-9440-78add527b749.jpg)
![configservice](https://user-images.githubusercontent.com/30099949/177226184-4313ae0d-ca2b-4023-b102-39a1c8ec715d.jpg)

**Comment by frapie** [comment]
hi, have we had any further progression in getting more than 1 MB attachment to upload? the application is not very useful without it.

**Comment by Super-Chama** [comment]
@frapie we have added more fields support for `MAX_ATTACHMENT_SIZE` in 5.1 release. you can check and let us know.

**Comment by bmcgonag** [comment]
If you don't know if this is working, why did you close it?

I can say that in version 5.3, the upload limit on images for branding is still giving the message in the User Interface that anything larger than 1 MB exceeds the size limit.

**Comment by Super-Chama** [comment]
@bmcgonag the default file size is 1MB still in 5.3, but you can change it by updating `MAX_ATTACHMENT_SIZE` variable in `src/plugins/orangehrmCorePlugin/Service/ConfigService.php`

**Comment by mm86133** [comment]
It is not fixed ! The issue exists in newest version still!

**Comment by Pezhvak** [comment]
Any updates on this?
