### ISSUE TITLE
[Bug - Save/Update employee custom field] : Saving the custom field are not working

### ISSUE THREAD

**Issue by janakapk** [orangehrm/orangehrm#138]
Saving the custom field are not working

Steps :
1.Save the date with 
id = 1, fieldId = 1, value = test
2.Shows message "Unknown record property / related component \"custom1 \" 
on \"Employee\""

Note : This should fixed in Update API also when we fixing

**Comment by lakshithaorange** [comment]
couldn't recreate it , I'll check with Janaka,
