### ISSUE TITLE
Blank page after installation

### ISSUE THREAD

**Issue by AbdelSaTd** [orangehrm/orangehrm#1383]
**Environment details**
OrangeHRM version: 5.1
OrangeHRM source: Git clone
Platform: Linux VirtualBox 5.15.0-41-generic #44~20.04.1-Ubuntu SMP Fri Jun 24 13:27:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

PHP version: 8.1.8
Database and version: MySQL 8.0.29-0ubuntu0.20.04.3 for Linux on x86_64
Web server:  Apache 2.4

If applicable:
Browser: Firefox

**Describe the bug**
After copying the source code under my web server main directory (/var/www/html) when accessing the folder I'm redirected to the URL : **localhost/orangehrm-5.1/installer/index.php/welcome**
And I have noticed that if run the script orangehrm-5.1/installer/cli_installer.php I am redirected to **localhost/orangehrm-5.0/web/index.php/auth/login** but the problem remains the same. Blank page.

**To Reproduce**
Just deploy and test

**Expected behavior**
See the installation page with buttons and stuffs

**What do you see instead:**
Blank page

src/log/installer.log

**Screenshots**
![Screenshot from 2022-07-16 18-29-34](https://user-images.githubusercontent.com/38259750/179363633-15962db5-851e-41b6-b51f-ecc58f88c9ed.png)

**Comment by RajithaKumara** [comment]
Hi @AbdelSaTd 
If you want to test the application without building, you have to download the production build from [here](https://github.com/orangehrm/orangehrm/wiki/5.x-development-guide).
If you are a developer follow [this high level guide](https://github.com/orangehrm/orangehrm/wiki/5.x-development-guide) to install dependencies & build the application.

**Comment by AbdelSaTd** [comment]
Hi @RajithaKumara thank you. It works.
