### ISSUE TITLE
unable to login to orangeHRM

### ISSUE THREAD

**Issue by yugap21** [orangehrm/orangehrm#1399]
Hello, i am unable to login in Demo URL which is mentioned in the description which is:

https://opensource-demo.orangehrmlive.com/index.php/

It shows Invalid Credentials every-time. I am using the credentials mentioned in the above url as, Admin & admin123

Thank You

**Comment by Super-Chama** [comment]
Hello @yugap21 we're sorry about the inconvenience. as it's a public demo anyone can change the credentials. but it automatically reset every hours. please give a try now.

Alternatively you can register for a [OrangeHRM starter free trial](https://www.orangehrm.com/open-source/open-source-on-demand) this way you will get private access to your own instance for testing.

**Comment by Super-Chama** [comment]
This is fixed in https://github.com/orangehrm/orangehrm/pull/1418 and update [demo](https://opensource-demo.orangehrmlive.com) is available.
