### ISSUE TITLE
Application not maintaining session when using https:// 

### ISSUE THREAD

**Issue by siddharthaithena** [orangehrm/orangehrm#1421]
**Environment details**
OrangeHRM version: 5.1.0
OrangeHRM source: Git clone
Platform: centos
PHP version: 8.0.18
Database and version: MySQL 5.7.38
Web server: Apache 2.4

**Describe the bug**
We have applied SSL to the server. When we load any page in the web app with https, it works, but whenever there is a new server request, it logs the user out. User is not able to log in with https. User can login when the protocol is http.

If the user tries to log in using https as protocol, then the login fails and the application redirects to http.

**Comment by RajithaKumara** [comment]
Hi @siddharthaithena ,
OrangeHRM 5.1 supports both http and https. This is probably an issue with server configuration. Is it possible for you to provide apache vhost (by clearing sensitive data)?
Also, the application does not redirect between HTTP & HTTPS.

Additionally, if you are not a developer and willing to use production release, we recommend using release build from https://sourceforge.net/projects/orangehrm/files/stable/ rather than cloning from git.

**Comment by siddharthaithena** [comment]
Hi @RajithaKumara ,
Thanks for the quick reply.
Attaching the vhost config file for your reference.

Firstly, let me explain you the SSL configuration with the below steps.
- We are using an EC2 server and have configured OrangeHRM on port 81 as it is a shared server.
- There is a Load Balancer which directs traffic to port 81.
- The SSL certificate is from AWS itself and is connected to the Load Balancer, so we do not have it's .crt file and the key. Hence, the vhost looks the way it looks.
![orangehrm_vhost](https://user-images.githubusercontent.com/106513889/186336533-321ba309-9c93-4c70-93af-1553a1347abb.png)

**Comment by siddharthaithena** [comment]
Hi @RajithaKumara ,
Thanks for the quick reply. Attaching the vhost.conf file for your reference.

Firstly, let me explain you the SSL configuration with the below steps.
- We are using an EC2 server and have configured OrangeHRM on port 81 as it is a shared server.
- There is a Load Balancer which directs traffic to port 81.
- The SSL certificate is from AWS itself and is connected to the Load Balancer, so we do not have it's .crt file and the key. Hence, the vhost looks the way it looks.
![orangehrm_vhost](https://user-images.githubusercontent.com/106513889/186362959-164e57a9-8a25-4728-ac07-d78c9f2a125b.png)

**Comment by siddharthaithena** [comment]
Thanks, @samanthajayasinghe ,
i have not used `Redirect permanent / `, but used a `RewriteEngine` to redirect and it works. Thanks again.
Closing this thread.
