### ISSUE TITLE
Error "Employee Id already exists" while Employee Id is blank

### ISSUE THREAD

**Issue by nethubonline** [orangehrm/orangehrm#1451]
**Environment details**
OrangeHRM version: 5.1
OrangeHRM source: Release build from [Sourceforge](https://sourceforge.net/projects/orangehrm)
Platform: CentOS Linux release 7.3.1611 x64
PHP version: 7.4.21
Database and version: MariaDB 10.0.36
Web server: Apache 2.4.48

If applicable:
Browser: Firefox / Chrome

**Describe the bug**
I had used v4.x for long time, and just upgraded to v5.1 recently. I have many employees whose Employee Id are blank, if I save any data of those employees now, I got error "Employee Id already exists"

**To Reproduce**
Save data for employee while Employee Id field is blank

**Expected behavior**
No error and allow blank the Employee Id

**Screenshots**
![screenshot 331](https://user-images.githubusercontent.com/10508881/190594966-5274bde8-5494-4978-b761-c75b06de6897.jpg)

**Comment by RajithaKumara** [comment]
This issue is fixed in OrangeHRM 5.2

**Comment by huuthinh47** [comment]
hi @RajithaKumara 
In version OrangeHRM OS 5.2, i can add new employee without employeeID or duplicated employeeID.
