### ISSUE TITLE
Attachment Size

### ISSUE THREAD

**Issue by officex** [orangehrm/orangehrm#1457]
**Environment details**
OrangeHRM version: 5.1
OrangeHRM source: Release build from [Sourceforge](https://sourceforge.net/projects/orangehrm)
Platform:  Debian 4.19.249-2 x86_64 
PHP version: 8.19
Database and version: Mariadb 10.3
Web server: Apache 2.4

If applicable:
Browser: Firefox and Chrome

**Describe the bug**
Under PIM > (Employee Name) > Job > Attachments 
I cannot upload any files **even below 1MB**. I tried even uploading 500kb file. 
It is fine to upload in any other areas of the site which is under 1MB but only affected in this section. 

**What do you see instead:**
 It states - "Attachment Size Exceeded". 

**Screenshots**
![job](https://user-images.githubusercontent.com/6488749/191212260-70fa90f5-f522-46e3-9ede-ce1fe732d81a.png)

**Additional context**
I tried changing the MAX_ATTACHMENT_SIZE in configService.php but it did not have any effect.

**Comment by officex** [comment]
Hi Guys 
Is there any quick fix for this issue in the meanwhile?

**Comment by Super-Chama** [comment]
Hi @officex this issue has been accepted as a bug and will be fixed with OrangeHRM 5.2 release.

**Comment by RajithaKumara** [comment]
This issue is fixed in OrangeHRM 5.2.
But if server configuration is not restricted the max request payload
