### ISSUE TITLE
Cannot View the Attachment by ESS (admin upload the file)

### ISSUE THREAD

**Issue by cholloSalvador** [orangehrm/orangehrm#1459]
**Environment details**
OrangeHRM version: 5.1
OrangeHRM source: Release build from [Sourceforge](https://sourceforge.net/projects/orangehrm) or Git clone
Platform: output of `uname -a` (UNIX), or version and 32 or 64-bit (Windows), or Docker
PHP version: output of `php -v`
Database and version: [e.g. MySQL 5.7, MariaDB 10.2]
Web server: [e.g. Apache 2.4, Nginx 1.4]

If applicable:
Browser: [e.g. Chrome, Safari]

**Describe the bug**
I try to upload the attachment in User profile. 

Then I logged in to the user to download the file

**To Reproduce**
Admin> click user > attachment> upload attachment > done 

**Expected behavior**
This page isn’t working

Domain name.com/web/index.php/pim/viewAttachment/empNumber/2/attachId/4

**Comment by RajithaKumara** [comment]
This issue is fixed in OrangeHRM 5.2
