### ISSUE TITLE
PHP 7 support is missing

### ISSUE THREAD

**Issue by SmartiApps** [orangehrm/orangehrm#146]
We are getting following error because of mysql_connect()  is deprecated in the PHP7 installed machines.
Fatal error: Uncaught Error: Call to undefined function mysql_connect() in install.php:210 Stack trace: #0 {main} thrown in install.php on line 210

**Comment by samanthajayasinghe** [comment]
OrangeHRM currently support php 5.6.x and we are working on php7 supports.

**Comment by casoetan** [comment]
@samanthajayasinghe Any updates on how soon php7 support will be in.

**Comment by kavithagurusamy** [comment]
This will be available in OS 4.0 release which we are planning for next month (July 2017)

**Comment by kavithagurusamy** [comment]
@casoetan You can try with https://github.com/orangehrm/orangehrm/tree/php7-dev to install the Open source in PHP 7.1 with maria db support. This is currently under QA.

**Comment by casoetan** [comment]
Thanks.
Will take a look this weekend.

Best, \Charles
via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=dx&cv=9.8.8&pv=10.12.5&source=email_footer_2]
On Thu, Jun 22, 2017 at 9:08, kavithagurusamy <notifications@github.com> wrote:
@casoetan [https://github.com/casoetan] You can try with https://github.com/orangehrm/orangehrm/tree/php7-dev [https://github.com/orangehrm/orangehrm/tree/php7-dev] to install the Open source in PHP 7.1 with maria db support. This is currently under QA.

**Comment by casoetan** [comment]
Hello. Got this issue
<code>
Warning: require_once(/orangehrm_php7/symfony/lib/vendor/phpseclib/phpseclib/phpseclib/Crypt/Random.php): failed to open stream: No such file or directory in /orangehrm_php7/installer/ApplicationSetupUtility.php on line 22
</code>

**Comment by samanthajayasinghe** [comment]
Did you update the composer ? 
if not execute the following command 
composer install -d symfony/lib

**Comment by casoetan** [comment]
Thanks. That worked. But now

<code>
...
/orangehrm_php7/symfony/web/themes/default/css/reset.css - No such file or directory
/orangehrm_php7/symfony/web/themes/default/css/tipTip.css - No such file or directory
/orangehrm_php7/symfony/web/themes/default/css/jquery/jquery-ui-1.8.21.custom.css - No such file or directory/orangehrm_php7/symfony/web/themes/default/css/jquery/jquery.autocomplete.css - No such file or directory/orangehrm_php7/symfony/web/themes/default/css/main.css - No such file or directory
/orangehrm_php7/symfony/web/themes/default/images/login/logo.png - No such file or directory
/orangehrm_php7/symfony/web/themes/default/images/login/linkedin.png - No such file or directory
/orangehrm_php7/symfony/web/themes/default/images/login/facebook.png - No such file or directory
/orangehrm_php7/symfony/web/themes/default/images/login/twiter.png - No such file or directory/orangehrm_php7/symfony/web/themes/default/images/login/youtube.png - No such file or directory
...
/orangehrm_php7/symfony/web/themes/default/images/favicon.ico - No such file or directory
</code>

**Comment by casoetan** [comment]
Hello @samanthajayasinghe I think the issue I'm having is using Orange HRM with NGinx & PHP-FPM.

Already have an issue raised here #155

Can't login, I could only view the application through orangehrm_dev. See screenshot.

<img width="1211" alt="screenshot 2017-06-27 15 42 39" src="https://user-images.githubusercontent.com/1047316/27593563-6312426e-5b4f-11e7-96a7-ff0c1a8c5055.png">

**Comment by casoetan** [comment]
@samanthajayasinghe  See how the assets are mapped: 
<code>
http://hr.example.org:8080/var/www/hr.example.org/symfony/web/themes/default/images/login/login.png
</code>

**Comment by casoetan** [comment]
@samanthajayasinghe and this keeps showing up
<code>
Warning: Invalid argument supplied for foreach() in /var/www/hr.example.org/symfony/plugins/orangehrmCorePlugin/lib/utility/PluginExecutionManager.php on line 76
</code>

**Comment by kavithagurusamy** [comment]
@casoetan Following are the steps followed by QA to setup the system,

1. Download the build (Zip) file from "https://github.com/orangehrm/orangehrm/tree/php7-dev"
2. Extract it inside the web directory
3. Grant permission to the extracted folder (chmod -R 755)
4.Update composer then run the following command from symfony/lib
composer install
composer dump-autoload -o
5. RUN from symfony/
./symfony cc
./symfony d:build-model
./symfony o:publish-as
6. Access the system in web and install through web installer.

**Comment by casoetan** [comment]
Yeah. This works.

Please @kavithagurusamy look at #155. can you help with that?

**Comment by kavithagurusamy** [comment]
Closing this and replied on #155

**Comment by Lamsa-GitHub** [comment]
In System check

Warning: require(): Filename cannot be empty in C:\wamp64\www\orangehrm-435\installer\environmentCheck\SystemValidator.php on line 22

Fatal error: require(): Failed opening required '' (include_path='.;C:\php\pear') in C:\wamp64\www\orangehrm-435\installer\environmentCheck\SystemValidator.php on line 22

**Comment by RajithaKumara** [comment]
Hi @Lamsa-GitHub 
Can you go through the #514 , and let us know if it not solve your issue.
