### ISSUE TITLE
LDAP integration for orangehrm 5.1

### ISSUE THREAD

**Issue by h3nr1-g** [orangehrm/orangehrm#1465]
Hi everyone,
I played around with orangehrm and I really like your software solution. 

What I need is a LDAP integration for the user authentication. I saw that there is a LDAP plugin in the git branch "5.2". Is there a way to get this plugin running in version 5.1 or do you have a time frame when version 5.2 with this plugin will be released?

Best,
Henry

**Comment by RajithaKumara** [comment]
Hi @h3nr1-g,
Happy to hear.
Yeah, you have to wait till 5.2 release. We are actively working on it. will be released mid of October.

**Comment by h3nr1-g** [comment]
Hey @RajithaKumara ,
thanks for the fast reply. :)

Okay, No problem.
