### ISSUE TITLE
I want to change the font to make it easier to read in my native language (Vietnamese)

### ISSUE THREAD

**Issue by thinhplust** [orangehrm/orangehrm#1513]
Hi, thanks to the software development company.
I am currently implementing software for my company. But the problem is that my Vietnamese is difficult to read with the current font. I want to change the current font to google font.
hope can help me

**Comment by Super-Chama** [comment]
Hi @thinhplust we are currently using [Nunito Sans](https://fonts.google.com/specimen/Nunito+Sans) in OrangeHRM 5.0v (and onwards) which supports Unicode in all supported browsers. Sorry to hear you're having difficulties in your language. Can you share with us how it looks in Vietnamese and what needs to be improved? We can improve the product for everyone that way.

For customisation you will have to build your own version of OrangeHRM. There are multiple ways to change the styles. You can either change font style from [global.scss file](https://github.com/orangehrm/orangehrm/blob/main/src/client/src/core/styles/global.scss) or You can override the existing styles from [application layout](https://github.com/orangehrm/orangehrm/blob/main/src/plugins/orangehrmCorePlugin/templates/base.html.twig).

1. Overriding styles via global.scss
     - Follow our [development wiki](https://github.com/orangehrm/orangehrm/wiki/5.x-development-guide) and setup the application ready to develop
     - Locate `global.scss` file in `orangehrm/src/client/src/core/styles/global.scss`
     - Copy paste your font style from Google Fonts
         IE -> `@import url('https://fonts.googleapis.com/css2?family=Roboto&display=swap');`
    - Override `$oxd-font-family` sass variable
         IE -> `$oxd-font-family: 'Roboto', sans-serif;`
    - Build the application using `yarn build`

2. Overriding styles via Layout
     - Follow our [development wiki](https://github.com/orangehrm/orangehrm/wiki/5.x-development-guide) and setup the application ready to develop OR download the OrangeHRM Build from our release channels.
     - Locate `base.html.twig` file in  `orangehrm/src/plugins/orangehrmCorePlugin/templates/base.html.twig`
     - Copy paste your font into `<head>` tag
          ```
           <html>
              <head>
                ....
                {% block stylesheets %}{% endblock %}
                <link rel="preconnect" href="https://fonts.googleapis.com">
                <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
                <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
              </head>
            ....
          ``` 
     - Override the default body font style by adding following code to bottom of `<body>`tag
          ```
           <body>
             ....
             <style>
              * {
                font-family: 'Roboto', sans-serif !important;
              }
            </style>
          </body>
          ```

In both cases you will have to cache clear your browser to show you the updated changes.
