### ISSUE TITLE
Install on CyberPanel

### ISSUE THREAD

**Issue by kw3rln** [orangehrm/orangehrm#1517]
Hello, is there any possibility to install on CyberPanel ?

![image](https://user-images.githubusercontent.com/114662333/199236722-444a5d7e-e4f8-496b-abcb-863c92a93157.png)

Thanks

**Comment by RajithaKumara** [comment]
Hi @kw3rln ,
There is one way to continue the installation. You have to do a code modification.

Remove this line;
https://github.com/orangehrm/orangehrm/blob/1ffd93940c80f9014d2435f446da837789737400/installer/Util/SystemConfig.php#L254


`installer/Util/SystemConfig.php` inside `isWebServerCompatible` function,
remove `$this->interruptContinue = true;`

Can I know your web server and version? (e.g. Apache 2.4)

**Comment by kw3rln** [comment]
Hello @RajithaKumara 

the web server is Open LiteSpeed, as far as i know orangehrm needs apache or ngix, right ?

**Comment by kw3rln** [comment]
![image](https://user-images.githubusercontent.com/114662333/199244152-0b0d5100-e1d0-4ea1-bdf8-033e97b41d45.png)

I did as you said, it installed ok but there is a problem in the display, could it be because it doesn't use apache/ngix ?

**Comment by Super-Chama** [comment]
@kw3rln this issue with i18n language strings has been accepted as a bug and will be addressed in our future release.

**Comment by RajithaKumara** [comment]
This issue was fixed in OrangeHRM 5.3. Get the latest build [here](https://sourceforge.net/projects/orangehrm/).
