### ISSUE TITLE
Invalid URL in OS Mobile App (OHRM 5.2)

### ISSUE THREAD

**Issue by novastream** [orangehrm/orangehrm#1519]
**Environment details**
OrangeHRM version: 5.2
OrangeHRM source: Release build from [Sourceforge](https://sourceforge.net/projects/orangehrm)
Platform: Ubuntu 22.04
PHP version: 7.4
Database and version: MySQL 8.0
Web server: nginx 1.24

If applicable:
Browser: N/A

**Describe the bug**
When trying to add Instance URL to the OrangeHRM Open Source app I get "Invalid URL"

**To Reproduce**
Start the app and add your OrangeHRM URL (https://hr.mydomain.com)

**Expected behavior**
The app should login

**What do you see instead:**
0.0.0.0 - - [02/Nov/2022:22:59:17 +0100] "POST /oauth/issueToken HTTP/2.0" 404 146 "-" "okhttp/3.12.12"
0.0.0.0 - - [02/Nov/2022:22:59:17 +0100] "POST /symfony/web/oauth/issueToken HTTP/2.0" 404 146 "-" "okhttp/3.12.12"
0.0.0.0 - - [02/Nov/2022:22:59:17 +0100] "POST /symfony/web/index.php/oauth/issueToken HTTP/2.0" 404 36 "-" "okhttp/3.12.12"
0.0.0.0 - - [02/Nov/2022:22:59:17 +0100] "POST /index.php/oauth/issueToken HTTP/2.0" 302 0 "-" "okhttp/3.12.12"
0.0.0.0 - - [02/Nov/2022:22:59:17 +0100] "GET /index.php/oauth/web/index.php/auth/login HTTP/2.0" 302 0 "-" "okhttp/3.12.12"
0.0.0.0 - - [02/Nov/2022:22:59:17 +0100] "GET /index.php/oauth/web/index.php/auth/web/index.php/auth/login HTTP/2.0" 302 0 "-" "okhttp/3.12.12"
0.0.0.0 - - [02/Nov/2022:22:59:17 +0100] "GET /index.php/oauth/web/index.php/auth/web/index.php/auth/web/index.php/auth/login HTTP/2.0" 302 0 "-" "okhttp/3.12.12"
0.0.0.0 - - [02/Nov/2022:22:59:17 +0100] "GET /index.php/oauth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/login HTTP/2.0" 302 0 "-" "okhttp/3.12.12"
0.0.0.0 - - [02/Nov/2022:22:59:17 +0100] "GET /index.php/oauth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/login HTTP/2.0" 302 0 "-" "okhttp/3.12.12"
0.0.0.0 - - [02/Nov/2022:22:59:17 +0100] "GET /index.php/oauth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/login HTTP/2.0" 302 0 "-" "okhttp/3.12.12"
0.0.0.0 - - [02/Nov/2022:22:59:17 +0100] "GET /index.php/oauth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/login HTTP/2.0" 302 0 "-" "okhttp/>
0.0.0.0 - - [02/Nov/2022:22:59:17 +0100] "GET /index.php/oauth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/login HTTP/2.0">
0.0.0.0 - - [02/Nov/2022:22:59:17 +0100] "GET /index.php/oauth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/a>
0.0.0.0 - - [02/Nov/2022:22:59:18 +0100] "GET /index.php/oauth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/a>
0.0.0.0 - - [02/Nov/2022:22:59:18 +0100] "GET /index.php/oauth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/a>
0.0.0.0 - - [02/Nov/2022:22:59:18 +0100] "GET /index.php/oauth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/a>
0.0.0.0 - - [02/Nov/2022:22:59:18 +0100] "GET /index.php/oauth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/a>
0.0.0.0 - - [02/Nov/2022:22:59:18 +0100] "GET /index.php/oauth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/a>
0.0.0.0 - - [02/Nov/2022:22:59:18 +0100] "GET /index.php/oauth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/a>
0.0.0.0 - - [02/Nov/2022:22:59:18 +0100] "GET /index.php/oauth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/a>
0.0.0.0 - - [02/Nov/2022:22:59:18 +0100] "GET /index.php/oauth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/a>
0.0.0.0 - - [02/Nov/2022:22:59:18 +0100] "GET /index.php/oauth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/a>
0.0.0.0 - - [02/Nov/2022:22:59:18 +0100] "GET /index.php/oauth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/a>
0.0.0.0 - - [02/Nov/2022:22:59:18 +0100] "GET /index.php/oauth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/auth/web/index.php/

If issue related to any other
- src/log/orangehrm.log 

**Screenshots**

**Additional context**

**Comment by Super-Chama** [comment]
Hi @novastream please note that the OrangeHRM 5X is not yet supported with our mobile apps. It is next in our roadmap and will be incorporated in a future release.

**Comment by hcaz** [comment]
Is there any timeline for when this will be supported? Or a publically available roadmap to track

**Comment by Super-Chama** [comment]
@hcaz it's planned for April, please refer https://github.com/orangehrm/orangehrm/issues/1651
