### ISSUE TITLE
Web Server FAILED during set up OrangeHRM 5.2

### ISSUE THREAD

**Issue by jazzx7** [orangehrm/orangehrm#1529]
**Environment details**
OrangeHRM version: 5.2
OrangeHRM source: Release build from [Sourceforge](https://sourceforge.net/projects/orangehrm) or Git clone
PHP version: (ver 8.0.24)
Database and version: 10.5.16-MariaDB-cll-lve
Web server: Linux x86_64

**Describe the bug**
During the insulation, in step (4) System check - it gives me the error 'Web server failed'.

**What do you see instead:**
Error message (see the screenshot below)

**Screenshots**
![Capture10](https://user-images.githubusercontent.com/91319514/201239162-4016a2dc-db7d-4e30-bfa7-41f6257b9439.PNG)

**Comment by RajithaKumara** [comment]
Hi @jazzx7 ,
Can you apply the patch mentioned in [this comment](https://github.com/orangehrm/orangehrm/issues/1517#issuecomment-1298482549)

**Comment by RajithaKumara** [comment]
This issue was fixed in OrangeHRM 5.3. Get the latest build [here](https://sourceforge.net/projects/orangehrm/).

**Comment by Admin-SDS** [comment]
I see the same issue maybe due to which I find another error during installation step "Applying database changes" showing Request failed with status code 500. For more details check the error log in /src/log/installer.log file 

Server: Linux (Hostinger H panel)

**Comment by devishke-orange** [comment]
Hi @Admin-SDS 

Could you open a new issue on GitHub so that we can continue the conversation there? Please upload your installer.log file as well (located in <your-orangehrm-folder>/src/log)

Alternatively you can send the log file to ossupport@orangehrm.com
