### ISSUE TITLE
Unable to change fields in the PIM Personal Details page using FTP

### ISSUE THREAD

**Issue by paulchike** [orangehrm/orangehrm#1543]
**Environment details**
OrangeHRM version: 5.2
OrangeHRM source: Release build from [Sourceforge](https://sourceforge.net/projects/orangehrm) 
Platform: output of `uname -a` (UNIX), or version and 32 or 64-bit (Windows), or Docker
PHP version: output of `php 8.1
Database and version: MySQL 5.7
Web server: Apache 2.4
If applicable:
Browser: Chrome, Safari

**Describe the bug**
Changes made in the file using FTP doesn't effect

**To Reproduce**
I tried to make changes in the html/src/plugins/orangehrmPimPlugin/Api/EmployeePersonalDetailAPI  but it doesn't effect in the front interface after saving it. I am not sure if maybe I am working on the wrong folder. Please help !

**Expected behavior**
Changes should effect in the front interface

**What do you see instead:**
No changes

If issue related to installation:
-html/src/plugins

If issue related to any other
- src/log/orangehrm.log 

**Screenshots**

**Additional context**

**Comment by Super-Chama** [comment]
Closing due to similar issue is active https://github.com/orangehrm/orangehrm/issues/1562
