### ISSUE TITLE
Can't Crate Databases

### ISSUE THREAD

**Issue by chamin123** [orangehrm/orangehrm#1559]
Hello,
MariaDB Version 5.5
PHP Version 8.1.13

I have installed OrangeHRM V 5.2. but There is an error "Unexpected Error" in Database Creation Page.Pl Help
![OHRm](https://user-images.githubusercontent.com/119924550/205852712-e662d018-9cb2-49c2-afc3-e1e876410a9c.PNG)

**Comment by RajithaKumara** [comment]
Hi @chamin123 
Please send us the installer error log which is located `src/log/installer.log`.
Make sure to remove sensitive data if any.

**Comment by chamin123** [comment]
Hello @RajithaKumara 

It says "cannot open ‘/src/log/installer.log’ for reading: No such file or directory"

**Comment by RajithaKumara** [comment]
@chamin123 ,
Can you give write permission to `src/log` directory. Anyway, this will require you to continue the next step.
Then `installer.log` should create once you submit form in the database configuration

**Comment by Super-Chama** [comment]
Hi @chamin123 you need to install these php extensions in your environment. on Debain based environment, use following command to install these extensions.

`sudo apt-get install php-xml php-zip php-intl php-gd php-ldap`

**Comment by chamin123** [comment]
Hello @Super-Chama @RajithaKumara 

Yeah I have successfully installed OHRM 5 on CentOS 7.

Is there any method to add user roles like Manager,Supervisor?

**Comment by Super-Chama** [comment]
@chamin123 Glad you have resolved the issue. OrangeHRM starter version do not support user role management. It only has the inbuilt user roles such as Admin/ESS. Supervisor user role is automatically assigned when you add subordinates to an employee. You can learn more on our [help portal](https://starterhelp.orangehrm.com/hc/en-us)

For more fined grained user role management features and more you can checkout our [enterprise version](https://www.orangehrm.com/features/hr-administration).

**Comment by chamin123** [comment]
@Super-Chama noted and thank you very much your support.

**Comment by RajithaKumara** [comment]
This issue was fixed in OrangeHRM 5.3. Get the latest build [here](https://sourceforge.net/projects/orangehrm/).
