### ISSUE TITLE
file not found 

### ISSUE THREAD

**Issue by m7mod** [orangehrm/orangehrm#156]
/home/hr/public_html/symfony/lib/vendor/autoload.php

file not found and it's required on 

/home/hr/public_html/symfony/plugins/orangehrmRESTPlugin/config/orangehrmRESTPluginConfiguration.class.php
line 7

**Comment by samanthajayasinghe** [comment]
You have to run composer update on (projectroot)/symfony/lib folder if you clone via github

**Comment by m7mod** [comment]
how can i do this ?


compose update doesn't work 

Warning: unknown mime-type for "update" -- using "application/octet-stream"

**Comment by m7mod** [comment]
thank you, issue solved and composer working well
