### ISSUE TITLE
The Leave page ERROR when using the Employee account to login

### ISSUE THREAD

**Issue by anhtester** [orangehrm/orangehrm#1561]
![image](https://user-images.githubusercontent.com/87883620/205980695-ef736f27-97bf-4ce9-9ed4-29a52bacd988.png)

When using the Admin role is Ok

![image](https://user-images.githubusercontent.com/87883620/205981483-43e80b5a-cb53-463a-8284-d81ce58fc133.png)

**Comment by Super-Chama** [comment]
Hi @anhtester to use the leave module, you need to define the leave period and save. after this only users can expect to use the leave module. ESS Users are not allowed to see configuration pages such as this, that is why the page is giving 404 here.

**Comment by anhtester** [comment]
Yeah, thank you !! @Super-Chama 
I don't think letting it throw an error like that. There should be a UI page to demonstrate this.

- How do I manage User Roles? I can't find a place to manage it on the UI.
