### ISSUE TITLE
Orangehrm5.2 clear cache

### ISSUE THREAD

**Issue by paulchike** [orangehrm/orangehrm#1562]
I made changes in the src/client/src/orangehrmPimPlugin/pages/employee/EmployeePersonalDetails.vue file but it did not update on the end user interface. I can see that it effected when I go to the inspect option on the browser interface, which means the code applied.

I tried to clear cache using this command line **_php bin/console cache:clear_**  but it did not work. Does anyone face similar issue, is there a fix for this or a way around this?

Thanks.

**Comment by paulchike** [comment]
@RajithaKumara Can you please help me with this? Regards

**Comment by Super-Chama** [comment]
Hi @paulchike to customise OrangeHRM application I suggest you refer [this guide](https://github.com/orangehrm/orangehrm/wiki/5.x-development-guide) and setup your development environment first. As you may have noted, the front-end concerns are handled by separate vue.js application. After any supposed change you need to build the FE application to get it reflected in the browser. you can use `yarn build` command to build the app.

**Comment by devishke-orange** [comment]
I'm closing this as the question has been answered.
