### ISSUE TITLE
OrangeHRM send personal details to OrangeHRM on install

### ISSUE THREAD

**Issue by HenrysCat** [orangehrm/orangehrm#1574]
Then the emails start coming in, and if you included a phone number they start calling.

This should be optional and people should be informed this will happen, also people should be given an oportunity to opt out of any personal information being sent anywhere.

**Comment by mckaygerhard** [comment]
This is pretty importnat, today telemetry is a case of care...

**Comment by kavithagurusamy** [comment]
You can request to permanently delete this information to OrangeHRM by sending an email as described in this screenshot. Please mention the instance ID that is created for your instance. 

![image](https://user-images.githubusercontent.com/25813012/208109171-4180243f-bf93-4eca-ab21-c8827f90b29e.png)

The option of opting out of sending the registration data at the installation step will be available in the future release. By registering, You will be eligible for free support via emails, receive security alerts, and newsletters from OrangeHRM.

**Comment by mckaygerhard** [comment]
Wow:

> The option of opting out of sending the registration data at the installation step will be available in the future release. By registering, You will be eligible for free support via emails, receive security alerts, and newsletters from OrangeHRM.


that's i call good bussines strategy O.ou

**Comment by HenrysCat** [comment]
> Wow:
> that's i call good bussines strategy O.ou

That's what I call an invasion of privacy

**Comment by kavithagurusamy** [comment]
This feature is released in OrangeHRM 5.3 version.
