### ISSUE TITLE
Search bar in side bar disappear when type in special character 

### ISSUE THREAD

**Issue by NamPham1906** [orangehrm/orangehrm#1583]
### OrangeHRM version

5.1

### Environment details

- OrangeHRM source:
- Platform:
- PHP version:
- Database and version:
- Web server:
- Browser:

### Describe the bug

When I type in special character ("?", "/") in side bar for quick navigation (of home page), my search bar just disappear from the screen.

### Expected behavior

Should show error message.

**Comment by NamPham1906** [comment]
![312251523_856140012074214_7467596656607268039_n](https://user-images.githubusercontent.com/61858329/210090081-e24bd791-79bd-42e1-9ba5-fbedbe59b958.png)

**Comment by kavithagurusamy** [comment]
This issue is fixed from OrangeHRM 5.4 version
