### ISSUE TITLE
Functional button in DOB datepicker is covered up in employee detail

### ISSUE THREAD

**Issue by NamPham1906** [orangehrm/orangehrm#1584]
### OrangeHRM version

5.1

### Environment details

- OrangeHRM source:
- Platform:
- PHP version:
- Database and version:
- Web server:
- Browser:
![Uploading 318207023_2662633200538512_3595742266437223801_n.png…]()

### Describe the bug

"Today" "Close" and "Reset" Buttons in Date of birth datepicker is covered and cannot be clicked In employee detail screen. 

### Expected behavior

Functional buttons should be showed

**Comment by NamPham1906** [comment]
![318207023_2662633200538512_3595742266437223801_n](https://user-images.githubusercontent.com/61858329/210139046-2db28b95-92db-490c-97d4-eb5e388947d8.png)

**Comment by kavithagurusamy** [comment]
This issue is fixed from OrangeHRM 5.4 version
