### ISSUE TITLE
Database Configuration

### ISSUE THREAD

**Issue by ketmox** [orangehrm/orangehrm#162]
hi everyone
I need your help please, well i would like to install orangeHRM but i gives me an error in Database Configuration here is the screens : 
![dbconf](https://user-images.githubusercontent.com/27818488/27177477-0e8b265e-51b6-11e7-8e7e-601b3c10f31b.png)
and here's the error : 
![error](https://user-images.githubusercontent.com/27818488/27177502-226c0b84-51b6-11e7-887e-90c94ea6e231.png)

and thank you !

**Comment by samanthajayasinghe** [comment]
Hi, 
Are you deploying in php 7+ ? 
Right now it's working only on php5.6 ( <).

**Comment by ketmox** [comment]
yeah I'm deploying in php 7.0.13 using xampp

**Comment by samanthajayasinghe** [comment]
then It's better to use an older version of XAMPP which based on php 5.6

**Comment by ketmox** [comment]
Ok thank you !
