### ISSUE TITLE
 OrangeHRM CSS/font issue

### ISSUE THREAD

**Issue by jazzx7** [orangehrm/orangehrm#1640]
### OrangeHRM version

5.3

### Environment details

- Platform: Linux us-phx-web736
- PHP version: 8.1
- Database and version:
- Web server: CGI/FastCGI
- Browser: Chrome

### Describe the bug

After installing orangehrm-5.3, I noticed that the font is broken. It's hard to read. I tried different browsers, and I got same result. Any help? 

![Capture10](https://user-images.githubusercontent.com/91319514/224375880-e9b3ed25-5b88-44e2-bb66-3e6d9d7229a8.PNG)
![image](https://user-images.githubusercontent.com/91319514/224376483-753b5628-fc93-4512-9dd5-51fbef4acc12.png)

### To reproduce

The font is broken across the whole app.

### Expected behavior

I believe the original font is clearer.

**Comment by Super-Chama** [comment]
Looks like the browser has switched to default browser font, possibly due to some error serving the font files from server.

@jazzx7 can you check the browser developer console/network tab and see if anything is preventing loading the fonts (any errors, any blocked requests etc)

**Comment by jazzx7** [comment]
@Super-Chama, thanks! I have checked, and the site is secured.. and all permissions are granted but still the same result. Any thoughts?

**Comment by jazzx7** [comment]
I've just noticed its only give the correct view on Firefox, not Chrome or Edge. How I can enable the original view on Chrome?

**Comment by Super-Chama** [comment]
@jazzx7 can you check our [demo](https://opensource-demo.orangehrmlive.com/web/index.php/auth/login) and confirm whether the fonts work there for you?

**Comment by kavithagurusamy** [comment]
Closing the ticket as no response from the reporter.
