### ISSUE TITLE
Payroll

### ISSUE THREAD

**Issue by chandachewe10** [orangehrm/orangehrm#1655]
**Is your feature request related to a problem? Please describe.**
Compiling a Payroll For All Employees within the system
**Describe the solution you'd like**
Please describe the desired behavior.
An admin runs the payroll by selecting the start date and end date upon which a payroll is supposed to run. The system compiles the payslips and stores them in the systems storage, the admin later downloads the payslips in compressed format for all employees with password protected where the password is each particular employees employee number  
**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.
Let me know if a PR will be necessary for this

**Comment by kavithagurusamy** [comment]
This feature is not planned for opensource version, this is facilitated in OrangeHRM Advance version
