### ISSUE TITLE
Automated Mails, when Applicant applies for job, and when meetings are scheduled

### ISSUE THREAD

**Issue by EliasBA** [orangehrm/orangehrm#1664]
**Is your feature request related to a problem? Please describe.**

Currently, we have noticed that when a job offer is created and an applicant applies, they don't receive a confirmation email. Similarly, when a meeting with a supervisor is scheduled in the backend, neither the applicant nor the supervisor receive an email. This is causing confusion and a lack of transparency for applicants and supervisors.

**Describe the solution you'd like**

We would like to request that the existing email service in OrangeHRM be extended to include automatic confirmation emails for job applicants and meeting invitations for both applicants and supervisors. We hope that this feature is already included in the system but has not been activated, and we would appreciate any guidance on how to configure it.
 

**Describe alternatives you've considered**

We have considered manually sending confirmation and meeting invitation emails, but this is time-consuming and prone to errors. We have also looked into third-party email services, but we would prefer to have this functionality integrated within OrangeHRM for ease of use and consistency.

**Comment by EliasBA** [comment]
Hi,
any take on this?:)

**Comment by kavithagurusamy** [comment]
This feature is not planned for opensource version, this is facilitated in OrangeHRM Advance version
