### ISSUE TITLE
Translation errors | Some texts are and cannot translated in OrangeHRM

### ISSUE THREAD

**Issue by mrdanleey** [orangehrm/orangehrm#1665]
### OrangeHRM version

5.3

### Environment details

- OrangeHRM source: Github
- Platform: Ubuntu
- PHP version: 8
- Database and version: MariaDB
- Web server: Apache 2.4
- Browser: Vivaldi, Edge en Firefox

### Describe the bug

At the Recruitment module (Click on Recruitment) and then see the records on the page) (the status "Interview Passed" in the candidate records is not translated.

Also when clicking on a candidate and see the candidate history I see a non-translated item: 
recruitment.candidate_shortlisted_for_vacancy_by_employee

The text "Interview Passed" is translated into Dutch (language I'm using) but not here on the page, and I could not find the other text in the translation part of OrangeHRM

**Comment by RajithaKumara** [comment]
Hi @mrdanleey ,
I hope you are talking about `Admin > Configuration > Language Packages` feature.
For the particular language string key `recruitment.candidate_shortlisted_for_vacancy_by_employee` the resulting string should be `Shortlisted for {vacancy} by {employee}` in en_US.

When it is translated, it should be like `Op de shortlist gezet voor {vacancy} door {employee}` (Note: I just used a tool to translate, I'm not sure about the semantics).
`{vacancy}` and `{employee}` are variables in this case, values will be assigned when rendering the screen. Also, it's okay to change the position of the variables based on the language.  (e.g. in sinhala `{employee} විසින් {vacancy} සඳහා කෙටි ලැයිස්තුගත කර ඇත`). 
But you can't use translated words for variables. Variables should not translate.

Summary for Source Text: `Shortlisted for {vacancy} by {employee}`
|  | Translated Text | Reason |
| - | - | - |
| ✓ | Op de shortlist gezet voor {vacancy} door {employee} | |
| ✓ | Door {employee} op de shortlist gezet voor {vacancy} | It's okay to change the position of the variables to achieve the correct semantics |
| ✗ | Door {werknemer} op de shortlist gezet voor {vacature} | Should **not** translate variables |
| ✗ | Door employee op de shortlist gezet voor vacancy | Variables should be in curly braces. e.g. {employee} and {vacancy} |
| ✓ | Op de shortlist voor {vacancy} | Can remove variables if it's not necessary. e.g. here {employee} removed |
| ✗ | {candidate}: Shortlisted for {vacancy} | Can **not** introduce new variables. Should have only variables which are in `Source Text` |

**Technical background;**
We are using Intl ICU message formatting to support complex language translation. such as pluralization, conditional formatting.
References: [[1]](https://unicode-org.github.io/icu/userguide/format_parse/messages/), [[2]](https://symfony.com/doc/current/reference/formats/message_format.html).
For the moment we have a limitation when saving translated text, we can't validate whether it's in the proper format. This will lead to some rendering breaks in the browser.

Provide a screenshot of the browser console, when you are on the particular screen if the above explanation does not work for you.

**Comment by mrdanleey** [comment]
Hi RajithaKumara,

Indeed I'm talking about the Languages Pack function :-)

Here is a screenshot so you can see what I see (I can't see the language string mentioned in your reaction:
![image](https://user-images.githubusercontent.com/55659208/232415047-486d0011-f36a-43f8-b38e-b8d9ae3eef7e.png)

When I put OrgangeHRM in English US the string is translated but I can't find the string in the English Language Pack also.

**Comment by kavithagurusamy** [comment]
Resolved in 5.5. Upgrade the system to OrangeHRM 5.5 to get the fix.
