### ISSUE TITLE
5.3 app

### ISSUE THREAD

**Issue by Avey777** [orangehrm/orangehrm#1670]
### OrangeHRM version

5.3

### Environment details

Your demo is version 5.3, but the app requires version 5.4, so how can we use the app?

### Describe the bug

Your demo is version 5.3, but the app requires version 5.4, so how can we use the app?

**Comment by Super-Chama** [comment]
Hi @Avey777 I hope you're referring to the mobile app? The new version of mobile app and 5.4 version will be released later this month. 
You can get updates by following this thread. https://github.com/orangehrm/orangehrm/issues/1651

**Comment by Avey777** [comment]
> 

ok  Looking forward to a quick release
