### ISSUE TITLE
Open translation online

### ISSUE THREAD

**Issue by uda** [orangehrm/orangehrm#168]
I am testing the system, and in order to use it, some users will need an interface translated to Hebrew (he_IL). So I uploaded the messages xliff file to transifex so I can get help in translating.

I would appreciate if you take over the organization I opened in transifex:
https://www.transifex.com/orangehrm/orangehrm/dashboard/

I have some issues with the current state, I will open separate issues about them later (like generic info you can get from the CLDR project - countries, currencies etc.)

Updated question: Where can I find the full `en_US` xliff file with notes? I took the file from the repo, but the `de_DE` and `es_ES` from localizit have 4000 and something source strings while the one in the repo has just 1000 and something.

**Comment by samtuke** [comment]
Any progress on translations in the last year?

**Comment by kavithagurusamy** [comment]
Samtuke
OrangeHRM 4.6 version is released that admin can new translation pack or edit the existing available package.
