### ISSUE TITLE
Quick Start Guide or Documentation for Configuration of OAuth 2.0 Integration [5.4 Release]

### ISSUE THREAD

**Issue by joelicatajr** [orangehrm/orangehrm#1681]
**Is your feature request related to a problem? Please describe.**
OAuth 2.0 support was released with 5.4 but it is unclear how to configure this.

**Describe the solution you'd like**
Provide updated documentation for an example configuration using a common Enterprise IDP like Azure AD App Registration. Alternatively, provide a quick reply with essential information in the GitHub issue response. 

**Describe alternatives you've considered**
I searched for available Orange HRM resources on the support site and GitHub. Being this is a newly released feature I understand documentation may not yet be available. 

---

**Thanks for your work on the project, and congrats on the release of 5.4!**

**Comment by RajithaKumara** [comment]
Hi @joelicatajr 
Happy to hear from you. We will publish the grant types OrangeHRM 5.4 supports and the current limitations. Our main goal was to support OrangeHRM Mobile application as first priority as we were getting more requests.

**Comment by joelicatajr** [comment]
Hi @RajithaKumara
Thanks, I appreciate your help, and certainly understand regarding the priority for the OrangeHRM Mobile App.

**Comment by joelicatajr** [comment]
Just checking in on this one to see if there are any updates.

**Comment by joelicatajr** [comment]
We have decided to stop using Orange HRM.
