### ISSUE TITLE
Update user always disable it (in spanish language)

### ISSUE THREAD

**Issue by tonimiquelsogeti** [orangehrm/orangehrm#1684]
### OrangeHRM version

5.4

### Environment details

- OrangeHRM source: Sourceforge
- Platform: Windows
- PHP version: 8.2.4
- Database and version:  MariaDB 10.4.28
- Web server: Apache/2.4.56
- Browser: Firefox/Chrome

### Describe the bug

When a user is modified (or just edit and save without changes) this user is permanently disabled. Even you change to enable, when save the profile keeps disabled.

### To reproduce

1. Create a new user
2. Save the user
3. Check on the list that the user is enabled
4. Click on edit user
5. Save the edition page (making or not any change) and check the option "Active" is selected
6. Check on the list that user is disabled

### Expected behavior

User must be active if "active" option is selected on the profile

**Comment by tonimiquelsogeti** [comment]
Hi @RajithaKumara, thanks for your quick response!

As I notice that in English this bug not appears, and for now we've not a lot of modifications on this section, as a workaround I just change the language if I need to operate with users.

But thanks a lot for your work!

Regards!

**Comment by ManulMax** [comment]
Hi @tonimiquelsogeti ,
Thank you for reporting this issue. There is a patch attached here that you can apply as a fix for the issue. Please refer the following steps to apply patch. 

- **Backup the code base and database**
- **This patch only works with 5.4 release**
- Download the zip file that contains patch
- Unzip the downloaded file
- Replace  “client” folder with “client” folder in your src/client path
- Go inside client folder and run ‘yarn install’
- Then run ‘yarn build’

**Incase if the fix not working**
- Close your browser and try again
- Remove the browser cache
- Remove “node_modules” folder inside src/client and run ‘yarn install’ again

[client.zip](https://github.com/orangehrm/orangehrm/files/11504191/client.zip)

**Comment by kavithagurusamy** [comment]
Resolved in 5.5. Upgrade the system to OrangeHRM 5.5 to get the fix.
