### ISSUE TITLE
Issues where you can't set a password policy with an admin account

### ISSUE THREAD

**Issue by minnow-op** [orangehrm/orangehrm#1686]
### OrangeHRM version

5.4

### Environment details

- OrangeHRM source: Docker (https://hub.docker.com/r/orangehrm/orangehrm)
- Platform: linux
- PHP version: 8.1
- Database and version:MariaDB 10.2
- Web server:apache
- Browser:Chrome

### Describe the bug

No UI exists for administrators to set password policies.
According to the release notes, it seems like there should be, but there isn't.

5.4 feautre
Password Policy Enforcement
- Enables admins to configure password policies for users and automatically enforce those policies whenever a user creates a new password.

### To reproduce

1. Login to admin user
2. Go to settings menu

### Expected behavior

1. Login to admin user
2. Go to settings menu
3. Configure password policy
4. I can set a password policy

**Comment by ManulMax** [comment]
Hi @minnow-op ,
In our application currently we don't have admin screen for change the configurations of password policies. So you have to change values in database table. 
You can use the following query to update password policies.

```
/*
Supported values for default required password strength
veryWeak, weak, better, strong, strongest
*/
UPDATE hs_hr_config
SET value = 'better'
WHERE name = 'auth.password_policy.default_required_password_strength';

/*
Supported values - true / false
*/
UPDATE hs_hr_config
SET value = 'true'
WHERE name = 'auth.password_policy.is_spaces_allowed';

/*
Add value greater than 0
*/
UPDATE hs_hr_config
SET value = '2'
WHERE name = 'auth.password_policy.min_lowercase_letters';

/*
Add value greater than 0
*/
UPDATE hs_hr_config
SET value = '2'
WHERE name = 'auth.password_policy.min_numbers_in_password';

/*
Add value greater than 0
*/
UPDATE hs_hr_config
SET value = '12'
WHERE name = 'auth.password_policy.min_password_length';

/*
Add value greater than 0
*/
UPDATE hs_hr_config
SET value = '3'
WHERE name = 'auth.password_policy.min_special_characters';


/*
Add value greater than 0
*/
UPDATE hs_hr_config
SET value = '2'
WHERE name = 'auth.password_policy.min_uppercase_letters';
```

**Comment by minnow-op** [comment]
Hi @ManulMax,

Are there any plans to add a password policy management screen to the admin page?

I was just curious.
It's nice to still be able to use such great service.

Thank you for your kind reply.

**Comment by ManulMax** [comment]
Hi @minnow-op , 
Thank you for the suggestion. For the moment we don't have any plan for a password policy management screen. But we will consider this in future and we'll add it as feature request for the product.

**Comment by kale1d0code** [comment]
@ManulMax 
is it possible to set the min_* values to 0?
