### ISSUE TITLE
Edit Candidate attached CV

### ISSUE THREAD

**Issue by dzalbsch** [orangehrm/orangehrm#1694]
### OrangeHRM version

5.4

### Environment details

- OrangeHRM source: https://opensource-demo.orangehrmlive.com
- Platform: https://opensource-demo.orangehrmlive.com
- PHP version: [Online Test Server](https://opensource-demo.orangehrmlive.com)
- Database and version: https://opensource-demo.orangehrmlive.com
- Web server: https://opensource-demo.orangehrmlive.com
- Browser: Firefox/Chrome (actual)

### Describe the bug

When editing a canditates profile and attach a CV (PDF < 1 MB) save dos not work.
Delete current works
add new does not work
replace current does not work

File name is shown in selection. Is this a known bug? Search does not give any results.

### To reproduce

Create new candidate without attached CV.
Save.
Edit newly created candidate.
Follow normal upload instructions for uploading.
Click save.
(--> no result)

### Expected behavior

save file to database

### Relevant log output

```shell
n/a
```

**Comment by kavithagurusamy** [comment]
Issue fixed in OrangeHRM 5.5 version
