### ISSUE TITLE
Duration time in Clock in's and Timesheets

### ISSUE THREAD

**Issue by gavinjb22** [orangehrm/orangehrm#1695]
### OrangeHRM version

5.4

### Environment details

- OrangeHRM source: github
- Platform: Unix 
- PHP version:  alt-php82
- Database and version: Database client version: libmysql - mysqlnd 7.4.33
- Web server: linux
- Browser: Google Chrome
 

### Describe the bug

When I submit timesheets and clock in-outs for 30 mins, it always comes out 50 mins on duration and not 30 mins 

For example:

22-05-2023 11:00 AM GMT +01:00
22-05-2023 11:30 AM GMT +01:00
0.50

### Expected behavior

For it to say 30 mins instead of 50 mins is there any way to change this please?

**Comment by ManulMax** [comment]
Hi @gavinjb22,
I would like to kindly clarify a point regarding the system's behavior. It seems there may have been a misunderstanding.
If you take close look at the header of the table it shows **Duration (Hours).** Therefore, in your particular case, it indicates a duration of 0.5 hours, which equates to half an hour or 30 minutes.

![Screenshot from 2023-05-22 16-08-14](https://github.com/orangehrm/orangehrm/assets/49731724/0b0a6abb-81b6-4815-b38e-af184f2291af)

Thank You.

**Comment by gavinjb22** [comment]
Ok thank you
