### ISSUE TITLE
Offering help for translations in French

### ISSUE THREAD

**Issue by Louis-Marie-W** [orangehrm/orangehrm#1700]
**Is your feature request related to a problem? Please describe.**
I am using OrangeHRM 5.4.
I have detected several texts which have not been translated in French.
Example: no record found

**Describe the solution you'd like**
I would be happy to help in translations, but I am not a developer.
How can I help?

**Describe alternatives you've considered**

**Comment by ManulMax** [comment]
Hi @Louis-Marie-W ,
We are delighted to know that you are interested in contributing to the Orange HRM open-source project. We want to inform you that we have recently updated our help article with content related to translations. You can follow the guidelines provided in the article to contribute your translations. We appreciate your willingness to contribute, and we look forward to your valuable contributions to the project. Thank you!

[**Help Article Link**](https://starterhelp.orangehrm.com/hc/en-us/articles/9075137055132-How-to-Add-a-New-Language-Package-to-OrangeHRM)

**Comment by kavithagurusamy** [comment]
Closing the ticket.
