### ISSUE TITLE
Bulk leave assignment

### ISSUE THREAD

**Issue by Flange0323** [orangehrm/orangehrm#1718]
Hi,

Does the opensource (free) version of OrangeHRM allow for bulk leave assignment?

Thanks

**Comment by RajithaKumara** [comment]
Hi @Flange0323
Unfortunately, OrangeHRM open source does not support Bulk leave assignment.
But bulk leave entitlement assigning is supported.

**Comment by kavithagurusamy** [comment]
Bulk leave assignment is only available in OrangeHRM advanced version.
