### ISSUE TITLE
Unit test Issue with orangehrm 4.9

### ISSUE THREAD

**Issue by vvsreerag** [orangehrm/orangehrm#1719]
### OrangeHRM version

4.9

### Environment details

- OrangeHRM source: 4.9
- Platform: Linux Mint
- PHP version: 7.3
- Database and version:
- Web server: Xampp
- Browser: Chrome

### Describe the bug

when i trying to run below command:

./symfony/lib/vendor/bin/phpunit

Im having error: 
PHP Warning:  Private methods cannot be final as they are never overridden by other classes in /opt/lampp/htdocs/orange/symfony/lib/vendor/phpunit/phpunit/src/Util/Configuration.php on line 162
PHP Fatal error:  Cannot acquire reference to $GLOBALS in /opt/lampp/htdocs/orange/symfony/lib/vendor/phpunit/phpunit/src/Util/Configuration.php on line 504

Please kindly help me to resolve this issue

**Comment by RajithaKumara** [comment]
Hi @vvsreerag
Thanks for trying out OrangeHRM. But 4.9 version already met the EOL, and 4.10.1 is the latest 4.x version. So we will provide security fixes for 4.x, but not actively working on that branches. Please checkout [main branch](https://github.com/orangehrm/orangehrm/tree/main) which is based on 5.x version. (Current version: 5.5)
