### ISSUE TITLE
Failed to Update to 5.5 from 4.10.1

### ISSUE THREAD

**Issue by kale1d0code** [orangehrm/orangehrm#1724]
### OrangeHRM version

5.5

### Environment details

- OrangeHRM source: Docker
- Platform: Docker
- PHP version: 8.1.20
- Database and version: MariaDB 10.9.4
- Web server: apache
- Browser: Chrome Version 114.0.5735.198 (Official Build) (64-bit)

### Describe the bug

Tried to update to OrangeHRM 5.5 from 4.10.1

pulled new image and recreated instance.
old version number showed (4.10.1)
and got 500 error code on login

reverted back to 4.10.1

### To reproduce

move from orangehrm/orangehrm:4.10.1 to orangehrm/orangehrm:5.5

### Expected behavior

version 5.5 to show on login screen
and to login successfully

### Relevant log output

```shell
H00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.16.208.2. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.16.208.2. Set the 'ServerName' directive globally to suppress this message
[Tue Jul 18 13:33:24.129233 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.56 (Debian) PHP/8.1.20 configured -- resuming normal operations
[Tue Jul 18 13:33:24.129298 2023] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
```

**Comment by RajithaKumara** [comment]
Hi @kale1d0code 
You need to use web upgrader or CLI upgrader to make database schema compatible with 5.5 release. Check this https://github.com/orangehrm/orangehrm/issues/1499#issuecomment-1286557419 thread for more information.
You can check this to follow [CLI upgrader](https://github.com/orangehrm/orangehrm/pull/1571#issuecomment-1353283606) and [this extra information](https://github.com/orangehrm/orangehrm/pull/1575#issuecomment-1370891786).

**Comment by kavithagurusamy** [comment]
Closing the ticket as no response from reporter, The required solution provided in the thread.
