### ISSUE TITLE
Localization error

### ISSUE THREAD

**Issue by zhangweimtan** [orangehrm/orangehrm#1726]
### OrangeHRM version

5.5

### Environment details

- OrangeHRM source: Dockerhub
- Platform: debian11  Docker
- PHP version:
- Database and version:Mysql 5
- Web server: 
- Browser:Edge

### Describe the bug

![image](https://github.com/orangehrm/orangehrm/assets/38522457/5fe177b5-a025-41af-a54c-7021b074ae33)
![image](https://github.com/orangehrm/orangehrm/assets/38522457/f2ec1333-73cf-46a8-ae22-d302e5cf56c0)

Chosen Admin, Configuration, Localization, selected language =Chinese(Simplified Chinese..), Saved, Language Pack applied, however Only Traditional Chinese shows.

i have seen a guide installation in other blog( A China Website Blog https://wbsu2003.gitee.io/2023/07/17/%E5%BC%80%E6%BA%90%E4%BA%BA%E5%8A%9B%E8%B5%84%E6%BA%90%E7%AE%A1%E7%90%86%E7%B3%BB%E7%BB%9FOrangeHRM/), shows the Simplified Chinese working well.

Tried asking the Blogger, he suggest me it would be a Bug.

![image](https://github.com/orangehrm/orangehrm/assets/38522457/1cb048b6-133a-482f-9574-8272a7d20664)

**Comment by zhangweimtan** [comment]
docker run -d \
   --restart unless-stopped \
   --name orangehrm \
   -p 80:80 \
   -v /root/data:/orangehrm \
   -e PUID=1000 \
   -e PGID=1000 \
   orangehrm/orangehrm:latest

**Comment by devishke-orange** [comment]
Hi @zhangweimtan, thank you for taking the time to create a separate issue for this. If you don't mind, could you provide some examples of the traditional Chinese that you are seeing?

I noticed a few things in the screenshot you provided. The second menu item ("個人信息管理系統") seems to contain a different translation than what we have in our database. Have you added any translations of your own to the database?

If you're not sure we can check this by going to the Language Packages screen and search for the relevant string in the simplified Chinese pack. (管理员 > 设置 > Language Packages > Click "Translate" on Simplified Chinese)
![image](https://github.com/orangehrm/orangehrm/assets/97493184/4777138f-26bb-4115-b406-dae18ed8400d)


For reference, the same string on my local system:
Simplified
![image](https://github.com/orangehrm/orangehrm/assets/97493184/724966ed-4ca7-4591-8648-dd3d8e484978)

Traditional
![image](https://github.com/orangehrm/orangehrm/assets/97493184/30011e24-93f9-4361-a75d-07ef8778ebc8)

**Comment by kavithagurusamy** [comment]
Are you still having the issue?
