### ISSUE TITLE
No Ubuntu Linux Instructions

### ISSUE THREAD

**Issue by P1xelC0da** [orangehrm/orangehrm#1727]
Would be nice to provide actual instructions at https://starterhelp.orangehrm.com/hc/en-us/articles/6187572000540-Prerequisites-for-installing-OrangeHRM-Starter-in-Linux if you're going to link it anywhere. I'm trying to run this without Docker, and I can't find anything.

**Comment by devishke-orange** [comment]
Hi @P1xelC0da. We are currently in the process of updating our environment setup and API documentation.

You can take a look at this gist to get an idea of the recommended server configuration for Apache and Nginx on Ubuntu: https://gist.github.com/RajithaKumara/87a69a196691083829ce4057dac47bdc

You can also follow our starter installation guide after you have configured your environment: https://starterhelp.orangehrm.com/hc/en-us/articles/5295915003666-OrangeHRM-Starter-Installation-Guide

Pinging @RajithaKumara for any additional material

**Comment by P1xelC0da** [comment]
Sounds good! Plan on using it with my nonprofit, https://codifyde.org 😁

-- 
Damian Freeman
Executive Director
Codifyde
--=_b96309dc4fe25a27811678bb0549d346
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html; charset=UTF-8

<html><head><meta http-equiv=3D"Content-Type" content=3D"text/html; charset=
=3DUTF-8" /></head><body style=3D'font-size: 10pt; font-family: Verdana,Gen=
eva,sans-serif'>
<p>Sounds good! Plan on using it with my nonprofit, <a href=3D"https://codi=
fyde.org">https://codifyde.org</a>&nbsp;=F0=9F=98=81</p>
<div id=3D"signature">-- <br />
<div class=3D"pre" style=3D"margin: 0; padding: 0; font-family: monospace">=
Damian Freeman <br />Executive Director<br />Codifyde<br /><br /><br /></di=
v>
</div>
</body></html>

--=_b96309dc4fe25a27811678bb0549d346--

**Comment by kavithagurusamy** [comment]
Closing the ticket as its answered above

**Comment by ManulMax** [comment]
Hi @P1xelC0da , You can refer our newly published API documentation here. [https://api-starter.orangehrm.com/](url)

**Comment by P1xelC0da** [comment]
I'm not looking to use the API at this time. I need docs to install 
OpenHRM on Ubuntu Linux.
