### ISSUE TITLE
Sendmail Not Sending

### ISSUE THREAD

**Issue by adamrpostjr** [orangehrm/orangehrm#1734]
### OrangeHRM version

5.4

### Environment details

- OrangeHRM source: Git Clone
- Platform: Linux <hostname> 4.18.0-477.21.1.el8_8.x86_64 #1 SMP Tue Aug 8 21:30:09 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- PHP version: 8.8.8
- Database and version:  10.6.15-MariaDB
- Web server: Nginx Proxy Pass to Apache
- Browser: Chrome / FireFox

### Describe the bug

When trying to sendmail using the built in sendmail I try to test the email and I get the following error message:
Aug 21 14:50:16 pleskhost1 postfix/sendmail[3501149]: fatal: stand-alone mode requires no recipient

### To reproduce

Test email config as sendmail

### Expected behavior

Send mail to test email address

### Relevant log output

```shell
/var/log/maillog:
Aug 21 14:50:52 pleskhost1 postfix/sendmail[3501412]: fatal: stand-alone mode requires no recipient
```

**Comment by ManulMax** [comment]
Hi @adamrpostjr , I think you are using PHP version: 8.2 or something, not PHP version: 8.8.8 . And can you please further check your mail server configurations ?

**Comment by adamrpostjr** [comment]
> 8.2
My applogies, that 8.8.8 was ment to be a placeholder and I forgot to update it. 
I am using 8.2.9, the mail server is working just fine for the rest of the plesk server just not this application.


Is there a specific version of sendmail that OrangeHRM supports?

**Comment by adamrpostjr** [comment]
We were able to correct this issue by changing the Sendmail command in the database.
It was ..../sendmail -bs we changed it to .../sendmail -t and that corrected the issue.

**Comment by adamrpostjr** [comment]
Closing Issue
