### ISSUE TITLE
Can i modify the current code ,add or remove some html code and then make a build

### ISSUE THREAD

**Issue by freakster00** [orangehrm/orangehrm#1738]
I just came to know about this amazing open source tool.I just want to know what further modification i can make to this project while setting up and running locally in my system.Can i modify the current code add or remove some html code and then make a build?

**Comment by RajithaKumara** [comment]
Hi @freakster00 ,
Yes, you can. Please follow the [development guide](https://github.com/orangehrm/orangehrm/wiki/5.x-development-guide). Make sure to build the front-end code once you have made your changes to the code.
If you want a development environment you can try out our [Docker development environment](https://github.com/orangehrm/orangehrm-os-dev-environment/wiki/How-to-setup).

I'm going to close this, If you need further information please reopen.
