### ISSUE TITLE
How to run app locally

### ISSUE THREAD

**Issue by jstawow** [orangehrm/orangehrm#1740]
i would like to get instruction how to run app locally in order to write e2e test locally on application.?

**Comment by devishke-orange** [comment]
Hi @jstawow!

Thank you for your interest in contributing to OrangeHRM Open-Source!

You can take a look at our development guide in our GitHub wiki to get an idea of how to run the system locally: https://github.com/orangehrm/orangehrm/wiki/5.x-development-guide

Also take a look at the advanced guide: https://github.com/orangehrm/orangehrm/wiki/5.x-advanced-guide

**Comment by jstawow** [comment]
will it work on mac?

**Comment by jstawow** [comment]
at the beginning i go it curl -sS https://getcomposer.org/installer | php
zsh: command not found: php
curl: (23) Failure writing output to destination
jakubstawowczyk@MacBook-Pro-Jakub orangehrm %

**Comment by RajithaKumara** [comment]
Hi @jstawow ,
I never tried on mac. But you can try MAMP, https://ampps.com/mamp/

**Comment by jstawow** [comment]
<img width="1075" alt="Zrzut ekranu 2023-08-31 o 14 22 49" src="https://github.com/orangehrm/orangehrm/assets/91880075/ea16165c-503a-4830-a055-5fd38e381fb3">
<img width="1157" alt="Zrzut ekranu 2023-08-31 o 14 23 04" src="https://github.com/orangehrm/orangehrm/assets/91880075/0f215146-2086-41a6-b068-f87a72cfa577">
I have like on screen and when the app should run on which localhost should it pop up automatically?

**Comment by jstawow** [comment]
@RajithaKumara
Where is the build that i can upload to mamp server?

**Comment by RajithaKumara** [comment]
[Here](https://starterhelp.orangehrm.com/hc/en-us/articles/5295915003666-OrangeHRM-Starter-Installation-Guide) is the OrangeHRM installation guide, you can find the build link there.
