### ISSUE TITLE
Problem with database configuration on max version of orangehrm is 5:0

### ISSUE THREAD

**Issue by jstawow** [orangehrm/orangehrm#1742]
i have such problem like on screen:

<img width="1196" alt="Zrzut ekranu 2023-09-1 o 14 31 47" src="https://github.com/orangehrm/orangehrm/assets/91880075/35172a76-4f58-40c9-85c7-ea6a6fb03aa4">
php version is : php@8.1
could you have any idea why is like that?

**Comment by RajithaKumara** [comment]
Hi,
I recommend you to use the current latest release: https://sourceforge.net/projects/orangehrm/files/stable/5.5/ OrangeHRM 5.5
And what is the database version that you are using? Also seems you didn't provide a `Privileged Database User Password`. Is your database `root` user password is empty? if so please try OrangeHRM 5.5. Still error there please use [this template](https://github.com/orangehrm/orangehrm/issues/new?assignees=&labels=5x&projects=&template=bug_report_5x.yml) to report a bug.

**Comment by jstawow** [comment]
https://github.com/orangehrm/orangehrm/wiki/5.x-development-guide
and i use MAMP
i updated the root password and all as it is in config file then i do not have error but is loader and then i am not moved to step 4
i also needed to change port on:
hostName: 127.0.0.2
beause when is hostName: 127.0.0.1
i have error:

The MySQL server isn't running on `127.0.0.1:3306`. It seems like you are using an incorrect TCP/IP port number or incorrect Unix socket file name. Please check whether MySQL server configuration as well as firewall and port blocking services are enabled.

so if i have:


<img width="1188" alt="Zrzut ekranu 2023-09-1 o 15 00 45" src="https://github.com/orangehrm/orangehrm/assets/91880075/337a8fda-b1a1-4f3a-b13a-00f6e9994039">

<img width="397" alt="Zrzut ekranu 2023-09-1 o 14 59 36" src="https://github.com/orangehrm/orangehrm/assets/91880075/234f4107-99f5-47a9-869f-75a4fc5e135e">

result is like this:
i updated the root password and all as it is in config file then i do not have error but is loader and then i am not moved to step 4

**Comment by devishke-orange** [comment]
Hi @jstawow 

Updating the values in the `cli_install_config.yaml` is only necessary if you are using our [CLI installer](https://github.com/orangehrm/orangehrm/pull/1575#issuecomment-1370849433).

Could you please elaborate on the error you are getting as it is not clear to us.
