### ISSUE TITLE
After once installed the app I have a login form, but I would like to register once again how to do that?

### ISSUE THREAD

**Issue by jstawow** [orangehrm/orangehrm#1747]
### OrangeHRM version

5.5

### Environment details

OrangeHRM source:
Platform: Mac
PHP version: 7.4.33
Database and version: MySql 5.7.39
Web server: Apache
Browser: Chrome

### Describe the bug

After once registered the app I have a login form, but I would like to register once again How to do that? What should I clean?
<img width="1197" alt="Zrzut ekranu 2023-09-7 o 13 05 52" src="https://github.com/orangehrm/orangehrm/assets/91880075/7826abc2-117b-4581-bce8-57a074257853">

**Comment by ManulMax** [comment]
Hi @jstawow , I think you want to reinstall the application. There are several ways that you can do that. Quick way to reinstall is remove the `confs` file in `lib/confs` and install again the application. And then you can re register the app with new data.

**Comment by devishke-orange** [comment]
You can also reset the instance via our `devTools` console (`php devTools/core/console.php i:reset)`.

 I will close this since the question has been answered.
