### ISSUE TITLE
Orangehrm 4.0 throughs HTTP ERROR 500 on installation

### ISSUE THREAD

**Issue by Awais-cb** [orangehrm/orangehrm#177]
Hi i have tried installing orangehrm 4.0 everything goes fines but on installation tab it gives HTTP ERROR 500.i am using php 5.6
please let me know if i am wrong at somewhere any help would be appreciated 
Thanks.

**Comment by Awais-cb** [comment]
error is being thrown by install.php

**Comment by Awais-cb** [comment]
[Wed Aug 16 12:40:19.859266 2017] [:error] [pid 4598] [client ::1:48808] PHP Fatal error:  require_once(): Failed opening required '/var/www/html/hrm4_0/symfony/lib/vendor/phpseclib/phpseclib/phpseclib/Crypt/Random.php'

**Comment by kavithagurusamy** [comment]
Hi Awais

1. Download the build (Zip) file from "https://github.com/orangehrm/orangehrm/tree/v4.0"
2. Extract it inside the web directory
3. Grant permission to the extracted folder (chmod -R 755)
4.Update composer then run the following command from symfony/lib
     - composer install
     - composer dump-autoload -o
5. Move to Symfony folder and execute following commands.
./symfony cc
./symfony d:build-model
./symfony o:publish-as
Access the system in web and install through web installer.

These steps are not required if you install from the stable release. 
https://sourceforge.net/projects/orangehrm/files/stable/4.0/orangehrm-4.0.zip/download

**Comment by Awais-cb** [comment]
sure let me try the stable release thanks for your help :)

**Comment by Awais-cb** [comment]
working almost fine now
