### ISSUE TITLE
error={"error":"invalid_csrf_token", "message":"CSRF token validation failed"}

### ISSUE THREAD

**Issue by jstawow** [orangehrm/orangehrm#1771]
### OrangeHRM version

5.5

### Environment details

- OrangeHRM source:
- Platform: 
- PHP version: 8.2.0
- Database and version: 
- Web server: 
- Browser: chrome

### Describe the bug

**I wrote such apiLogin test in playwright:
It seems that I wrote all the same as in your cypress tests
Why response that I got is html
Why there is an error which I put down in bold
What and how should I get from that response cookies or token in order to pass to another request** 
When I use those credentials in website then I am logged in successfully to the orangehrm application on localhost
  test.only('Api login', async ({ request }) => {
    
    const newIssue = await request.post('http://localhost:8888/web/index.php/auth/validate', {
      data: {
        username: 'user is correct',
        password: 'password is correct',
      },
    });
  
    expect(newIssue.ok()).toBeTruthy();
  
    const responseBody = await newIssue.text();
    console.log(responseBody);
  });
**output is as follow:**
Running 1 test using 1 worker
[desktop-chromium] › functional/tests/pimPage.spec.ts:212:8 › Admin user should be able to manage on pim page › Api login
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>OrangeHRM</title>
      <link rel="icon" href="/web/dist/favicon.ico?v=1695283103439">
    <link href="/web/dist/css/chunk-vendors.css?v=1695283103439" rel="preload" as="style">
    <link href="/web/dist/css/app.css?v=1695283103439" rel="preload" as="style">
    <link href="/web/dist/js/chunk-vendors.js?v=1695283103439" rel="preload" as="script">
    <link href="/web/dist/js/app.js?v=1695283103439" rel="preload" as="script">
      <link href="/web/dist/css/chunk-vendors.css?v=1695283103439" rel="stylesheet"/>
    <link href="/web/dist/css/app.css?v=1695283103439" rel="stylesheet"/>
</head>
<body>
  <style>
    :root {
            --oxd-primary-one-color:#FF7B1D;
            --oxd-primary-font-color:#FFFFFF;
            --oxd-secondary-four-color:#76BC21;
            --oxd-secondary-font-color:#FFFFFF;
            --oxd-primary-gradient-start-color:#FF920B;
            --oxd-primary-gradient-end-color:#F35C17;
            --oxd-secondary-gradient-start-color:#FF920B;
            --oxd-secondary-gradient-end-color:#F35C17;
            --oxd-primary-one-lighten-5-color:#ff8a37;
            --oxd-primary-one-lighten-30-color:#ffd4b6;
            --oxd-primary-one-darken-5-color:#ff6c03;
            --oxd-primary-one-alpha-10-color:rgba(255, 123, 29, 0.1);
            --oxd-primary-one-alpha-15-color:rgba(255, 123, 29, 0.15);
            --oxd-primary-one-alpha-20-color:rgba(255, 123, 29, 0.2);
            --oxd-primary-one-alpha-50-color:rgba(255, 123, 29, 0.5);
            --oxd-secondary-four-lighten-5-color:#84d225;
            --oxd-secondary-four-darken-5-color:#68a61d;
            --oxd-secondary-four-alpha-10-color:rgba(118, 188, 33, 0.1);
            --oxd-secondary-four-alpha-15-color:rgba(118, 188, 33, 0.15);
            --oxd-secondary-four-alpha-20-color:rgba(118, 188, 33, 0.2);
            --oxd-secondary-four-alpha-50-color:rgba(118, 188, 33, 0.5);
        }
  </style>
    <noscript>
        <strong>
            We're sorry but orangehrm doesn't work properly without JavaScript enabled. Please enable it to continue.
        </strong>
    </noscript>

    <div id="app">
    <auth-login
            **:error="{&quot;error&quot;:&quot;invalid_csrf_token&quot;,&quot;message&quot;:&quot;CSRF token validation failed&quot;}"**
            :token="&quot;e.ICuUjFISMfzfDxGRa_WQB5ZSr_ODMG6yF0y6BlqAfvU.EEf7_GJVcLCtOyLYGrv0MaYImaK1BTHFYg3RdDDJHKNDeqbmAlpcuolqVA&quot;"
            :login-logo-src="&quot;\/web\/images\/ohrm_logo.png&quot;"
            :login-banner-src="&quot;\/web\/images\/ohrm_branding.png?v=1695283103439&quot;"
            :show-social-media="true"
            :is-demo-mode="false"
        >
    <template v-slot:footer>
        <div class="orangehrm-copyright-wrapper">
            <oxd-text tag="p" class="orangehrm-copyright">OrangeHRM OS 5.5</oxd-text>
<oxd-text tag="p" class="orangehrm-copyright">&copy; 2005 - 2023 <a href="http://www.orangehrm.com" target="_blank">OrangeHRM, Inc</a>. All rights reserved.</oxd-text>
        </div>
    </template>
    </auth-login>
    </div>
    <script type="text/javascript">
        window.appGlobal = {
          baseUrl: "/web/index.php",
          publicPath: "/web",
        };
    </script>
    <script src="/web/dist/js/chunk-vendors.js?v=1695283103439"></script>
    <script src="/web/dist/js/app.js?v=1695283103439"></script>
</body>
</html>

**Comment by devishke-orange** [comment]
Hi @jstawow 

Thank your for interest in writing tests for OrangeHRM 5.5!

You will not be able to login directly. If you look at the relevant code in our cypress test, you can see that we have a separate plugin that we use for testing: https://github.com/orangehrm/orangehrm/blob/main/src/test/functional/cypress/support/commands.js#L38-L47

This plugin is located in `src/test/functional/tools/plugins/orangehrmFunctionalTestingPlugin`.

In order to setup for testing:

- Install the system fresh
- Run `prepare.php` (`src/test/functional/tools/prepare.php`)

This will copy the plugin to `src/plugins` and create a savepoint for the database. You can verify that it's working by running the cypress tests (README: https://github.com/orangehrm/orangehrm/blob/main/src/test/functional/Readme.md)
