### ISSUE TITLE
Please add silent install again (command line installer)

### ISSUE THREAD

**Issue by wim-vandijck-sp** [orangehrm/orangehrm#1772]
**Is your feature request related to a problem? Please describe.**
I want to be able to perform silent install.

**Describe the solution you'd like**
Allow a configuration file for the command line installer

**Describe alternatives you've considered**
n/a - this used to work in 5.3

**Comment by devishke-orange** [comment]
Hi @wim-vandijck-sp,

You can still use the old CLI installer.

`php installer/cli_install.php`. The old configuration file is also available at `cli_install_config.yaml`

Is this what you were referring to?
