### ISSUE TITLE
Need help on API document for my website

### ISSUE THREAD

**Issue by leductho911** [orangehrm/orangehrm#1774]
### OrangeHRM version

5.5

### Environment details

- OrangeHRM source: 5.5
- Platform: Web app
- PHP version:
- Database and version:
- Web server:
- Browser:

### Describe the bug

Hi, I install Orange HRM open source on mydomain.com and I notice that the API url is : mydomain.com/orange/web/index.php/api/v2/admin/users?limit=50&offset=0&sortField=u.userName&sortOrder=ASC

Is there any way I can get the API document (like swagger) for my my website?
I found this url but I think it's outdate https://orangehrm.github.io/orangehrm-api-doc/

Many thanks

**Comment by devishke-orange** [comment]
Hi Theo,

You can find our api documentation here: https://api-starter.orangehrm.com. You can change the Base URL field to your website and it will reflect throughout the whole documentation.

![Screenshot from 2023-11-27 07-59-27](https://github.com/orangehrm/orangehrm/assets/97493184/fd14ab31-e488-4ec7-9289-5cf3249c470d)

**Comment by leductho911** [comment]
> Hi Theo,
> 
> You can find our api documentation here: https://api-starter.orangehrm.com. You can change the Base URL field to your website and it will reflect throughout the whole documentation.
> 
> ![Screenshot from 2023-11-27 07-59-27](https://private-user-images.githubusercontent.com/97493184/285719079-fd14ab31-e488-4ec7-9289-5cf3249c470d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MjU0OTQsIm5iZiI6MTcwMTQyNTE5NCwicGF0aCI6Ii85NzQ5MzE4NC8yODU3MTkwNzktZmQxNGFiMzEtZTQ4OC00ZWM3LTkyODktNWNmMzI0OWM0NzBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDEwMDYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyOTk5Y2ZhMWQxMTIxOTEwOTc5MTc5OTc3NTBmZWY5YTA0MGUxNDczYjM3MmMzZmU4YjRjM2FiNWU0NTU5ZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fVKbQwcxGmWiiy1yEZqikcQEImMMkNuRhfYBDnTxnVI)

Thanks man
