### ISSUE TITLE
Invalid datetime format Error While adding Employee.

### ISSUE THREAD

**Issue by SmartiApps** [orangehrm/orangehrm#178]
I installed orange hrm in Ubuntu 16 and tried to add employee.

I got the following Error.
SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '2017-08-19 06:38:10am' for column 'created_date' at row 1

**Comment by kavithagurusamy** [comment]
Hi..
Which version of OrangeHRM have you tried out? Have you tried with the latest stable release?

**Comment by SmartiApps** [comment]
I'm using OrangeHRM 4.0 recently downloaded from https://excellmedia.dl.sourceforge.net/project/orangehrm/stable/4.0/orangehrm-4.0.zip

Please let me know if you need URL and credentials.

**Comment by lakshithaorange** [comment]
@SmartiApps What is the SQL version you are using ? please set SET GLOBAL sql_mode = ''; in SQL and check if it's working set that value from the config file ,

**Comment by kavithagurusamy** [comment]
Hi..

Are you using MySQL or Maria DB for this installation? I think you might be using mysql 5.6, If so can you please update the configuration as below. You could change this in my.cnf

* Global SQL mode should be empty
- SET GLOBAL sql_mode = '';

**Comment by SmartiApps** [comment]
We are using MYSQL server version 5.7.19- 0ubuntu0.16.04.1

**Comment by kavithagurusamy** [comment]
So you required to change the SQL mode, Can you change it and check whether its working.?

**Comment by xluffy** [comment]
The setting `[mysqld] sql-mode=""` you're disabling safe-mode. That isn't solution.

**Comment by cmlxmm** [comment]
Any progress on this issue? I can confirm reproduction of such problem on Ubuntu 16.04 with MySQL 5.6.39, nevertheless omitting sql-mode in my.cnf is working. Before I have had sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES.

**Comment by maruhgar** [comment]
The following fix based on [this stackoverflow answer](https://stackoverflow.com/a/42490167/254643) worked for me.

Change the line 63 in `orangehrm-4.0/symfony/plugins/orangehrmPimPlugin/lib/service/EmployeeEventService.php` from `$employeeEvent->setCreatedDate(date("Y-m-d h:i:sa"));` to 
`$employeeEvent->setCreatedDate(date("Y-m-d H:i:s"));`

Of course, I am unaware if there are side-effects elsewhere

**Comment by kavithagurusamy** [comment]
@xluffy @SmartiApps @maruhgar @cmlxmm Closing this issue..Please let me know if any of you are facing the issue in 4.1 release.
