### ISSUE TITLE
Database Error

### ISSUE THREAD

**Issue by sohailk784** [orangehrm/orangehrm#1785]
### OrangeHRM version

5.5

### Environment details

Database

### Describe the bug

I am getting below error while installing the OrangeHRM on my server. We tried to off the foreign key checks but still no luck.

An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1833 Cannot change column
  'id': used in a foreign key constraint 'ohrm_job_interview_ibfk_1' of table 'ohrm_job_int
  erview'

**Comment by devishke-orange** [comment]
Hi @sohailk784 

This is a known issue. Please see https://github.com/orangehrm/orangehrm/issues/1731#issuecomment-1727583099

**Comment by devishke-orange** [comment]
Hi @sohailk784,

This issue is fixed in OrangeHRM 5.6: https://github.com/orangehrm/orangehrm/releases/tag/v5.6

**Comment by devishke-orange** [comment]
I'm closing this since the issue was fixed.
