### ISSUE TITLE
employees schedule shift module

### ISSUE THREAD

**Issue by aymeen1** [orangehrm/orangehrm#1806]
Hello every one
I have successfully installed the OrangeRHM source code, but as a team leader I want to schedule shifts (morning, afternoon and night) for my team every month and ability to update. This module is not provided in the downloaded software as it is source software, can someone help me in adding this module

thank you in advance
Aymen

**Comment by ManulMax** [comment]
Hi @aymeen1 ,
Please go to Admin -> Job -> Work shift page and there you can add your related work shifts with working hours. And also you can assign those work shifts to the employees as well.

**Comment by aymeen1** [comment]
hi Manul
thank you for the assistance in fact I'm looking for a schedule model like the one in the photo below. M=Morning, A=Afternoon, N=Night, C=Leave
![schedule employees](https://github.com/orangehrm/orangehrm/assets/38131249/6e2c5869-3b05-4d8a-a843-146417d3b5a7)
