### ISSUE TITLE
n3 is not a function. (In 'n3()', 'n3' is an instance of Module)

### ISSUE THREAD

**Issue by marciano0695** [orangehrm/orangehrm#1808]
### OrangeHRM version

5.6

### Environment details

- OrangeHRM source: Git clone
- Platform: 23.2.0 Darwin Kernel (MAC)
- PHP version: 8.1
- Database and version: Mysql 8.2
- Web server:
- Browser: ALL

### Describe the bug

Fresh installation via git clone
After making command "yarn dev"
![Captura de ecrã 2024-02-14, às 13 02 46](https://github.com/orangehrm/orangehrm/assets/52575365/d92feda2-5528-4ee8-8fd6-88b57b72a018)

### Relevant log output

```shell
Don't have logs
```

**Comment by devishke-orange** [comment]
Hi @marciano0695,

Did you run `yarn install` and `yarn dev` in both `installer/client` and `src/client`?

**Comment by marciano0695** [comment]
> Hi @marciano0695,
> 
> Please let me know your node version. Does `yarn dev` compile successfully?

Hi @devishke-orange,
I do the ```yarn dev``` on ```src/client```, already try with ```v16.19.1```, ```v18.15.0```, ```v20.11.0``` and yes complie successfuly.

I think the error comes from ```@ohrm/oxd```

<img width="1301" alt="Captura de ecrã 2024-02-14, às 18 37 33" src="https://github.com/orangehrm/orangehrm/assets/52575365/6521e59f-52f2-4961-8ad9-710f46a39396">

**Comment by n3ndor** [comment]
Hey, I have the same problem! I can successfully run the following commands:

`yarn install `
`yarn build`
`yarn dev`

But in the browser, I see the uncaught TypeError as @marciano0695 posted.

Running yarn build returns `o is not a function`, and running yarn dev returns `n3 is not a function`.

I can't believe that you didn't share the solution after enduring such a long struggle.

**Comment by mpark4656** [comment]
Having the same problem here; exactly same error message in the browser console.

**Comment by marciano0695** [comment]
@n3ndor @smriad @mpark4656 Yes i get it solved.

Node version: ```v16.20.2```
Remove ```node_modules``` e ```package.lock``` (if you have it)

Do not run ```npm install``` instead run ```yarn install``` with the following yarn.lock:
[yarn.lock.zip](https://github.com/orangehrm/orangehrm/files/15264124/yarn.lock.zip)

After that you can run yarn dev or build

I didn't test with another versions of node.

**Comment by n3ndor** [comment]
hey @marciano0695 !
Thanks, your solution worked for me too.

**Comment by smriad** [comment]
> @n3ndor @smriad @mpark4656 Yes i get it solved.
> 
> Node version: `v16.20.2` Remove `node_modules` e `package.lock` (if you have it)
> 
> Do not run `npm install` instead run `yarn install` with the following yarn.lock: [yarn.lock.zip](https://github.com/orangehrm/orangehrm/files/15264124/yarn.lock.zip)
> 
> After that you can run yarn dev or build
> 
> I didn't test with another versions of node.

Thanks @marciano0695 . Worked for node version: v20.12.2

**Comment by EibarReneOrtizRey** [comment]
also worked for me, had me all day with headaches, this does not work with node version 22.x, i used the version @smriad mentioned and worked perfectly fine, thank so much @marciano0695

**Comment by jhonfrancisduarte** [comment]
Very helpful. Thanks a lot.🥰

**Comment by badfelon** [comment]
@marciano0695 do not have such a package in my node modules (Remove node_modules e package.lock (if you have it)) but still getting error ERROR TypeError: n3.title is not a function .
