### ISSUE TITLE
Please help me to logs from orangehrm php

### ISSUE THREAD

**Issue by vvsreerag** [orangehrm/orangehrm#1814]
### OrangeHRM version

5.5

### Environment details

- OrangeHRM source:
- Platform:
- PHP version: 8.2
- Database and version:
- Web server:
- Browser:

### Describe the bug

I would like to get logs from php code to know whats the value in a variable im using lampp to run orangehrm how to do get logs so that i can try to develop something ??

**Comment by ManulMax** [comment]
Hi @vvsreerag you can find logs at` /src/log`. For installer related issues you can find installer.log file and for product development issues youcan find orangehrm.log there.

**Comment by devishke-orange** [comment]
Hi we have added this as an FAQ: https://starterhelp.orangehrm.com/hc/en-us/articles/13089379665436-Where-are-my-log-files

I'll close this issue.
