### ISSUE TITLE
HTTP ERROR 500 when trying to login on demo website

### ISSUE THREAD

**Issue by Sanketr123** [orangehrm/orangehrm#1816]
### OrangeHRM version

5.1

### Environment details

- OrangeHRM source:
- Platform:
- PHP version:
- Database and version:
- Web server:
- Browser:

### Describe the bug

The user is getting an HTTP ERROR 500 error on the demo website
This the the link I have used : https://opensource-demo.orangehrmlive.com/web/index.php/auth/login

### To reproduce

Open Chrome browser
Enter url - https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
Observe the error

### Expected behavior

The user should be able to log in demo website

**Comment by henriquemanieri** [comment]
Same here.
Since Saturday 02/24

**Comment by devishke-orange** [comment]
Hi @Sanketr123, @henriquemanieri 

The demo site is back up.
