### ISSUE TITLE
Admin cannot edit their own job details in the My Info section

### ISSUE THREAD

**Issue by NickNck** [orangehrm/orangehrm#1831]
### OrangeHRM version

5.6

### Environment details

- OrangeHRM source: 5.6
- Platform: Windows 10
- PHP version: 8.1
- Database and version: MariaDB 10.1
- Web server: WAMP
- Browser: Chrome

### Describe the bug

Administrators cannot edit their own job info which i find strange, because admins can edit other admin users job details but not their own.

### To reproduce

Create admin user, try to edit your own job info in the My Info section but you'll see that everything is greyed, however, you can edit another admins job details.

### Expected behavior

Any admin should be able to edit all users job details, include the admins own job details and not need another admin to do that.

**Comment by devishke-orange** [comment]
Hi @NickNck,

This is not a bug. This behaviour is intentional. If you need to edit an employee associated with an admin account, you can do so via a separate administrator account (that is associated with a different employee).
