### ISSUE TITLE
Invalid URL oRangeHRM Mobile App

### ISSUE THREAD

**Issue by smvha-owner** [orangehrm/orangehrm#1833]
### OrangeHRM version

5.6

### Environment details

- OrangeHRM source: SourceForge
- Platform: cPanel Linux (Apache)
- PHP version: 8.1
- Database and version: 0.5.24-MariaDB-cll-lve
- Web server: Apache
- Browser: Chrome/Safari/Edge

### Describe the bug

Getting Invalid URL when trying to set-up the oRangeHRM Mobile App. I am entering the correct URL (https://hr.mydomain.com). I have enabled the Mobile Module in the Admin Configuration (although the module settings itself is not visible in the dashboard.

**Comment by ManulMax** [comment]
Hi @smvha-owner can you send the URL you added to mobile app, the URL you given (https://hr.mydomain.com/) seems not working.And Make sure to remove the ending '/' 

Also you can tryout mobile application by adding our demo URL - [https://opensource-demo.orangehrmlive.com/web/index.php](url)

**Comment by smvha-owner** [comment]
@ManulMax  URL is https://hr.smvha.com .. I did try it both with and without ending "/" but both gives the same error "Invalid URL"

**Comment by devishke-orange** [comment]
Hi @smvha-owner,

I think you are trying to use the "OrangeHRM Advanced" application. Please ensure you are using "OrangeHRM Open Source". You can click the icons below.

<a href="https://play.google.com/store/apps/details?id=com.orangehrm.opensource" target="_blank">
<img height="54" alt='Get it on Google Play'
    src='https://raw.githubusercontent.com/wiki/orangehrm/orangehrm/mobile/play_store_cropped_en_US_2022_08_04.png'/>
</a>
<a href="https://apps.apple.com/us/app/orangehrm/id1527247547" target="_blank">
<img height="54" alt='Download on the App Store'
    src='https://raw.githubusercontent.com/wiki/orangehrm/orangehrm/mobile/app_store_en_US.svg'/>
</a>

Also, love how you've customized the login page. Looks great.

**Comment by devishke-orange** [comment]
I'll close this issue since it seems the wrong app was being used.
