### ISSUE TITLE
Logout -> Back button -> Visible Previous Session Details

### ISSUE THREAD

**Issue by Abhinavram** [orangehrm/orangehrm#184]
After logging out as admin in the index.php/pim/viewEmployeeList page, I pressed back button (in the browser) and it redirected me to the below page,
![orangehrm](https://user-images.githubusercontent.com/15023872/31050104-0c4ee4fc-a607-11e7-82c6-e019bfe232f2.JPG)

In the above page, it surprisingly displayed all the details.
This might eventually be a big privacy risk to user details.

**Comment by kavithagurusamy** [comment]
@Abhinavram Are you accessing to OrangeHRM Demo instance or your production instance?

Please check whether you see the issue in your production instance?
