### ISSUE TITLE
Employee list internal error and other bugs in 4.0

### ISSUE THREAD

**Issue by slim-benhammouda** [orangehrm/orangehrm#185]
Hi,
I installed 4.0 stable version downloaded from https://sourceforge.net/projects/orangehrm/files/stable/4.0/orangehrm-4.0.zip/download
on:
- ubuntu 16.04,
- mySql 5.7.19
- php 7.0.22 (I also test it with php 7.1)

but I'm facing some issue:
- In Admin dashboard, "Pending Leave Requests" widget is displaying an internal error
- after adding a employee, employee list can't be displayed, I'm keeping receiving internal error
- trying to add leaving entitlement to multiple users but the confirmation dialog keep loading!!!

I also tried to install orange hrm from git but installation always fails (tested with branches master, 4.0 and 4.0.1)!!! any steps to follow to install from git?

Many thanks,
Slim

**Comment by ankitchauhan22** [comment]
I had same issue. It's not related to OrangeHRM. 

`SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));`

execute above query in mysql console. This will fix the issue.

Regards
Ankit

**Comment by kavithagurusamy** [comment]
Changing SQL mode will resolve the issue.
