### ISSUE TITLE
Speed up installer process

### ISSUE THREAD

**Issue by kale1d0code** [orangehrm/orangehrm#1856]
**Is your feature request related to a problem? Please describe.**
Installing OrangeHRM from the web installer is cumbersome with required fields, various screens, no defaults, and strict controls on admin user password.

**Describe the solution you'd like**
command line installer or environment variables / secrets.
allow for admin password controls to be configurable at startup (requiring all the different character types etc)

**Describe alternatives you've considered**

**Comment by kale1d0code** [comment]
![Screenshot from 2024-06-18 14-35-24](https://github.com/orangehrm/orangehrm/assets/13876156/5c79adf9-1216-499b-b910-d723887a4858)
Screenshot of Password control screen which shouldn't appear

**Comment by kale1d0code** [comment]
The information on the following page was helpful for getting around the issue with password controls:
https://github.com/orangehrm/orangehrm/issues/1686
sql needs to be executed before attempting to signin

**Comment by devishke-orange** [comment]
Hi @kale1d0code 

Glad you found a solution for the password policy. Please check this article for information on our CLI installer: https://starterhelp.orangehrm.com/hc/en-us/articles/13087529184540-How-can-I-install-upgrade-OrangeHRM-if-I-m-facing-issues-with-the-web-installer-upgrader

**Comment by kale1d0code** [comment]
First specify inputs for the install command:
```
install_inputs=$(cat <<EOF
yes
dbms

db
root
secret

dbuser
dbpassword
no
Orange Development
united kingdom
en_US
Europe
Europe/London
John
Doe
dev@example.com

admin
Password1!
Password1!
no

EOF
)
```
and then install
```
echo -e "$install_inputs" | docker exec -i docker-orange-1 php /var/www/html/installer/console install:on-new-database 2>&1
```

and then

```
docker exec docker-dbms-1 mysql -u root -p'secret' db -e 'UPDATE `hs_hr_config` SET `value` = "off" WHERE `name` = "auth.password_policy.enforce_password_strength"'
```

however I would warn anyone using the installer. it does not support arguments so you need to pipe the inputs into the command like how I have, if the order of the inputs change you will need to rewrite the install_inputs heredoc
