### ISSUE TITLE
Where can I change the forgot password email subject and sender name?

### ISSUE THREAD

**Issue by 75healthAdm** [orangehrm/orangehrm#1858]
### OrangeHRM version

5.6.1

### Environment details

- OrangeHRM source: 5.6.1
- Platform: Apache
- PHP version: 8
- Database and version: MySQL 8.0.37
- Web server: Apache
- Browser: NA

### Describe the bug

How can I change the subject line and the sender name in Forgot Password Email?

**Comment by 75healthAdm** [comment]
I have got it.

**Comment by gictm** [comment]
@75healthAdm, could you let me know where you were able to make these changes?
