### ISSUE TITLE
cannot run dump-autoload composer not found

### ISSUE THREAD

**Issue by kale1d0code** [orangehrm/orangehrm#1865]
### OrangeHRM version

5.6.1

### Environment details

- OrangeHRM source: Dockerhub
- Platform: Docker
- PHP version: PHP 8.3.4 (cli)
- Database and version: Mariadb 10.9.4
- Web server: apache?
- Browser: Version 126.0.6478.61 (Official Build) (64-bit)

### Describe the bug

docker container does not provide composer
it is not possible to run dump-autoload with the container as it is.

### To reproduce

run composer dump-autoload within /var/www/html/src

### Expected behavior

composer to generate a new autoload file

### Relevant log output

```shell
bash: composer: command not found
```

**Comment by RajithaKumara** [comment]
Hi @kale1d0code ,
Thanks for your contribution. But we can't add composer to our production docker image, as we have separate environment for development https://github.com/orangehrm/orangehrm-os-dev-environment. If you want you can use it.
