### ISSUE TITLE
What happened to the dutch language?

### ISSUE THREAD

**Issue by remkoseelig** [orangehrm/orangehrm#195]
According to OrangeHRM website, and the application itself, Dutch language should be supported but nothing happens when changing it. Appears that the nl_NL.xml language file is not there.

Curious if it ever existed and what happened to it?

**Comment by samanthajayasinghe** [comment]
@remkoseelig It seems that we don't have Dutch language pack since there is no language expert contributor. 
Are you willing to contribute for nl_NL language pack?

**Comment by kavithagurusamy** [comment]
Its made available in OrangeHRM 4.1.2 release
