### ISSUE TITLE
Why I can not add a "night shift" for work shifts?

### ISSUE THREAD

**Issue by baijianpeng** [orangehrm/orangehrm#196]
I am working in a hospital. I want to add a shift for "night shift", which will start from 19:00 and end at 09:00 of the NEXT day.

However, when I fill in the 19:00 and 9:00 respectively for the time in "Work Hours" option, I got warning message:

[quote]From time should be less than To time[/quote]

But, our "night shift" is REALLY ended in the next day, because we are working in a hospital, there are always someone on duty in EACH HOUR. Why this software does NOT allow this?

Please improve this feature.

**Comment by samanthajayasinghe** [comment]
@baijianpeng Night shift is not a common scenario for most of the employers that's why it's not supported in OS version but it's available in the enterprise version. please contact orangehrm.com support for more information.

**Comment by baijianpeng** [comment]
understand now. Thank you.
