### ISSUE TITLE
Is it possible to adjust the sequence  of First Name / Last Name ?

### ISSUE THREAD

**Issue by baijianpeng** [orangehrm/orangehrm#197]
In our Chinese language, when writing/showing the name of a person, we always put the Last Name first then his/her first name.  So I hope I can also do this in OrangeHRM. And, we don't have "middle name" at all.

However, I did not see any option to adjust the sequence  of First Name / Last Name, neither do I see any option to remove/hide the "middle name".

How can I adjust the sequence  of First Name / Last Name? How can I remove the "middle name" ?

Thank you.

**Comment by kavithagurusamy** [comment]
@baijianpeng You need to customise the code to get this done. Please forward your request to sales@orangehrm.com

**Comment by jaleelpoonath** [comment]
Table: ohrm_display_field interchange first_name last_name values
