### ISSUE TITLE
Can't access REST API

### ISSUE THREAD

**Issue by na7r1x** [orangehrm/orangehrm#200]
Managed to successfully spin up a local instance, but it is not clear how to access the REST API.

I tried to GET localhost/orangehrm-4.0/symfony/web/index.php/api/v1/user and got response 401 Unauthorised and body '[ ]'

The API documentation does not say how to authenticate against the API. I also tried the /api/v1/login?username={myadminusername}&password={myadminpassword} and got the same response. 

Am I missing something obvious - if so, could you point me in the right direction (and maybe update your docs)? Or is this an issue with the current version?

**Comment by samanthajayasinghe** [comment]
@na7r1x It's better to access API via rest-client. please have a look how it integrated  
https://github.com/orangehrm/api-client-php

and this is how it's implemented it in the sample app
https://github.com/orangehrm/api-sample-app-php

**Comment by na7r1x** [comment]
@samanthajayasinghe I did have a look at the resources you mentioned before I asked the question. However, the application I'm trying to integrate OrangeHRM with is based on IBM Integration Bus, so that kinda takes your rest-client and PHP out of the picture. I wanted to find out how I can use the API without it - especially how to authenticate with just parameters/headers, as this is not documented in your API specification document. Do I need to setup an OAuth entry point? How do I pass the ID and secret - parameter/header? What's the parameter/header? None of those questions are answered in your documentation. Please, clarify - thank you!

**Comment by na7r1x** [comment]
Nevermind, figured it out. Had to dig through the code, though. 

If anyone's looking for an answer to what's going on:
- it's a Bearer token authentication
- before you can use the API you need to create an OAuth client from the OrangeHRM web UI in `Admin > Configuration > Register OAuth Client` by giving it secure id and secret/password.
- In order to authenticate, a POST request is fired to `{your-host}/index.php/oauth/issueToken` (in my case http://127.0.0.1/orangehrm-4.0/symfony/web/index.php/oauth/issueToken)
- the request takes parameters client_id, client_secret, grant_type , where 

client_id = [the oauth ID you've created];
client_secret = [the oauth secret you've created];
grant_type = 'client_credentials'

- the response looks like `{"access_token":"ecdc9f1c565ce501f25c7b9a1b17d4d254d35f50","expires_in":3600,"token_type":"bearer","scope":null}`

- now you can call the API with an Authorisation header: {[token_type] [access_token]} (e.g. `Authorisation: "Bearer ecdc9f1c565ce501f25c7b9a1b17d4d254d35f50"` at `http://{your-host}/api/v1/*`

@samanthajayasinghe feel free to (adapt and) use the above in the README.md/documentation

**Comment by samanthajayasinghe** [comment]
@na7r1x 
Thank you very much. I'll update the readme file and API docs.

**Comment by danielbair** [comment]
> Nevermind, figured it out. Had to dig through the code, though.
> 
> If anyone's looking for an answer to what's going on:
> 
>     * it's a Bearer token authentication
> 
>     * before you can use the API you need to create an OAuth client from the OrangeHRM web UI in `Admin > Configuration > Register OAuth Client` by giving it secure id and secret/password.
> 
>     * In order to authenticate, a POST request is fired to `{your-host}/index.php/oauth/issueToken` (in my case http://127.0.0.1/orangehrm-4.0/symfony/web/index.php/oauth/issueToken)
> 
>     * the request takes parameters client_id, client_secret, grant_type , where
> 
> 
> client_id = [the oauth ID you've created];
> client_secret = [the oauth secret you've created];
> grant_type = 'client_credentials'
> 
>     * the response looks like `{"access_token":"ecdc9f1c565ce501f25c7b9a1b17d4d254d35f50","expires_in":3600,"token_type":"bearer","scope":null}`
> 
>     * now you can call the API with an Authorisation header: {[token_type] [access_token]} (e.g. `Authorization: "Bearer ecdc9f1c565ce501f25c7b9a1b17d4d254d35f50"` at `http://{your-host}/api/v1/*`
> 
> 
> @samanthajayasinghe feel free to (adapt and) use the above in the README.md/documentation

I can get the token just fine, but any attempt to access the api just results in a 401 unauthorized. 
What is the link to the api documentation for OrangeHRM OS v4.1.2.1 please?

I have this problem even with the php sample app.

**Comment by kavithagurusamy** [comment]
API documentation is tracked in 
https://orangehrm.github.io/orangehrm-api-doc/

**Comment by kleinker** [comment]
the Baerer Token works fine regarding e.g. search employee

GET /orangehrm-4.3/symfony/web/index.php/api/v1/employee/search HTTP/1.1
Host: 192.168.145.21
Authorization: Bearer c8539acf81e97006fcb33d8f4e255c314630c2d2
cache-control: no-cache
Postman-Token: e976e33d-826a-41a5-bcde-f0044c8527f2

### but I struggle in creating a new emplyoee
isn't it: https://orangehrm.github.io/orangehrm-api-doc/#api-Employee-saveEmployee

**Comment by samanthajayasinghe** [comment]
@kleinker , Seems you make a PUT request rather than a POST request. 
Can you make a POST request to add the employee and PUT request to update the employee?

**Comment by marcus-davies** [comment]
I have a similar issue to the above in that when I call the following IP with a bearer token it returns 
GET https://35.230.111.111/api/v1/user
Content-Type=application/json
Bearer a22ccba16d7e7ea4c43d8548390937841f798108

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
    <head>
        <title>404 Not Found</title>
    </head>
    <body>
        <h1>Not Found</h1>
        <p>The requested URL /api/v1/user was not found on this server.</p>
    </body>
</html>

```
I have tried other flavours of the URL to see if it would help but no success
```
GET https://35.230.111.111/api/v1/users
GET https://35.230.111.111/api/v1/users
GET https://35.230.137.124/symfony/web/index.php/api/v1/users
```
None of the above work all failing with a 404 error

I tried running the curl command which shows the certificates have not been setup.  Could this be why it is failing?

```
curl -X GET \
  https://35.230.111.111/api/v1/user \
  -H 'Authorization: Bearer a22ccba16d7e7ea4c43d8548390937841f798108' \
  -H 'Content-Type: application/json' 
curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
HTTPS-proxy has similar options --proxy-cacert and --proxy-insecure.
```

**Comment by myardyas** [comment]
@marcus-davies Morning!
Did you try:
GET https://35.230.111.111/symfony/web/index.php/api/v1/user
i.e. w/o 's' in the end

**Comment by marcus-davies** [comment]
Yes. I did try user (singular) as well as users.
Postman says its failing with a "401 Unauthorized"
However I am using the Authorization header with a newly generated bearer token.
I have also tried sending in the username and password as parameters but to no avail

```
curl -X GET \
  'https://35.230.111.111/symfony/web/index.php/api/v1/user?username=user&password=uDeT4CU9dUq7' \
  -H 'Authorization: Bearer f1bbb3f827b66242c4637f444f2a08525642b011' \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: 94e5ecc5-0b3f-49d0-b813-f7120bd88b36' \
  -H 'cache-control: no-cache' \
  -d undefined=```

**Comment by o-hreshchuk** [comment]
Could someone please help with that? I also have the same issue as @marcus-davies

**Comment by SamirAdel** [comment]
> Thanks for your help Myardyas
> 
> Yes. I did try user (singular) as well as users.
> Postman says its failing with a "401 Unauthorized"
> However I am using the Authorization header with a newly generated bearer token.
> I have also tried sending in the username and password as parameters but to no avail
> 
> ```
> curl -X GET \
>   'https://35.230.111.111/symfony/web/index.php/api/v1/user?username=user&password=uDeT4CU9dUq7' \
>   -H 'Authorization: Bearer f1bbb3f827b66242c4637f444f2a08525642b011' \
>   -H 'Content-Type: application/json' \
>   -H 'Postman-Token: 94e5ecc5-0b3f-49d0-b813-f7120bd88b36' \
>   -H 'cache-control: no-cache' \
>   -d undefined=
> ```
> 
> FYI: The API to get the token works fine but then I cant do anything with it. Here is the call to get the token
> 
> ```
> curl -X POST \
>   https://35.230.111.111/symfony/web/index.php/oauth/issueToken \
>   -H 'Content-Type: application/x-www-form-urlencoded' \
>   -H 'Postman-Token: 5f022920-bab2-4c06-91c6-db7bac6360e6' \
>   -H 'cache-control: no-cache' \
>   -d 'grant_type=client_credentials&client_id=MyClientID&client_secret=APIKeyXXX&undefined='```
> 
> Any ideas what could be wrong?
> ```

After calling the https://{YOUR-DOMAIN}/symfony/web/index.php/oauth/issueToken?grant_type=client_credentials&client_id={Your client id}&client_secret={Your client secret} .. you will receive 
{
    "access_token": "721ff.....................",
    "expires_in": 3600,
    "token_type": "bearer",
    "scope": null
} 

you should call any APIand add use "access_token" parameter in the query string instead of adding the "Authenticate" in the headers. Example: /api/v1/user?access_token=721ff.....................

I have been struggling with this for 2 days and finally found the solution by using the access_token in the query string

**Comment by RajithaKumara** [comment]
Hi @SamirAdel 
Please find authentication steps [here](https://github.com/orangehrm/orangehrm/wiki/REST-API), it's same as @na7r1x [comment](https://github.com/orangehrm/orangehrm/issues/200#issuecomment-378215737).

E.g. Start authentication as below. Postman also fine. Use below curl request or import it to Postman and setup `{{host}}`, `{{client_id}}`, `{{client_secret}}`. Note:  `{{client_id}}` and `{{client_secret}}` should be in OrangeHRM `OAuth Client`.
```console
curl -X POST 'https://{{host}}/symfony/web/index.php/oauth/issueToken' \
-H 'Content-Type: application/json' \
-d '{
    "grant_type":"client_credentials",
    "client_id":"{{client_id}}",
    "client_secret":"{{client_secret}}"
}'
```
And you could get below response;
```json
{
    "access_token": "{{auth_token}}",
    "expires_in": 3600,
    "token_type": "bearer",
    "scope": null
}
```
When testing copy `{{auth_token}}` and use it for below request.

```console
curl -X GET \
  'https://{{host}}/symfony/web/index.php/api/v1/user' \
  -H 'Authorization: Bearer {{auth_token}}' \
  -H 'Content-Type: application/json'
```
Response will be like this.
```json
{
    "data": [
        {
            "userName": "Admin",
            "userRole": "Admin",
            "status": "Enabled",
            "employeeName": "first last",
            "employeeId": "1"
        }
    ],
    "rels": []
}
```

**Comment by ArhamKhan321** [comment]
I am accessing login Api but it does not getting my credentials (Sending response Null) I am following the steps as given in Api documentation.
I am using OrangeHrm 4.7

**Comment by RajithaKumara** [comment]
Hi @ArhamKhan321 
Can you provide more info about the endpoint that you used or an example cURL/Postman request?
Did you successfully get access token as documented in https://github.com/orangehrm/orangehrm/wiki/REST-API.

**Comment by ArhamKhan321** [comment]
Thanks for your response I have already resolved that issue, I just changed the function of Postparams to getQuerryParams and it worked for me.

**Comment by RajithaKumara** [comment]
Is that bug of OrangeHRM? Can you provide a patch if that is a bug :relaxed:

**Comment by Winniepoom** [comment]
> 

It not working for me, I copy CURL and import to POSTMAN and I get 404 error  any idea to solve it ?
![image](https://github.com/orangehrm/orangehrm/assets/107398226/9b6cd29c-db9f-4a4c-b809-9ba12f506290)

**Comment by Winniepoom** [comment]
> Hi @SamirAdel Please find authentication steps [here](https://github.com/orangehrm/orangehrm/wiki/REST-API), it's same as @na7r1x [comment](https://github.com/orangehrm/orangehrm/issues/200#issuecomment-378215737).
> 
> E.g. Start authentication as below. Postman also fine. Use below curl request or import it to Postman and setup `{{host}}`, `{{client_id}}`, `{{client_secret}}`. Note: `{{client_id}}` and `{{client_secret}}` should be in OrangeHRM `OAuth Client`.
> 
> ```
> curl -X POST 'https://{{host}}/symfony/web/index.php/oauth/issueToken' \
> -H 'Content-Type: application/json' \
> -d '{
>     "grant_type":"client_credentials",
>     "client_id":"{{client_id}}",
>     "client_secret":"{{client_secret}}"
> }'
> ```
> 
> And you could get below response;
> 
> ```json
> {
>     "access_token": "{{auth_token}}",
>     "expires_in": 3600,
>     "token_type": "bearer",
>     "scope": null
> }
> ```
> 
> When testing copy `{{auth_token}}` and use it for below request.
> 
> ```
> curl -X GET \
>   'https://{{host}}/symfony/web/index.php/api/v1/user' \
>   -H 'Authorization: Bearer {{auth_token}}' \
>   -H 'Content-Type: application/json'
> ```
> 
> Response will be like this.
> 
> ```json
> {
>     "data": [
>         {
>             "userName": "Admin",
>             "userRole": "Admin",
>             "status": "Enabled",
>             "employeeName": "first last",
>             "employeeId": "1"
>         }
>     ],
>     "rels": []
> }
> ```

> 

It not working for me, I copy CURL and import to POSTMAN and I get 404 error  any idea to solve it ?
![image](https://github.com/orangehrm/orangehrm/assets/107398226/9b6cd29c-db9f-4a4c-b809-9ba12f506290)
