### ISSUE TITLE
Module 'core' is not enabled Module 'dashboard' is not enabled

### ISSUE THREAD

**Issue by Awais-cb** [orangehrm/orangehrm#201]
Hi

I am facing fatal errors while installing orangehrm when i checked orangehrm log file it says 

- module 'core' is not enabled

when i mute this exception and try to login it say 

- module 'dashboard' is not enabled 
any solution to this would be really appreciated thanks.

**Comment by samanthajayasinghe** [comment]
@Awais-cb 
How you install the orangehrm? via git clone or SourceForge download?

**Comment by kavithagurusamy** [comment]
@Awais-cb Are you still facing the issue? Can you please share the steps that you followed to install the system?

**Comment by kavithagurusamy** [comment]
@Awais-cb I am closing this issue, let me know if you still face the issue to reopen it.
