### ISSUE TITLE
How to give access to employee

### ISSUE THREAD

**Issue by paiyasaravanan** [orangehrm/orangehrm#204]
Hi,

I have download Orange HRM from Sourceget.com and Installed into My PC.

I want create user ( employee ) and give the access to him.

i can find options for user creation.

after create user how they access the orange HRM. What is the access URL?

Please guide me . thanks

**Comment by kavithagurusamy** [comment]
Hi Paiyasaravanan

You have to host it with public domain and share the credentials with users. Please check with your system admin on how to host it.
