### ISSUE TITLE
Database connection problem

### ISSUE THREAD

**Issue by Jetranger** [orangehrm/orangehrm#221]
Hi, eveyone, I have a question when I install orangehrm.
![default](https://user-images.githubusercontent.com/15374658/40659315-820552d0-6380-11e8-9b5d-919334df553d.png)
![default](https://user-images.githubusercontent.com/15374658/40659336-8adaa6c6-6380-11e8-83ff-355a61b43d3c.png)
![default](https://user-images.githubusercontent.com/15374658/40659352-96d831fa-6380-11e8-95ee-9d1f50dc0981.png)

I need help. thanks.

**Comment by samanthajayasinghe** [comment]
@Jetranger , is orangehrm db-user has DB creation privileged?

**Comment by Jetranger** [comment]
My DB is MariaDB, does it cause this problem?

**Comment by kavithagurusamy** [comment]
@Jetranger What version of OrangeHRM you are installing? OrangeHRM 4.0 & 4.1 is supported with MariaDB.
Is your database connection is up and running? Can you please login to the database and try to create a test database ? This will give a confirmation on your server is up and running.

**Comment by Jetranger** [comment]
@kavithagurusamy OrangeHRM 4.1.
![default](https://user-images.githubusercontent.com/15374658/40785265-9fc19946-651a-11e8-8038-75686add3b68.png)
![default](https://user-images.githubusercontent.com/15374658/40785278-ac9cbd94-651a-11e8-9967-f684120bc3fa.png)

**Comment by Jetranger** [comment]
I'm waiting.

**Comment by sanik90** [comment]
yes, stumbled upon same issue, I've created new user and db, grant priviledge and still get the same error

**Comment by jlevy-wishfarms** [comment]
Same problem here, been trying for two days to get this installed

**Comment by jlevy-wishfarms** [comment]
If it is any help, I get the following error in my Apache logs when the installer errors out:

_[Mon Jun 11 14:24:38.397687 2018] [access_compat:error] [pid 19371] [client 172.109.139.122:41853] AH01797: client denied by server configuration: /var/www/html/orangehrm/installer/images/dummy.jpg, referer: http://orangehrm.wishfarms.com/installer/installerUI.php_

The following is the Directory section of my Apache vhost config:

     <Directory /var/www/html/orangehrm/>
        Options +FollowSymlinks
        AllowOverride All
        Require all granted
	
     </Directory>

**Comment by MadhukaHarith92** [comment]
Hi, can you create a test.php file in symfony/web like follows and run that php file. This will verify whether there is a problem in your database connectivity.
<?php

// Create connection
$conn = new mysqli($servername, $username, $password,$database,$port);
// Check connection
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
} 

// Create database
$sql = "CREATE DATABASE myDB";
if ($conn->query($sql) === TRUE) {
    echo "Database created successfully";
} else {
    echo "Error creating database: " . $conn->error;
}

$conn->close();
?>

**Comment by Jetranger** [comment]
![default](https://user-images.githubusercontent.com/15374658/41448826-bf98360a-708f-11e8-8cda-495f91768c6e.png)

**Comment by darshana-danrox** [comment]
same issue here does  any one offer help ??

**Comment by yuvarajsridhar** [comment]
i'm also facing same problem. i guess root cause is PHP version 7.2.x which is depreciated mysqli and it is working fine in PHP5.6.

**Comment by darshana-danrox** [comment]
issue resolved .contact me here  for help 1031danrox@gmail.com

https://www.fiverr.com/danrox

**Comment by Jetranger** [comment]
@yuvarajsridhar Neither php5 nor 7 can work.

**Comment by darshana-danrox** [comment]
found the issue and resolve it . @yuvarajsridhar  its not with the php  
Hint : mysql db configurations

**Comment by jlevy-wishfarms** [comment]
@darshana-danrox Could you please give more details?

**Comment by darshana-danrox** [comment]
I implement  latest orange hrm in  debian 9 stretch (raspberry pi )and ran in to multiple issues with databases .I use MariaDB  

@Jetranger your db issue can be resolve by using local host ip number 127.0.0.1 , 
also use create database and user with password  and give full privileges to that database 

@jlevy-wishfarms  Please provide more info . you can find errors here symfony/log

hope orange hrm support guys reproduce this and resolve

**Comment by Jetranger** [comment]
@darshana-danrox I have tried to all posiable you offer. but it have same error here.

**Comment by darshana-danrox** [comment]
check your db configurations . 
also provide log /OS/details to further assistance  

ping me here if you need help
 1031danrox@gmail.com

**Comment by sanik90** [comment]
I did granted full priviledge to root user.
Create new user and new DB using root credential also not working, I've tried using existing DB (which in my case I created it manually via command) also give error in process.
Funny thing that if the root user has no priviledge, how did I found the mysql user "orangehrm" was created (I checked from mysql.user table).

**Comment by kavithagurusamy** [comment]
@Jetranger OrangeHRM 4.1 version is supported with PHP 5.6, PHP 7.0 and PHP 7.1 as the compatible environment.
PHP 7.2 support will be available on this month release (will be available to the community in the first week of July). Have you tried to install in PHP 7.1 and still getting the same issue?

**Comment by jlevy-wishfarms** [comment]
Can confirm that changing 'localhost' to '127.0.0.1' in database config installation page does allow it to finish, PHP version is 7.1

**Comment by darshana-danrox** [comment]
it's sad that They couldn't find a solution to the  their own application  and when People offer solution they delete it .

**Comment by samanthajayasinghe** [comment]
@darshana-danrox This is an open source product where everyone can contribute to the success of the product. 
If you know the solution you can make a pull-request as other contributors do.

**Comment by a1friend** [comment]
@darshana-danrox I had the same problem on php 5.6 but when I changed 'localhost' to '127.0.0.1' with existing database option, installation went successfully.

**Comment by Jetranger** [comment]
It is worked when I type 127.0.0.1. but I have a new problem.
![default](https://user-images.githubusercontent.com/15374658/42121125-41becfc8-7c5b-11e8-8216-f421e50ecd43.png)

**Comment by Xorserd** [comment]
Jetranger, what version of Orangehrm are you using?

**Comment by baig772** [comment]
why is this closed? is it solved? i am facing same issue

**Comment by PetelsonLuis** [comment]
Hello.
I have the same issue.

**Comment by PetelsonLuis** [comment]
I Solved My Problem.
But my english is no very good.

**Comment by hermawan-fsi** [comment]
i have got same problem and looking for it.. still no luck..
forum is dead.. 
how about i will own forum for orange and will be sharing for  every one.. cause i have made some modification too.. maybe other person need.

**Comment by hermawan-fsi** [comment]
where is it in apache or in somewhere else

**Comment by baig772** [comment]
> where is it in apache or in somewhere else

While installing, it asks for DB info. I changed it there

**Comment by hermawan-fsi** [comment]
ok thanks... i wish not deleted by orange..

**Comment by samanthajayasinghe** [comment]
Hi @hermawan-fsi , 

As we noted, changing mysql host 'localhost' to '127.0.0.1'  solve the issue. We assume that it's an issue with your local mysql server can't connect via 'localhost' but via '127.0.0.1'. Anyone can change local my.cnf file and grant access via 'localhost' rather than the IP then it solves the issue. 
If you feel that it's an issue with Orangehrm code base then feel free to make a pull request with unit tests.

Thank you.

**Comment by hermawan-fsi** [comment]
thanks for all.., i am just wonder why the orange forum still 404..
