### ISSUE TITLE
Annoying to use, lots of bugs

### ISSUE THREAD

**Issue by SaphiLC** [orangehrm/orangehrm#247]
From sessions not saving, and when i try to relog it gives a csrf token error so i have to remove from the url the super long route you created for a login.... Sometimes, like 90% of the time, i get an error punching in or out, just "an error ocurred" or something like that

**Comment by samanthajayasinghe** [comment]
@SaphiLC please check following php session settings. I assume it's an issue with your local web server settings. 
```php
session.save_handler 
session.save_path
session.auto_start
```

**Comment by kavithagurusamy** [comment]
Released on OrangeHRM 4.1.2
