### ISSUE TITLE
Attachments download as .html

### ISSUE THREAD

**Issue by mtrayn01** [orangehrm/orangehrm#259]
After uploading any attachments, if I click on them to download them, the file extension always has .html appended.

If I rename the file to remove .html and keep the original file extension, the file opens correctly.

**Comment by kavithagurusamy** [comment]
@mtrayn01 
Which version of OrangeHRM are you using it? Are you using the latest version (4.1.1)?
Can you mention in which screen you have tried this? (E.g: PIM - Personal Details)
What is the type of file you have uploaded?
Are you opening in the browser itself or downloading and opening it?

**Comment by kavithagurusamy** [comment]
@mtrayn01 
We are unable to reproduce your issue in latest version 4.3.1 as well. I am closing the issue since its outdated by a year. Please comment it if you still see the issue with the steps to reproduce it.
