### ISSUE TITLE
Incorrect version number in config file

### ISSUE THREAD

**Issue by jameswill** [orangehrm/orangehrm#262]
Hi,

I have downloaded latest package from [https://www.orangehrm.com/solutions/open-source/register-to-download/?type=stable-zip]() which is of 4.1. However when I tried installing manually on one of our servers it is setting 4.0.1 in **/lib/confs/Conf.php** post installation.

When I login into admin panel, it is showing correct version i.e 4.1. After further finding I found that is taking from **{PATH}/{TO}/{orange411}/symfony/apps/orangehrm/templates/_copyright.php**

I wanted to know why it is taking wrong version in Conf.php file ?

**Comment by jameswill** [comment]
Hi,

Any update regarding this ?

**Comment by kavithagurusamy** [comment]
Fixed in OrangeHRM 4.1.2
