### ISSUE TITLE
Not saving Organization Name

### ISSUE THREAD

**Issue by ftarnogol** [orangehrm/orangehrm#263]
After completing and saving Organization name, going to structure triggers message "Please Add the Organization name". Going back to Org Name section, information is not there anymore.

**Comment by kavithagurusamy** [comment]
@ftarnogol What version of OrangeHRM you are using.? Whats your deployment environment?
Can you please mention about the browser details that you are using..and the Organisation name that you have entered for this?
I tried with 4.1.1 version and it was working fine for me.

**Comment by kavithagurusamy** [comment]
@ftarnogol Iam closing this, Please let me know if you still have the issue.
