### ISSUE TITLE
Base url is messed up

### ISSUE THREAD

**Issue by Awais-cb** [orangehrm/orangehrm#265]
just installed new copy of orange hrm after installation base url goes wrong and nothing loads up right.
the errors i am getting in console

`5Refused to apply style from '<URL>' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
login:1 [DOM] Found 2 elements with non-unique id #csrf_token: (More info: https://goo.gl/9p2vKq) <input type=​"hidden" name=​"_csrf_token" value=​"d42fc406a589c93024da5a64248946f1" id=​"csrf_token">​ <input type=​"hidden" name=​"_csrf_token" value=​"f9873d9267e8f2196d37b4b067eb9117" id=​"csrf_token">​
login:186 GET https://demo.clipbucket.com/hrm/hrm_demo/symfony/web/home/cb/web/demo.clipbucket.com/public_html/hrm/hrm_demo/symfony/web/themes/default/images/login/logo.png 404 (Not Found)
login:257 GET https://demo.clipbucket.com/hrm/hrm_demo/symfony/web/home/cb/web/demo.clipbucket.com/public_html/hrm/hrm_demo/symfony/web/themes/default/images/login/linkedin.png 404 (Not Found)
jquery-1.7.2.min.js:2 GET https://demo.clipbucket.com/hrm/hrm_demo/symfony/web/home/cb/web/demo.clipbucket.com/public_html/hrm/hrm_demo/symfony/web/themes/default/images/login/login.png 404 (Not Found)
(anonymous) @ jquery-1.7.2.min.js:2
o @ jquery-1.7.2.min.js:2
fireWith @ jquery-1.7.2.min.js:2
ready @ jquery-1.7.2.min.js:2
B @ jquery-1.7.2.min.js:2
login:259 GET https://demo.clipbucket.com/hrm/hrm_demo/symfony/web/home/cb/web/demo.clipbucket.com/public_html/hrm/hrm_demo/symfony/web/themes/default/images/login/facebook.png 404 (Not Found)
login:263 GET https://demo.clipbucket.com/hrm/hrm_demo/symfony/web/home/cb/web/demo.clipbucket.com/public_html/hrm/hrm_demo/symfony/web/themes/default/images/login/youtube.png 404 (Not Found)
login:261 GET https://demo.clipbucket.com/hrm/hrm_demo/symfony/web/home/cb/web/demo.clipbucket.com/public_html/hrm/hrm_demo/symfony/web/themes/default/images/login/twiter.png 404 (Not Found)
jquery-1.7.2.min.js:2 GET https://demo.clipbucket.com/hrm/hrm_demo/symfony/web/home/cb/web/demo.clipbucket.com/public_html/hrm/hrm_demo/symfony/web/themes/default/images/login/Login_button.png 404 (Not Found)
(anonymous) @ jquery-1.7.2.min.js:2
o @ jquery-1.7.2.min.js:2
fireWith @ jquery-1.7.2.min.js:2
ready @ jquery-1.7.2.min.js:2
B @ jquery-1.7.2.min.js:2
favicon.ico:1 GET https://demo.clipbucket.com/hrm/hrm_demo/symfony/web/home/cb/web/demo.clipbucket.com/public_html/hrm/hrm_demo/symfony/web/themes/default/images/favicon.ico 404 (Not Found)`

**Comment by Awais-cb** [comment]
Css + JavaScript resources not found

**Comment by Awais-cb** [comment]
you guys suck at support like seriously!

**Comment by rimaz523** [comment]
Hi Awaic-cb,
Can you let me know the environment you have deployed this on? is it Windowss IIS or Apache on Linux? etc..
Did the installation steps complete without any issues? and can you check if the database has been successfully created in mysql/mariadb?
Also a screenshot of the Login page with the URL would be helpful in debugging this issue.
Thanks,

**Comment by Awais-cb** [comment]
Hi @rimaz523 
DB was successfully created.server is running on apache with linux centos,Installation was problematic with using `localhost` as local server i used `127.0.0.1` installation went ok but there was issue with paths which i resolved my self thanks for your concern.

**Comment by Awais-cb** [comment]
issue is with this file which overall returns paths of theme and plugins
