### ISSUE TITLE
attendance summary is not showing the reports of employees

### ISSUE THREAD

**Issue by umernasir19** [orangehrm/orangehrm#270]
attendance summary is not showing the reports of employees .it always shows 0 hours .

**Comment by kavithagurusamy** [comment]
@umernasir19 
Which version of OrangeHRM are you using? Are the employees' attendance records added?

I could be able to get the attendance summary when the employees are added with attendance record.
![attendancesummary](https://user-images.githubusercontent.com/25813012/43823949-55824e46-9b0e-11e8-97a0-063e934dd055.png)

**Comment by umernasir19** [comment]
4.1.1

**Comment by umernasir19** [comment]
i am unable to get attendance summary of employee records in version 4.1.1

**Comment by umernasir19** [comment]
here it is afzal(employee) spent 14 hours but it is not showing in the
records of admin in attendance summary

**Comment by kavithagurusamy** [comment]
can you please send the screenshot of employee attendance record screen..to confirm that the data is added in the system.

**Comment by umernasir19** [comment]
yes here it is

**Comment by kavithagurusamy** [comment]
Is your admin having an employee assigned or does he has any role like project admin?
Can you please explain more about the language, timezone, and browser u are using to replicate the issue.?

**Comment by umernasir19** [comment]
issue resolved thanks for support :)
