### ISSUE TITLE
Unable to create database

### ISSUE THREAD

**Issue by baig772** [orangehrm/orangehrm#312]
I am using PHP 7.0 on Ubuntu 18.
I am trying to install the OrangeHRM but seeing the error 
![screenshot-2018-8-30 orangehrm web installation wizard](https://user-images.githubusercontent.com/6718529/44845509-2bb9b580-ac67-11e8-875b-263ef1f561c8.png)
There is nothing in logs too

**Comment by mayuratsynerzip** [comment]
Try using 127.0.0.1 as database host instead of "localhost".
If it doesn't works then try to use php 5.6

**Comment by mayurkathale** [comment]
Try using 127.0.0.1 as database host instead of "localhost".
If it doesn't works then try to use php 5.6

**Comment by baig772** [comment]
This actually worked for me. Changing localhost to 127.0.0.1
