### ISSUE TITLE
BUG - API : Employee - Employee Dependents section given URL doesn't work

### ISSUE THREAD

**Issue by janakapk** [orangehrm/orangehrm#34]
Employee - Employee Dependents section given URL doesn't work

1.Doc says given URL as "https://{your-orangehrm-host}/api/v1/employee/:id/dependent"
2.This is not working and it should be as "https://{your-orangehrm-host}/api/v1/employee/:id/dependents"

**Comment by lakshithaorange** [comment]
This issue is fixed and will available with sprint 02-24

**Comment by janakapk** [comment]
Now it is corrected
