### ISSUE TITLE
PHP 7.2.9 issue

### ISSUE THREAD

**Issue by NelsonGaldeman** [orangehrm/orangehrm#360]
Is there any way to install it under PHP 7.2.9 I currently have some apps running under it and I cannot change PHP version.

**Comment by kavithagurusamy** [comment]
@NelsonGaldeman We have not certified with PHP 7.2.9, Certified maximum version is PHP 7.2.5.
You could change the system requirement file to install it in your version.
Modify the maximum version in the following path
 - OrangeHRM/installer/environmentCheck/system_requirements.yml
Change with following
phpversion:
    min: '5.6'
    max: '7.2.9'
    excludeRange: []

**Comment by NelsonGaldeman** [comment]
Thank you
