### ISSUE TITLE
Add mysqli & pdo_mysql modules to pre-requisites check

### ISSUE THREAD

**Issue by NelsonGaldeman** [orangehrm/orangehrm#361]
Would be great to have mysqli & pdo_mysql at the pre-requisites check, If you do not have them enabled, it will thought an exception.

**Comment by kavithagurusamy** [comment]
Thanks @NelsonGaldeman for sharing your viewpoint. We will consider this in a future release.

**Comment by RajithaKumara** [comment]
Hi @kavithagurusamy,
We can close this. Because, this is fixed in 4.2 release.
