### ISSUE TITLE
BUG - API : Email format is not validating when adding the Contact Details

### ISSUE THREAD

**Issue by janakapk** [orangehrm/orangehrm#37]
Email format is not validating when adding the Contact Details.

1.Added contact detail via the postman
2.Added email as janaka@orangehrm.com1
3.It allowed to save the data

**Comment by samanthajayasinghe** [comment]
@janakapk , @lakshithaorange 
 janaka@orangehrm.com1 is valid email address in email context

**Comment by lakshithaorange** [comment]
closing the issue hence email format is valid
