### ISSUE TITLE
Dockerfile severely broken

### ISSUE THREAD

**Issue by phiros** [orangehrm/orangehrm#407]
Hey folks,
I wanted to take OrangeHRM for a spin and was positively surprised that it comes with a Dockerfile until I realized that the Dockerfile is broken for quite some time. Also I noticed that it is using an ancient ubuntu base image.

**Comment by samanthajayasinghe** [comment]
@phiros Thanks for raising the issue, We will fix the issue in next release.

**Comment by nuheluxulu** [comment]
Bump.
This is what I have so far, but my nginx config seems to be redirecting me, so something is off there

`
#docker-compose.yml
version: '3'

volumes:
  mysql_orangehrm_production: {}

networks:
  net_orangehrm_production: {}

services:
  db:
    restart: always
    image: mariadb
    env_file: mysql.env
    volumes:
      - mysql_orangehrm_production:/var/lib/mysql
    networks:
      - net_orangehrm_production
  app:
    restart: always
    build:
      context: ./app
    volumes:
      - ./orangehrm/:/site:ro
      - ./Conf.php:/site/lib/confs/Conf.php:ro
    depends_on:
      - db
    networks:
      - net_orangehrm_production

  web:
    restart: always
    image: nginx:alpine
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/site.conf:ro
      - ./wildcard.pem:/etc/ssl/certs/wildcard.pem:ro
      - ./cache:/var/cache/nginx
      - ./run:/var/run
      - ./orangehrm/:/site:ro
      - ./Conf.php:/site/lib/confs/Conf.php:ro
    ports:
      - 80:80
      - 443:443
    networks:                                  
      - net_orangehrm_production 
`

`
#Conf.php
<?php
class Conf {

	var $smtphost;
	var $dbhost;
	var $dbport;
	var $dbname;
	var $dbuser;
	var $version;

	function Conf() {

		$this->dbhost	= 'db';
		$this->dbport 	= '3306';
		if(defined('ENVIRNOMENT') && ENVIRNOMENT == 'test'){
		$this->dbname    = 'test_orangehrm_production';
		}else {
		$this->dbname    = 'orangehrm_production';
		}
		$this->dbuser    = 'orangehrm_user';
		$this->dbpass	= 'some_secret_pass';
		$this->version = '3.3.3';

		$this->emailConfiguration = dirname(__FILE__).'/mailConf.php';
		$this->errorLog =  realpath(dirname(__FILE__).'/../logs/').'/';
	}
}
?>
`
`
#mysql.env
MYSQL_ROOT_PASSWORD=some_super_secret_pass
MYSQL_DATABASE=orangehrm_production                                                   
MYSQL_USER=orangehrm_user                                                          
MYSQL_PASSWORD=some_secret_pass
`
`
#nginx.conf
server {
    server_name orangehrm.example.org;
    root /site;

    location / {
        # try to serve file directly, fallback to app.php
        try_files $uri /index.php$is_args$args;
    }
    # PROD
    location ~ ^/index\.php(/|$) {
        fastcgi_pass app:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
       # When you are using symlinks to link the document root to the
       # current version of your application, you should pass the real
       # application path instead of the path to the symlink to PHP
       # FPM.
       # Otherwise, PHP's OPcache may not properly detect changes to
       # your PHP files (see https://github.com/zendtech/ZendOptimizerPlus/issues/126
       # for more information).
       fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
       fastcgi_param DOCUMENT_ROOT $realpath_root;
       # Prevents URIs that include the front controller. This will 404:
       # http://domain.tld/app.php/some-path
       # Remove the internal directive to allow URIs like this
       internal;
   }

   # return 404 for all other php files not matching the front controller
   # this prevents access to other php files you don't want to be accessible.
   location ~ \.php$ {
     return 404;
   }

   error_log /var/log/nginx/project_error.log;
   access_log /var/log/nginx/project_access.log;
}
`
`
#app/Dockerfile
# escape=`

FROM php:7.3.7-fpm-alpine
#TODO Install required PHP
`

**Comment by RajithaKumara** [comment]
Hi @nuheluxulu 
Do you want to improve your `nginx.conf` file? If so you can refer orangehrm development environment Nginx configuration [[1]](https://github.com/orangehrm/orangehrm-os-dev-environment/blob/master/server/nginx/config/server.conf) [[2]](https://github.com/orangehrm/orangehrm-os-dev-environment/blob/master/server/nginx/config/orangehrm.conf) and adupt it to your production environment. Also you can improve your `php` Dockerfile by referring [orangehrm development environment PHP Dockerfile](https://github.com/orangehrm/orangehrm-os-dev-environment/blob/master/php/php73/Dockerfile).
