### ISSUE TITLE
Missing bin2hex

### ISSUE THREAD

**Issue by adrianjcalvert** [orangehrm/orangehrm#416]
https://github.com/orangehrm/orangehrm/blob/ec59be3850083fe38aee19014281af0d0749c1ec/upgrader/apps/upgrader/lib/schemaIncrementTasks/SchemaIncrementTask59.php#L72

https://github.com/orangehrm/orangehrm/blob/ec59be3850083fe38aee19014281af0d0749c1ec/upgrader/apps/upgrader/lib/schemaIncrementTasks/SchemaIncrementTask60.php#L104

These lines cause a similar error to below when upgrading because they are not wrapped with `bin2hex` as they are on the main installation script.

`return bin2hex(\phpseclib\Crypt\Random::string(55));`  fixes the issue

> 2018-Oct-29 12:01:37 : MySQL Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Q?')' at line 1. 
Query: INSERT INTO `hs_hr_config` ( `key`, `value`) VALUES ('csrf_secret', 'Õ¹%Éžö|½VG¶¦–ZpÐ™<Ã3ÈÜ@¤Ü4ÙÝ¸‡CW1ÚÌ·ƒìpaP¿(àC-ˆ\Á'QÂ');

**Comment by RajithaKumara** [comment]
Hi @adrianjcalvert 
Thank you for raise this issue.
