### ISSUE TITLE
Unable to login into Orangehrm 4.2

### ISSUE THREAD

**Issue by jameswill** [orangehrm/orangehrm#418]
Hi,

I have installed orangehrm 4.2 on one of my test server and I am unable to logging into admin panel.

When I fill admin credentials it redirects again to login screen and does not update any log files as well.

I have gone through **/symfony/log** and **/lib/logs** but no files were generated into that directories.

Is there anyway to debug this further ?

**Comment by jameswill** [comment]
Hi,

I have tried on both the servers. i.e with and without HTTPS and getting same issue on both.

**Comment by kavithagurusamy** [comment]
@jameswill 
I am willing to help you to solve the issue. Can you please share the screenshot of your screen?
Which browser you are using it?

**Comment by jameswill** [comment]
Hi,

I have tried on both the browsers. Here is an screenshot of Mozilla firefox browser..

![orangehrm](https://user-images.githubusercontent.com/6368036/47907985-536d0a00-deb2-11e8-923f-0691e6b9e75f.png)

**Comment by jameswill** [comment]
Hi,

I have tried on both the browsers. Here is a screenshot of Mozilla firefox browser..


![orangehrm](https://user-images.githubusercontent.com/6368036/47908516-57e5f280-deb3-11e8-92c0-6f27df85ffd0.png)

**Comment by RajithaKumara** [comment]
Hi @jameswill,
Normally this issue comes with cookie issue. Can you check using browser developer option, is there cookie called PHPSESSID?

**Comment by jameswill** [comment]
> 
> 
> Hi @jameswill,
> Normally this issue comes with cookie issue. Can you check using browser developer option, is there cookie called PHPSESSID?

Yes, there is coockie genretaed named PHPSESSID.

**Comment by RajithaKumara** [comment]
Could you please send the running server details if you are okay. And also PHP modules you are enabled.

**Comment by jameswill** [comment]
> 
> 
> Could you please send the running server details if you are okay. And also PHP modules you are enabled.

Sure.

My server runs on PHP 7.0.28
Mysql version 5.5
Apache 2.2
Linux 64 bit

There are so many modules enables including tokenizer, mbstring, zlib, iconv etc

**Comment by RajithaKumara** [comment]
Could you please try enabling `mod_ssl` in your Apache server.

**Comment by jameswill** [comment]
Can you please guide, how to enable mod_ssl ?

**Comment by jameswill** [comment]
> 
> 
> Could you please try enabling `mod_ssl` in your Apache server.

It is already loaded in my apache

**Comment by RajithaKumara** [comment]
You can follow Apache guide. http://httpd.apache.org/docs/2.2/ssl/
Anyway, we are planning to remove this HTTPS restriction as soon as possible. Thank you for raising this issue.

**Comment by jameswill** [comment]
But what can I do to make my this installation work ? Shall I wait for next release ? if yes then is there any ETA to release new release ?

**Comment by RajithaKumara** [comment]
According to you provided the screenshot, it seems like you are using invalid SSL certificate. If you are okay with server file changes, I can provide file changes you need to do.

**Comment by jameswill** [comment]
> 
> 
> According to you provided the screenshot, it seems like you are using invalid SSL certificate. If you are okay with server file changes, I can provide file changes you need to do.

Ideally it should work on both. Right ?

If you are planning to remove this HTTPS restriction,  may I know is there any ETA for new release ?

**Comment by jameswill** [comment]
> 
> 
> @jameswill We will make 4.2.0.1 release soon which will allow both http and https. Pre-release available today. Will you be volunteering to test it?

I shall wait for new release.

**Comment by srigurubyo** [comment]
> @jameswill We will make 4.2.0.1 release soon which will allow both http and https. Pre-release available today. Will you be volunteering to test it?

Yes, I am willing to test it.  How do I get the fixes?

**Comment by RajithaKumara** [comment]
We are released 4.2.0.1. Could you please try that.

**Comment by srigurubyo** [comment]
Just installed and tested 4.2.0.1.  Works perfectly fine. Thanks for your quick fix.

**Comment by kavithagurusamy** [comment]
Closing the issue , OS 4.2.0.1 is supported to host without https.
