### ISSUE TITLE
mydomain/installer/installerUI.php   this is balck page 

### ISSUE THREAD

**Issue by Ghost173** [orangehrm/orangehrm#425]
i try with php 5.6, 7.0, 7.2  all are in this page show as blank how can i fix this issues?

**Comment by RajithaKumara** [comment]
Hi @Ghost173 
What is the OrangeHRM version you are tried?
Could you please send the `orangehrm.log` file which is located in `OHRM_ROOT_DIR\symfony\log` directory? If there are sensitive data in that log file please replace them as you preferred.

**Comment by Ghost173** [comment]
oops sorry php version 7.2.10 too high  sorry please close this issue :(

**Comment by kavithagurusamy** [comment]
Closing the issue as per the reporters' request.
