### ISSUE TITLE
cannot Install

### ISSUE THREAD

**Issue by andiahap** [orangehrm/orangehrm#430]
Hai, apakah ada yang pernah mengalami permasalahan seperti saya?? 
Mysql client Not support,
Mysql Server Nov availabel,
Mysql InnoDB Support Cannot Connect database
Mysql Event Scheduler status Canot Connect database

yang saya gunakan adalah Xampp ver3.2.2 dan Orange Ver 3.2.1
Mohon bantuannya ya....

![img1](https://user-images.githubusercontent.com/45480096/49560843-9bb29880-f946-11e8-9490-4998b3fccadb.jpg)

**Comment by RajithaKumara** [comment]
Hi @andiahap 
As I understood, your database connection is not working properly. Please use OrangeHRM latest release available at [sourceforge](https://sourceforge.net/p/orangehrm/) insted of tring OrangeHRM 3.2.1. So we are currently supporting maximum PHP version is 7.2.5, maximum MySQL version is 5.7.24 and maximum MariaDB version is 10.3.7. Please consider that before going forward with installer.

**Comment by kavithagurusamy** [comment]
@andiahap I am closing this issue since there is no open issue from OrangeHRM side, Please let me know whether you have successfully installed it.
We could reopen the issue if you have any issues identified further.
