### ISSUE TITLE
autoload.php No such file or directory error

### ISSUE THREAD

**Issue by ravisinghnath** [orangehrm/orangehrm#437]
Hi,
I am using the latest version of Orange HRM locally. I have installed xampp-win32-5.6.39-0-VC11-installer and on web install the orange HRM I got the error - 

Warning: require(C:\xampp\htdocs\orangehrm-master\installer\environmentCheck/../../symfony/lib/vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\orangehrm-master\installer\environmentCheck\SystemValidator.php on line 22

Fatal error: require(): Failed opening required 'C:\xampp\htdocs\orangehrm-master\installer\environmentCheck/../../symfony/lib/vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\orangehrm-master\installer\environmentCheck\SystemValidator.php on line 22

![o-hrm](https://user-images.githubusercontent.com/36439114/50286199-ad3a8b00-0484-11e9-8643-2c936073821f.png)
Please help me with that.
Thank you

**Comment by RajithaKumara** [comment]
Hi @ravisinghnath 
You need to install composer dependencies. Please refer https://github.com/orangehrm/orangehrm/wiki/Development to setup requirements. Or you can use latest release from [here](https://sourceforge.net/projects/orangehrm/).

**Comment by kavithagurusamy** [comment]
@ravisinghnath I am closing this ticket. This issue is resolved if you follow the development guide. Please let me know whether you were able to install this successfully.
