### ISSUE TITLE
Unable to see anything on System Check step

### ISSUE THREAD

**Issue by baig772** [orangehrm/orangehrm#440]
I am trying to install a fresh clone of orangeHRM. After the database credentials step, I am unable to see anything on the screen. There is nothing in the logs.
https://screenshots.firefox.com/9Dqsn3a8UWKGD3Om/softak-hrm.local#

**Comment by RajithaKumara** [comment]
Hi @baig772 
You need to install composer dependencies to going forward. Please use latest release from [here](https://sourceforge.net/projects/orangehrm/).  If you want to develop something, refer https://github.com/orangehrm/orangehrm/wiki/Development

**Comment by baig772** [comment]
Got it, solved the issue
