### ISSUE TITLE
Unable to Login - Demo 

### ISSUE THREAD

**Issue by deeprathod** [orangehrm/orangehrm#441]
Hello, i am unable to login in Demo URL which is mentioned in the description which is: 

https://opensource-demo.orangehrmlive.com/index.php/

It shows **Invalid Credentials** every-time.  I am using the credentials mentioned in the above url as,  Admin & admin123

Thank You

**Comment by RajithaKumara** [comment]
Hi @deeprathod 
That credentials works for me. Please try again.

**Comment by kavithagurusamy** [comment]
@deeprathod 
Hope its working for you. we have validated that the demo instance is working as expected.

**Comment by stiffroy** [comment]
Is there any restriction on the number of concurrent logins? I can't login too.

**Comment by sripop** [comment]
Yes..first few times it works but after few attempts it is showing invalid credential

**Comment by KarlJasson** [comment]
The Admin/admin123 credentials are not working again.

**Comment by cyrilbeyo** [comment]
Not working

**Comment by sangle2710** [comment]
This site (https://opensource-demo.orangehrmlive.com/index.php/) can not login with Admin account recently. It always show "Invalid credentials". Please fix it soon.

**Comment by 47techies** [comment]
I'm also unable to login with those credentials , Suggest me a solution

**Comment by cozyloon** [comment]
login credentials are not working for me as well

**Comment by cakarta** [comment]
Not working for me as well

**Comment by Rafat97** [comment]
Not working. 
It says account was disabled.

**Comment by dz1dz1on** [comment]
The same situation today.

**Comment by RajithaKumara** [comment]
This is fixed in https://github.com/orangehrm/orangehrm/pull/1418 and update [demo](https://opensource-demo.orangehrmlive.com) is available.
