### ISSUE TITLE
Can´t connect with AD user.

### ISSUE THREAD

**Issue by ZedPokermann** [orangehrm/orangehrm#446]
I configured ValidateCredentialsAction.class.php in order to use AD credentials to login, I can login correctly with the local credentials but when I login with AD username/password I`m being redirected to http://SERVER-IP/orangehrm/symfony/web/index.php/dashboard, but the login front page still showing up.

**Comment by kavithagurusamy** [comment]
@localsys 
Are you using the LDAP plugin from OrangeHRM?

**Comment by localsys** [comment]
I´m using adLDAP because I can´t find the plugin of OrangeHRM.

**Comment by kavithagurusamy** [comment]
LDAP plugin is available for OrangeHRM but its paid addon. You can install the latest version of OrangeHRM 4.3, and proceed with the request for LDAP
