### ISSUE TITLE
How can i add new user role in OrangeHRM 3.3.2 ?

### ISSUE THREAD

**Issue by teamghi** [orangehrm/orangehrm#447]
i want to add HRManager role to access and manage PIM module only

**Comment by kavithagurusamy** [comment]
@teamghi 
OrangeHRM open source version doesn't have a feature to control the user role for only chosen screens or modules. You could try with OrangeHRM enterprise trial version.

**Comment by kavithagurusamy** [comment]
@teamghi 
I am closing this ticket since your query is related to customizing the orangehrm open source version.
You need to have detailed understanding of OrangeHRM code to customise it.

Please do let us know if you require any help on open source version.

**Comment by jamu123** [comment]
how  can i add user role to  orangehrm open source version.
