### ISSUE TITLE
SugarCRM installation frozen

### ISSUE THREAD

**Issue by jacketlong** [orangehrm/orangehrm#459]
I'm trying to install SugarCRM version 6.5.23. on a webhost.

Everything goes nice until the step when the installation begins.

The output is this one:

Creating Sugar configuration file (config.php)

Creating Sugar application tables, audit tables and relationship metadata

.............

And never moves on!

**Comment by samanthajayasinghe** [comment]
@jacketlong 
This issue is not relevant here because it's something to do with SugerCRM
