### ISSUE TITLE
Bug : Success and error messages word should start with capital letters all 

### ISSUE THREAD

**Issue by janakapk** [orangehrm/orangehrm#47]
Success and error messages word should start with capital letters  

Successfully saved - > Successfully Saved
Updating failed -> Updating Failed
invalid Parameter -> Invalid Parameter
etc

**Comment by lakshithaorange** [comment]
@samanthajayasinghe need to clarify this issue , currently I'm using only first letter capital

**Comment by janakapk** [comment]
Decided to have 

Successfully saved
Updating failed
Invalid parameter
