### ISSUE TITLE
Pending Leave Request section on Dashboard didn't show information

### ISSUE THREAD

**Issue by huynq2007** [orangehrm/orangehrm#470]
Hi there,
[Pending Leave Requests] didn't show requested leaves information even I can confirm it from leave list. Is it a bug or do I need to configure something?

<img width="942" alt="screen shot 2019-02-28 at 20 58 49" src="https://user-images.githubusercontent.com/39758800/53565495-0289cb80-3b9d-11e9-911a-031f8c86baff.png">

 *The OrangeHRM package I'm using is **orangehrm-4.2.0-1-21**

**Comment by kavithagurusamy** [comment]
@huynq2007 Thanks for the update, We have identified this as an issue in the system.
We will be fixing this issue in our next release, will keep you updated when the fix is available.

**Comment by huynq2007** [comment]
@kavithagurusamy 
It seems that this issue has been fixed in **OrangeRHM Version 4.3 Release**

Thank you for your supporting!

**Comment by sobanakram** [comment]
Hi,
I still have this issue even in Version 4.3

**Comment by kavithagurusamy** [comment]
@sobanakram This is fixed in OrangeHRM 4.3.1 release and will be released end of this month.

You can get the patch from the following pull request.
https://github.com/orangehrm/orangehrm/pull/475

**Comment by kavithagurusamy** [comment]
This is fixed in 4.3.1
The latest release is available on SourceForge
https://sourceforge.net/projects/orangehrm/files/stable/4.3.1/
