### ISSUE TITLE
Upgrade for 3.3.2 to 4.0/4.3

### ISSUE THREAD

**Issue by nethubonline** [orangehrm/orangehrm#481]
Hi all,

I tried to upgrade my OrangeHRM from version 3.3.2 to 4.0/4.1/4.2.0.1/4.3 but failed, and I also tested to fresh install a version 3.3.2 and upgrade to 4.0/4.1/4.2.0.1/4.3 which also failed. Below is what I tested, can someone help?

**Environment:**
OS CentOS Linux release 7.3 x64
Apache: 2.4.6
MariaDB: 10.1
PHP: 5.6.39

**To duplicate problem of upgrading 3.3.2 to 4.0**
-------------------------------------------------------------
1. Download orangehrm-3.3.2.zip from https://sourceforge.net/projects/orangehrm/files/stable/3.3.2/, unzip & upload to website root directory

2. Install via HTTP website and working without problem

3. Download orangehrm-4.0.zip from https://sourceforge.net/projects/orangehrm/files/stable/4.0/, unzip & upload to website root directory to overwrite all files

4. Go to HTTP website /installer/installerUI.php , click "upgrading" and found blank page

5. /symfony/log/orangehrm.log shows:
[02-Apr-2019 10:14:48 Asia/Hong_Kong] PHP Fatal error:  Cannot redeclare class Swift in /var/www/vhosts/test.com/symfony/lib/vendor/symfony/lib/vendor/swiftmailer/classes/Swift.php on line 18

6. Apache log shows: 
1.2.3.4 - - [02/Apr/2019:02:14:46 +0000] "GET /installer/installerUI.php HTTP/1.0" 200 4151 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
1.2.3.4 - - [02/Apr/2019:02:14:48 +0000] "GET /upgrader/web/index.php/ HTTP/1.0" 302 348 "http://test.com/installer/installerUI.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
1.2.3.4 - - [02/Apr/2019:02:14:48 +0000] "GET /index.php HTTP/1.0" 302 235 "http://test.com/installer/installerUI.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
1.2.3.4 - - [02/Apr/2019:02:14:48 +0000] "GET /symfony/web/index.php/auth/login HTTP/1.0" 500 396 "http://test.com/installer/installerUI.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"

**To duplicate problem of upgrading 3.3.2 to 4.1/4.2.0.1/4.3**
-------------------------------------------------------------
1. Download orangehrm-3.3.2.zip from https://sourceforge.net/projects/orangehrm/files/stable/3.3.2/, unzip & upload to website root directory

2. Install via HTTP and working without problem

3. Download orangehrm-4.3.zip from https://sourceforge.net/projects/orangehrm/files/stable/4.3/, unzip & upload to website root directory to overwrite all files

4. Go to HTTP website /installer/installerUI.php , click "upgrading"

5. At "Database Information" page, enter database login info, click "Proceed"

6. Everything is green except "MySQL Event Scheduler status 	Disabled. This is required for automatic leave status changes of Leave module.", still click "Proceed"

7. Select "3.3.2" for "Current OrangeHRM Version", click "Proceed"

8. At "Version Information" page, click "Proceed"

9. "Applying Database Changes" page, click "Start" and then click "Proceed"

10. "Creating Configuration Files" page, click "Start" and then click "Proceed"

11. "Congratulations!" page, click "Proceed"

12. /symfony/log/orangehrm.log shows:
[02-Apr-2019 10:35:52 Asia/Hong_Kong] PHP Fatal error:  Class 'SessionAttributeSetterListener' not found in /var/www/vhosts/test.com/symfony/apps/orangehrm/config/orangehrmConfiguration.class.php on line 24

13. Apache log shows: 
1.2.3.4 - - [02/Apr/2019:02:35:26 +0000] "GET /upgrader/web/index.php HTTP/1.1" 302 607 "http://test.com/installer/installerUI.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
1.2.3.4 - - [02/Apr/2019:02:35:26 +0000] "GET /upgrader/web/index.php/upgrade/getDatabaseInfo HTTP/1.1" 200 6617 "http://test.com/installer/installerUI.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
1.2.3.4 - - [02/Apr/2019:02:35:32 +0000] "POST /upgrader/web/index.php/upgrade/getDatabaseInfo HTTP/1.1" 302 614 "http://test.com/upgrader/web/index.php/upgrade/getDatabaseInfo" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
1.2.3.4 - - [02/Apr/2019:02:35:32 +0000] "GET /upgrader/web/index.php/upgrade/executeSystemCheck HTTP/1.1" 200 10035 "http://test.com/upgrader/web/index.php/upgrade/getDatabaseInfo" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
1.2.3.4 - - [02/Apr/2019:02:35:33 +0000] "GET /upgrader/web/images/dummy.jpg HTTP/1.1" 403 1094 "http://test.com/upgrader/web/index.php/upgrade/executeSystemCheck" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
1.2.3.4 - - [02/Apr/2019:02:35:35 +0000] "POST /upgrader/web/index.php/upgrade/executeSystemCheck HTTP/1.1" 302 627 "http://test.com/upgrader/web/index.php/upgrade/executeSystemCheck" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
1.2.3.4 - - [02/Apr/2019:02:35:35 +0000] "GET /upgrader/web/index.php/upgrade/calculateIncrementNumbers HTTP/1.1" 302 603 "http://test.com/upgrader/web/index.php/upgrade/executeSystemCheck" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
1.2.3.4 - - [02/Apr/2019:02:35:35 +0000] "GET /upgrader/web/index.php/upgrade/selectVersion HTTP/1.1" 200 5922 "http://test.com/upgrader/web/index.php/upgrade/executeSystemCheck" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
1.2.3.4 - - [02/Apr/2019:02:35:41 +0000] "POST /upgrader/web/index.php/upgrade/calculateIncrementNumbers HTTP/1.1" 302 614 "http://test.com/upgrader/web/index.php/upgrade/selectVersion" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
1.2.3.4 - - [02/Apr/2019:02:35:41 +0000] "GET /upgrader/web/index.php/upgrade/displayVersionInfo HTTP/1.1" 200 3833 "http://test.com/upgrader/web/index.php/upgrade/selectVersion" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
1.2.3.4 - - [02/Apr/2019:02:35:43 +0000] "POST /upgrader/web/index.php/upgrade/displayVersionInfo HTTP/1.1" 302 607 "http://test.com/upgrader/web/index.php/upgrade/displayVersionInfo" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
1.2.3.4 - - [02/Apr/2019:02:35:43 +0000] "GET /upgrader/web/index.php/upgrade/executeDbChange HTTP/1.1" 200 5086 "http://test.com/upgrader/web/index.php/upgrade/displayVersionInfo" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
1.2.3.4 - - [02/Apr/2019:02:35:45 +0000] "GET /upgrader/web/index.php/upgrade/dbChangeControl?task=64 HTTP/1.1" 200 383 "http://test.com/upgrader/web/index.php/upgrade/executeDbChange" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
1.2.3.4 - - [02/Apr/2019:02:35:45 +0000] "GET /upgrader/web/index.php/upgrade/dbChangeControl?task=65 HTTP/1.1" 200 383 "http://test.com/upgrader/web/index.php/upgrade/executeDbChange" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
1.2.3.4 - - [02/Apr/2019:02:35:45 +0000] "GET /upgrader/web/index.php/upgrade/dbChangeControl?task=66 HTTP/1.1" 200 383 "http://test.com/upgrader/web/index.php/upgrade/executeDbChange" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
1.2.3.4 - - [02/Apr/2019:02:35:45 +0000] "GET /upgrader/web/index.php/upgrade/dbChangeControl?task=67 HTTP/1.1" 200 383 "http://test.com/upgrader/web/index.php/upgrade/executeDbChange" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
1.2.3.4 - - [02/Apr/2019:02:35:45 +0000] "GET /upgrader/web/index.php/upgrade/dbChangeControl?task=68 HTTP/1.1" 200 383 "http://test.com/upgrader/web/index.php/upgrade/executeDbChange" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
1.2.3.4 - - [02/Apr/2019:02:35:46 +0000] "GET /upgrader/web/index.php/upgrade/dbChangeControl?task=69 HTTP/1.1" 200 383 "http://test.com/upgrader/web/index.php/upgrade/executeDbChange" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
1.2.3.4 - - [02/Apr/2019:02:35:46 +0000] "POST /upgrader/web/index.php/upgrade/executeDbChange HTTP/1.1" 302 611 "http://test.com/upgrader/web/index.php/upgrade/executeDbChange" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
1.2.3.4 - - [02/Apr/2019:02:35:46 +0000] "GET /upgrader/web/index.php/upgrade/executeConfChange HTTP/1.1" 200 4574 "http://test.com/upgrader/web/index.php/upgrade/executeDbChange" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
1.2.3.4 - - [02/Apr/2019:02:35:48 +0000] "POST /upgrader/web/index.php/upgrade/executeConfChange HTTP/1.1" 200 4570 "http://test.com/upgrader/web/index.php/upgrade/executeConfChange" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
1.2.3.4 - - [02/Apr/2019:02:35:50 +0000] "POST /upgrader/web/index.php/upgrade/executeConfChange HTTP/1.1" 302 607 "http://test.com/upgrader/web/index.php/upgrade/executeConfChange" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
1.2.3.4 - - [02/Apr/2019:02:35:50 +0000] "GET /upgrader/web/index.php/upgrade/executeComplete HTTP/1.1" 200 4318 "http://test.com/upgrader/web/index.php/upgrade/executeConfChange" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
1.2.3.4 - - [02/Apr/2019:02:35:52 +0000] "GET / HTTP/1.1" 302 285 "http://test.com/upgrader/web/index.php/upgrade/executeComplete" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
1.2.3.4 - - [02/Apr/2019:02:35:52 +0000] "GET /symfony/web/index.php/auth/login HTTP/1.1" 500 273 "http://test.com/upgrader/web/index.php/upgrade/executeComplete" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"

**Comment by RajithaKumara** [comment]
Hi @nethubonline 
Can you please try replace vhost directory (test.com) instead overwriting when you unzipping. Or you can try clearing symfony cache. You can manually delete cache by deleting files and directories in <web-root>/symfony/cache/, or you can run
`$ cd  <web-root>/symfony/
$ php symfony cc`
In the first attemp (3.3.2 to 4.0) it seems the unzipping not completed.

**Comment by nethubonline** [comment]
Wow, after delete the cache, it works like a charm, thanks for your help.

**Comment by nethubonline** [comment]
Hi,

I was happy too fast because I got msg "You have successfully upgraded OrangeHRM", but I tried to login with admin, it shows blank page (error 500) and /symfony/log/orangehrm.log shows below error, could you advise?

[02-Apr-2019 19:35:53 Asia/Hong_Kong] PHP Fatal error:  Call to undefined method PasswordHash::verify() in /var/www/vhosts/test.com/symfony/plugins/orangehrmAdminPlugin/lib/service/SystemUserService.php on line 279

**Comment by RajithaKumara** [comment]
How did you successfully upgraded? By replacing OrageHRM 3.3.2 to OrangeHRM 4.3 or by overwriting OrageHRM 3.3.2 to OrangeHRM 4.3? If you upgrade OrangeHRM by overwriting, then it will lead to this issue. Please completely remove existing code base and unzip OrangeHRM 4.3. Otherwise, you can test with another vhost. Make sure backup the database before upgrading.

So once you successfully upgraded to OrangeHRM 4.3, your database will support for OrangeHRM 4.3. You don't need to upgrade it again. Only need to update code base. Also backup `<web-root>/lib/confs/Conf.php`, `<web-root>/lib/confs/cryptokeys`, `<web-root>/symfony/config/databases.yml`. After replacing codebase to OrangeHRM 4.3 you can place above three file(s) into particular places and connect to the database.

**Comment by nethubonline** [comment]
After completely remove existing code base and unzip OrangeHRM 4.3, it works now, thanks very much for your help.
