### ISSUE TITLE
Unable to install, failing on the System Check step

### ISSUE THREAD

**Issue by ZahaGit** [orangehrm/orangehrm#482]
Hello, I have performed multiple attempts to install this via the installerUI.php and It always fails upon this step, where I get the following errors:

Warning: require(C:\xampp\htdocs\orangehrm\installer\environmentCheck/../../symfony/lib/vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\orangehrm\installer\environmentCheck\SystemValidator.php on line 22

Fatal error: require(): Failed opening required 'C:\xampp\htdocs\orangehrm\installer\environmentCheck/../../symfony/lib/vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\orangehrm\installer\environmentCheck\SystemValidator.php on line 22
![image](https://user-images.githubusercontent.com/48787282/55395263-e1285080-5549-11e9-9092-5825fcfbf136.png)

Any ideas how to get over this step? The only way that I was able to install Orange4 was via the online .exe installer but I would like to have a pre-configured XAMPP and then install a branch from github.

**Comment by RajithaKumara** [comment]
Hi @ZahaGit 
Please refer #440 and #437.

**Comment by ZahaGit** [comment]
Managed to make it work, thanks!
