### ISSUE TITLE
Missing CSS, the publish-assets, build-model and cc commands are not defined

### ISSUE THREAD

**Issue by ZahaGit** [orangehrm/orangehrm#483]
I have managed to install Orange 4.3 on local, but the CSS is completely missing.

I have found out that I have to run the following commands
   php symfony orangehrm:publish-assets;
   php symfony doctrine:build-model;
   php symfony cc;
but they all return a "task "x" is not defined."

![image](https://user-images.githubusercontent.com/48787282/55399559-189bfa80-5554-11e9-94b3-6e2584a14b44.png)

**Comment by kalanatebel97** [comment]
Hi @ZahaGit 
I think the problem is with the semicolon.Try to execute the commands without semicolon at the end.Then it will work properly.

**Comment by ZahaGit** [comment]
Yep that was it! maybe the Development section of the online guide should be edited to reflect this, as all have a semi colon on them :)

**Comment by samanthajayasinghe** [comment]
@ZahaGit Thanks for pointing out the issue on development docs .. I changed it ..
