### ISSUE TITLE
MySql  5.7.25 Support

### ISSUE THREAD

**Issue by haishajo** [orangehrm/orangehrm#490]
I am getting an error during the installation .

MySql Version should be higher than 5.5 and lower than 5.7.24 .Installed version is 5.7.25
--

Is there any way to get work orangeHRM under  MySql  5.7.25 ?

![orangehrm_mysl](https://user-images.githubusercontent.com/49494922/55903999-22b29e80-5bcf-11e9-890d-e86405b1dcc9.png)

**Comment by RajithaKumara** [comment]
Hi @haishajo 
Please refer #360 and update [here](https://github.com/orangehrm/orangehrm/blob/master/installer/environmentCheck/system_requirements.yml#L8) in `<web_root>/installer/environmentCheck/system_requirements.yml`.
Thank you for raising this issue. We will update this in next release.

**Comment by haishajo** [comment]
Hi @RajithaKumara 

Thank you very for your quick response.
I could successfully install the OrangeHRm after changing thse value in <web_root>/installer/environmentCheck/system_requirements.yml.

Once again I thank you very much for the support.

Regards
Shajo
