### ISSUE TITLE
Report security issue

### ISSUE THREAD

**Issue by smutranchi** [orangehrm/orangehrm#526]
Hello,

I am wandering where to submit a report about an security issue? 

Thanks in advanced!

**Comment by kavithagurusamy** [comment]
@smutranchi 
Please email your issue to kavitha@orangehrm.com.

**Comment by kavithagurusamy** [comment]
This will be released in the next version OS 4.3.2 scheduled to community release on 1st of July.

**Comment by kavithagurusamy** [comment]
Fixed at 4.3.2
https://sourceforge.net/projects/orangehrm/files/stable/4.3.2/
