### ISSUE TITLE
Updating to latest version from 3.2

### ISSUE THREAD

**Issue by Mindbowser** [orangehrm/orangehrm#535]
I am getting 500 internal server error when I followed upgrade steps as per - https://drive.google.com/file/d/1kdj4MYu7sTCr6RNBrJDT2ke6zMyF5Bid/view

Here is the error - 
`PHP Parse error:  syntax error, unexpected '[' in /var/www/html/symfony/plugins/orangehrmCorePlugin/lib/utility/PasswordHash.php on line 38
`
whereas old version is working fine, I have yet to setup mysql old db connection with this but before that only I am getting this error, any thoughts?

Here are the server details

Component | Status
-- | --
PHP version | OK (ver 5.3.28)
MySQL Client | OK (ver 5.5.62)
OrangeHRM Configuration File Writable | OK
Maximum Session Idle Time before Timeout | OK
Memory allocated for PHP script | OK

**Comment by samanthajayasinghe** [comment]
Hi @Mindbowser,
It's an issue with your PHP version .. update php version to 5.6 or 7.x version.

php 5.3 is very old and no support for that version 
https://www.php.net/supported-versions.php

**Comment by Mindbowser** [comment]
I upgrades, and after that some featurs like pending leaves, and few more are showing internal server error

**Comment by samanthajayasinghe** [comment]
Can you send the error log? It's in {ohrm-root}/symfony/log/orangehrm.log

**Comment by RajithaKumara** [comment]
Hi @Mindbowser 
Did you resolve the issue?
