### ISSUE TITLE
REST API get leave entitlement forces optional parameter

### ISSUE THREAD

**Issue by briveira** [orangehrm/orangehrm#549]
as per doc https://orangehrm.github.io/orangehrm-api-doc/#api-Leave-employeeLeaveEntitlement

the GET leave entitlements for an employee needs three params (employee id, fromDate, toDate) and has an optional parameter (leaveType)

so when leaveType (optional parameter) is not specified, API method should return all the available leave entitlements;  it will instead fail with:

{
    "error": {
        "status": "202",
        "text": "No Leave Types Available :"
    }
}

**Comment by samanthajayasinghe** [comment]
Hi @briveira 
Entitlement always calculate for the leave type and should return all if leave type not specified .. will fix the issue on upcoming release.

**Comment by kavithagurusamy** [comment]
fixed in OrangeHRM 4.3.5 version
