### ISSUE TITLE
make ess user as admin through databse 

### ISSUE THREAD

**Issue by shadowboo** [orangehrm/orangehrm#552]
unfortunately our hr forget her password but she have employer account  assess (separate demo account)  through database how can we make ess user to admin?

**Comment by Damith88** [comment]
OrangeHRM version 4.3.2 onwards password reset feature is available. If your OrangeHRM version is 4.3.2 or later then you can use the password reset feature to achieve that.

If your OrangeHRM instance is below 4.3.2, then you may use the below query to achieve what you want.
`update ohrm_user u left join hs_hr_employee e on e.emp_number = u.emp_number
set u.user_role_id = 1 # 1 for admin role
where e.emp_firstname = '<firstName>' AND e.emp_lastname = '<lastName>';`
