### ISSUE TITLE
[Bug - Save Employee] - Returned ID is wrong in after add the employee  

### ISSUE THREAD

**Issue by janakapk** [orangehrm/orangehrm#56]
[Bug - Save Employee] - Returned ID is wrong in after add the employee  

1. Added employee with bellow details 
firstName = a
middleName = a
lastName = a
code =123
2. Result shows as bellow 
 {  "success": "Successfully saved", 
  "id": "0006"}
3. Here employee Id is 6 in database. It is not 0006

**Comment by lakshithaorange** [comment]
@samanthajayasinghe do we need to change this? since both 0006 or 6 refers the same employee

**Comment by samanthajayasinghe** [comment]
@lakshithaorange as I understand 
employee id : 6 and employee code : 0006 

so it should return employee id, so it should return 6

**Comment by janakapk** [comment]
Currently it return 0006

**Expected**  : It should return 6
