### ISSUE TITLE
Settings for Content-Security-Policy (CSP) HTTP Header

### ISSUE THREAD

**Issue by 22phuber** [orangehrm/orangehrm#568]
Dear OrangeHRM Dev Team

Is there a "standard installation" [Content-Security-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy) settings you already use/recommend?

**Comment by RajithaKumara** [comment]
Hi @22phuber 
Currently (upto OrangeHRM 4.3.5), OrangeHRM require following CSP directives;

`<meta http-equiv="Content-Security-Policy" content="default-src 'self' 'unsafe-inline' 'unsafe-eval';img-src 'self' *.orangehrm.com data:;font-src 'self' data:;">`

But it's upto you to decide your CSP header.

**Comment by 22phuber** [comment]
Thx for the reply. I'll implement this since i've no other integration which could affect the CSP atm.
