### ISSUE TITLE
email service not working  when user apply for leave 

### ISSUE THREAD

**Issue by Ghost173** [orangehrm/orangehrm#570]
we are using open source orangehrm  but when user (employee) apply for leave but HR(admin) didnt revised any email like notification but that leave approved or reject user revised email  

how can i enable email services for everything ?
1.if user apply for lave hr and report to person should revised emails 
2. if any one comment on leave also need email alerts

**Comment by kavithagurusamy** [comment]
@Ghost173 
In your system, Have you enabled the email subscriptions and the users? This can be done via (Admin > Configuration > Email Subscriptions.)
 - You need to add the admins as subscribers for these events.

Supervisor / Employee will get alerted if their work email is configured.

Please note that only updating comment won't send any alert.

**Comment by reddimohan** [comment]
Hi,

I am using opensource of OrangeHRM 4.3.4, I am still not getting any emails after configuration.

- Configured Email Configuration and able to send Test mail using */sendmail option
- Under Email Subscription I have selected all options to trigger the when anything happens with Leave Module
- Created 2 users x and y and configured x reports to y in Direct method
- Configured Work email address as well

after all this configuration, Leave notification emails are not being sent.

Please find the below error log for more information.

`Mon 10 Feb 2020 03:53:16 PM IST,681 [24654] ERROR leave.LeaveApplicationService - Exception while saving leave:Doctrine_Record_UnknownPropertyException: Unknown record property / related component "sendmail_path" on "EmailConfiguration" in /var/www/html/orange/symfony/lib/vendor/lexpress/doctrine1/lib/Doctrine/Record/Filter/Standard.php:55
Stack trace:
#0 /var/www/html/orange/symfony/lib/vendor/lexpress/doctrine1/lib/Doctrine/Record.php(1394): Doctrine_Record_Filter_Standard->filterGet(Object(EmailConfiguration), 'sendmail_path')
#1 /var/www/html/orange/symfony/lib/vendor/lexpress/doctrine1/lib/Doctrine/Record.php(1349): Doctrine_Record->_get('sendmail_path', true)
#2 /var/www/html/orange/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php(185): Doctrine_Record->get('sendmail_path')
#3 /var/www/html/orange/symfony/plugins/orangehrmCorePlugin/lib/mail/orangehrmMailTransport.php(76): sfDoctrineRecord->__call('getSendmailPath', Array)
#4 /var/www/html/orange/symfony/apps/orangehrm/lib/model/core/Service/EmailService.php(135): orangehrmMailTransport->getTransport()
#5 /var/www/html/orange/symfony/apps/orangehrm/lib/model/core/Service/EmailService.php(497): EmailService->getMailer()
#6 /var/www/html/orange/symfony/plugins/orangehrmLeavePlugin/lib/mail/LeaveMailer.php(90): EmailService->sendEmailNotifications('leave.apply', Array, Array, 'ess')
#7 /var/www/html/orange/symfony/lib/vendor/symfony/lib/event/sfEventDispatcher.class.php(77): LeaveMailer->listen(Object(sfEvent))
#8 /var/www/html/orange/symfony/plugins/orangehrmLeavePlugin/lib/service/LeaveApplicationService.php(158): sfEventDispatcher->notify(Object(sfEvent))
#9 /var/www/html/orange/symfony/plugins/orangehrmLeavePlugin/lib/service/LeaveApplicationService.php(74): LeaveApplicationService->saveLeaveRequest(Object(LeaveParameterObject))
#10 /var/www/html/orange/symfony/plugins/orangehrmLeavePlugin/modules/leave/actions/applyLeaveAction.class.php(110): LeaveApplicationService->applyLeave(Object(LeaveParameterObject))
#11 /var/www/html/orange/symfony/cache/orangehrm/prod/config/config_core_compile.yml.php(967): applyLeaveAction->execute(Object(sfWebRequest))
#12 /var/www/html/orange/symfony/plugins/orangehrmCorePlugin/lib/filter/orangehrmExecutionFilter.php(42): sfExecutionFilter->executeAction(Object(applyLeaveAction))
#13 /var/www/html/orange/symfony/cache/orangehrm/prod/config/config_core_compile.yml.php(962): orangehrmExecutionFilter->executeAction(Object(applyLeaveAction))
#14 /var/www/html/orange/symfony/cache/orangehrm/prod/config/config_core_compile.yml.php(948): sfExecutionFilter->handleAction(Object(sfFilterChain), Object(applyLeaveAction))
#15 /var/www/html/orange/symfony/cache/orangehrm/prod/config/config_core_compile.yml.php(1044): sfExecutionFilter->execute(Object(sfFilterChain))
#16 /var/www/html/orange/symfony/lib/vendor/symfony/lib/filter/sfCommonFilter.class.php(29): sfFilterChain->execute()
#17 /var/www/html/orange/symfony/cache/orangehrm/prod/config/config_core_compile.yml.php(1044): sfCommonFilter->execute(Object(sfFilterChain))
#18 /var/www/html/orange/symfony/plugins/orangehrmCorePlugin/lib/filter/orangehrmPostExecutionFilter.php(22): sfFilterChain->execute()
#19 /var/www/html/orange/symfony/cache/orangehrm/prod/config/config_core_compile.yml.php(1044): orangehrmPostExecutionFilter->execute(Object(sfFilterChain))
#20 /var/www/html/orange/symfony/apps/orangehrm/lib/filter/ModuleFilter.php(56): sfFilterChain->execute()
#21 /var/www/html/orange/symfony/cache/orangehrm/prod/config/config_core_compile.yml.php(1044): ModuleFilter->execute(Object(sfFilterChain))
#22 /var/www/html/orange/symfony/plugins/orangehrmCorePlugin/lib/authorization/filter/ohrmAuthorizationFilter.php(101): sfFilterChain->execute()
#23 /var/www/html/orange/symfony/cache/orangehrm/prod/config/config_core_compile.yml.php(1044): ohrmAuthorizationFilter->execute(Object(sfFilterChain))
#24 /var/www/html/orange/symfony/apps/orangehrm/lib/filter/SessionInfoFetcherFilter.php(67): sfFilterChain->execute()
#25 /var/www/html/orange/symfony/cache/orangehrm/prod/config/config_core_compile.yml.php(1044): SessionInfoFetcherFilter->execute(Object(sfFilterChain))
#26 /var/www/html/orange/symfony/apps/orangehrm/lib/filter/OrangeI18NFilter.php(58): sfFilterChain->execute()
#27 /var/www/html/orange/symfony/cache/orangehrm/prod/config/config_core_compile.yml.php(1044): OrangeI18NFilter->execute(Object(sfFilterChain))
#28 /var/www/html/orange/symfony/apps/orangehrm/lib/filter/ExceptionCatcherFilter.php(26): sfFilterChain->execute()
#29 /var/www/html/orange/symfony/cache/orangehrm/prod/config/config_core_compile.yml.php(1044): ExceptionCatcherFilter->execute(Object(sfFilterChain))
#30 /var/www/html/orange/symfony/lib/vendor/symfony/lib/filter/sfBasicSecurityFilter.class.php(72): sfFilterChain->execute()
#31 /var/www/html/orange/symfony/cache/orangehrm/prod/config/config_core_compile.yml.php(1044): sfBasicSecurityFilter->execute(Object(sfFilterChain))
#32 /var/www/html/orange/symfony/cache/orangehrm/prod/config/config_core_compile.yml.php(1009): sfFilterChain->execute()
#33 /var/www/html/orange/symfony/cache/orangehrm/prod/config/config_core_compile.yml.php(1044): sfRenderingFilter->execute(Object(sfFilterChain))
#34 /var/www/html/orange/symfony/cache/orangehrm/prod/config/config_core_compile.yml.php(685): sfFilterChain->execute()
#35 /var/www/html/orange/symfony/cache/orangehrm/prod/config/config_core_compile.yml.php(2773): sfController->forward('leave', 'applyLeave')
#36 /var/www/html/orange/symfony/lib/vendor/symfony/lib/util/sfContext.class.php(179): sfFrontWebController->dispatch()
#37 /var/www/html/orange/symfony/web/index.php(22): sfContext->dispatch()
#38 {main}`
