### ISSUE TITLE
OrangeHRM 4.3.3 <-> Toggl integration

### ISSUE THREAD

**Issue by 22phuber** [orangehrm/orangehrm#573]
Dear OHRM Team

I try to get OrangeHRM syncing with toggl.com but it is only partial working.

OrangeHRM version: `4.3.3`
toggl.com Account:
- My account is on the free plan

**Status and what i tested so far:**
0. Installed the toggl.com addon from Marketplace

1. Check toggl.com account for Toggl API Token

2. Saved the token in OHRM: 
![Bildschirmfoto 2019-10-03 um 12 47 29](https://user-images.githubusercontent.com/17426101/66121152-c6a86000-e5dc-11e9-9632-8ee30f2af102.png)

3. Added projects in OHRM: 
![Bildschirmfoto 2019-10-03 um 12 58 35](https://user-images.githubusercontent.com/17426101/66121555-c5c3fe00-e5dd-11e9-9992-b2e3943d92a2.png)

4. Pressed the sync button in OHRM

5. Warning about the OrangeHRM Workspace --> added the needed OrangeHRM Workspace in toggl.com

6. Synced again: All projects are synced properly
![Bildschirmfoto 2019-10-03 um 12 59 01](https://user-images.githubusercontent.com/17426101/66121584-cf4d6600-e5dd-11e9-9abd-18f53d3a3d4b.png)

7. Logged some time for a OHRM project in toggl.
![Bildschirmfoto 2019-10-03 um 13 00 59](https://user-images.githubusercontent.com/17426101/66121614-e0967280-e5dd-11e9-9ebf-eafd89b7c6c7.png)

8. Synced again and got this message: 
![Bildschirmfoto 2019-10-03 um 12 47 11](https://user-images.githubusercontent.com/17426101/66121375-50582d80-e5dd-11e9-9dd0-33bd6b203aaf.png)

I tried several times to sync a logged time. I does not seem to work and i couldn't find anything relevant in the logs or web developer console.
I also tried with ativities and they get synced as well to toggl.

Did i miss a something?

**Comment by kavithagurusamy** [comment]
@22phuber 

Can you please create activities for the Project "P2"? 
Please sync once you created the activities, they will be added as tags in Toggl.
When you are tracking the time in Toggl please attach the tag.

In OrangeHRM timesheet records are tracked for activities in each project.

So your Toggl record should look like this, I have created "Documentation" as an activity for this project and selected that when tracking time in Toggl.
![Toggl](https://user-images.githubusercontent.com/25813012/66184657-85768580-e69a-11e9-9dec-61b1044b6762.png)

**Comment by 22phuber** [comment]
Hi @kavithagurusamy 

Thank you for the fast reply and explanation. As soon as i choose the activities it worked seamlessly!

**Comment by kavithagurusamy** [comment]
@22phuber 
Sharing the promotion flyer of the paid addons for this month. Please request through your system if you are interested.
![October flyer](https://user-images.githubusercontent.com/25813012/66306263-c67ecc00-e91e-11e9-8639-8cd180b3a8d9.jpg)
