### ISSUE TITLE
How can we upload the employee photographs in a bulk? Is there any folder or path where we can put the photos renamed with employee number or so? Any other method will also work.

### ISSUE THREAD

**Issue by arjun7208** [orangehrm/orangehrm#578]

**Comment by Damith88** [comment]
Hi Arjun,
This is not supported with OrangeHRM api. it only provides profile picture get requests.
OrangeHRM employee pictures are stored in database, not in file system.
You may write a custom script to achieve this.

**Comment by arjun7208** [comment]
Thank you Damith, I understood. Will try for the custom script.
Anyways you gyz are great!

Thanking you!


Warm Regards


Arjun Madhav

Software Assistant (IT Admin)

HILL SPRING INTERNATIONAL SCHOOL

M.P. Mills Compound,
B.B. Nakashe Marg,
Tardeo, Mumbai-400034

Tel - +91-22-2355 6201

Ext no - 185

Location: IBDP E-wing, 6th Flr, Publications Block.

________________________________
