### ISSUE TITLE
Warning message comes when applying a specific time leave 

### ISSUE THREAD

**Issue by NayanatharaJayaweera** [orangehrm/orangehrm#581]
A warning message displays as "Leave quota exceeded" when a user applies for leave by selecting the duration as "Specify Time" and if the duration is less than 3 hours leave request does not come to the leave list

**Comment by kavithagurusamy** [comment]
This will be fixed in 4.3.4 release which is due end of October.

https://github.com/orangehrm/orangehrm/pull/574

**Comment by kavithagurusamy** [comment]
Fixed in 4.3.4 release.
