### ISSUE TITLE
Activation of language new localization file

### ISSUE THREAD

**Issue by asimakos** [orangehrm/orangehrm#583]
I have installed successfully OrangeHRM 4.3.3 and i would like to add a new language localization xml file for greek that i have recently prepared. At the moment it comes bundled only with the most popular  languages of the world.

I have followed the steps mentioned in the forum

1. Add the file symfony/apps/orangehrm/i18n
2. After the language pack has been added, login to the OrangeHRM system and follow below steps to enable.
3. Admin module -> Configuration -> Localization -> Change the preferred language.

but unfortunately i can not find the added language in the localization drop down list via admin module to select and enable it. Any idea what steps I should follow?

Regards

**Comment by Damith88** [comment]
please add an entry to [supported_languages.yml](https://github.com/orangehrm/orangehrm/blob/master/symfony/plugins/orangehrmAdminPlugin/config/supported_languages.yml)

**Comment by asimakos** [comment]
I followed exactly all the instructions mentioned above and when i select the language from localization drop down,  i get only a flash message "Successfully saved!" and afterwards nothing happens (no menu translation etc). On the contrary when i select other languages, everything is translated. 

Any idea what is happening wrong?

![screen](https://user-images.githubusercontent.com/15226087/68089003-49873980-fe6d-11e9-9bf1-9b6169ff7453.png)

Regards

**Comment by RajithaKumara** [comment]
Hi @asimakos 
Did you create `messages.gr.xml` in `<path_to_orangehrm>/symfony/apps/orangehrm/i18n`. If you didn't create yet,  please refer annother language file in `<path_to_orangehrm>/symfony/apps/orangehrm/i18n`.

**Comment by asimakos** [comment]
I found on lines 3096 and 5634 two missing closing tags. After correcting both of them, my language file is ready for contribution to OrangeHRM.

Regards

**Comment by kavithagurusamy** [comment]
Asimakos
OrangeHRM 4.6 version is released with the feature that admin can do the translation or add new language package via the OrangeHRM system.
Please contact orangehrm support via ossupport@orangehrm.com if you are interested in contributing the language pack.

**Comment by joshuaveiga** [comment]
hi there
can sombody help me
I am tryng to translate to portuguese version but I can't, I am use 5.1 version
how to do it manually?

**Comment by jorluisperales** [comment]
> hi there can sombody help me I am tryng to translate to portuguese version but I can't, I am use 5.1 version how to do it manually?

Did you ever manage to do it?

**Comment by nunesjuao** [comment]
Alguém tem o XML de tradução para português Brasil?
