### ISSUE TITLE
Can't create users if the username is less than 5 characters 

### ISSUE THREAD

**Issue by NayanatharaJayaweera** [orangehrm/orangehrm#588]
Can't create the users if the username is less than 5 characters. A validation message displays as "Should have at least 5 characters"

Is it possible to remove this validation?

![username](https://user-images.githubusercontent.com/22584142/67557434-b21a3c00-f732-11e9-931f-07f1bf653683.png)

**Comment by Damith88** [comment]
This can be achieved by modyfying the code.
_symfony/plugins/orangehrmAdminPlugin/web/js/systemUserSuccess.js_ is the file you will have to edit.
you will find there is a constraint for length validation under validation rules in that file . 
`minlength: 5`
either change the value of that constraint or remove the constraint from rules.
then you will have to run the following command from _symfony_ directory.
`php symfony orangehrm:publish-assets`
