### ISSUE TITLE
Installation Freezes

### ISSUE THREAD

**Issue by matthew119427** [orangehrm/orangehrm#593]
Hi, I'm trying to install the software. I tried this on two completely different machines already both using 4.0 and 4.3.3 and they're both experiencing this issue. 
![image](https://user-images.githubusercontent.com/40540813/68094588-067a9580-fe70-11e9-8de1-7fd0e49819a1.png)
It literally freezes here, nothing happens afterwards. I'm unsure what to do now.
PHP version is 7.1 and using this on Nginx.

**Comment by RajithaKumara** [comment]
Hi @matthew119427 
Can you send log files which are located at `<path_to_orangehrm>/installer/log.txt` and if exists `<path_to_orangehrm>/installer/logInsatall.log` and `<path_to_orangehrm>/symfony/log/orangehrm.log`.

**Comment by matthew119427** [comment]
`installer/log.txt`
```txt
Client Info

User Agent : Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0
Remote Address : 24.149.102.127

Server Info

Host : 
PHP Version : 7.1.33-1+0~20191027.27+debian9~1.gbpd10139
Server : nginx/1.10.3
Document Root : /var/www/orangehrm
ROOT_PATH : /var/www/orangehrm

OrangeHRM Installation Log

Sun, 03 Nov 2019 19:13:51 -0500 DB Creation - Starting
Sun, 03 Nov 2019 19:13:51 -0500 DB Creation - Done
Sun, 03 Nov 2019 19:13:51 -0500 DB Creation - No Errors
Sun, 03 Nov 2019 19:13:54 -0500 Fill Data Phase 1 - Starting
Sun, 03 Nov 2019 19:13:54 -0500 Fill Data Phase 1 - Connected to the DB Server
Sun, 03 Nov 2019 19:13:54 -0500 Fill Data Phase 1 - Selected the DB
Sun, 03 Nov 2019 19:13:54 -0500 Fill Data Phase 1 - Reading DB Script
Sun, 03 Nov 2019 19:13:54 -0500 Fill Data Phase 1 - Opened DB Script
Sun, 03 Nov 2019 19:13:54 -0500 Fill Data Phase 1 - Read DB script
Sun, 03 Nov 2019 19:13:54 -0500 Fill Data Phase 1 - There are 288 Statements in the DB script
```
`installer/logInsatall.log`
```txt
2019-08-30 17:36:47 Installation successfully completed.
```
`symfony/log/orangehrm.log` does not exist.

**Comment by matthew119427** [comment]
`installer/log.txt`
```txt
Client Info

User Agent : Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0
Remote Address : 

Server Info

Host : 
PHP Version : 7.1.33-1+0~20191027.27+debian9~1.gbpd10139
Server : nginx/1.10.3
Document Root : /var/www/orangehrm
ROOT_PATH : /var/www/orangehrm

OrangeHRM Installation Log

Sun, 03 Nov 2019 19:13:51 -0500 DB Creation - Starting
Sun, 03 Nov 2019 19:13:51 -0500 DB Creation - Done
Sun, 03 Nov 2019 19:13:51 -0500 DB Creation - No Errors
Sun, 03 Nov 2019 19:13:54 -0500 Fill Data Phase 1 - Starting
Sun, 03 Nov 2019 19:13:54 -0500 Fill Data Phase 1 - Connected to the DB Server
Sun, 03 Nov 2019 19:13:54 -0500 Fill Data Phase 1 - Selected the DB
Sun, 03 Nov 2019 19:13:54 -0500 Fill Data Phase 1 - Reading DB Script
Sun, 03 Nov 2019 19:13:54 -0500 Fill Data Phase 1 - Opened DB Script
Sun, 03 Nov 2019 19:13:54 -0500 Fill Data Phase 1 - Read DB script
Sun, 03 Nov 2019 19:13:54 -0500 Fill Data Phase 1 - There are 288 Statements in the DB script
```
`installer/logInsatall.log`
```txt
2019-08-30 17:36:47 Installation successfully completed.
```
`symfony/log/orangehrm.log` does not exist.

*repost, forgot to delete the IP address in there.*

**Comment by RajithaKumara** [comment]
Hi @matthew119427 
What is your operating system and MySQL version?

**Comment by matthew119427** [comment]
Debian 9.11
10.1.41-MariaDB-0+deb9u1

**Comment by RajithaKumara** [comment]
According to the log, It should be successfully completed upto [here](https://github.com/orangehrm/orangehrm/blob/master/installer/ApplicationSetupUtility.php#L149).
Could you please write error log in `for loop` ([here](https://github.com/orangehrm/orangehrm/blob/master/installer/ApplicationSetupUtility.php#L152)) for you.
Before that, please check the database auto commit is enabled.

**Comment by matthew119427** [comment]
I know absolutely no PHP, my languages are JS and Python. How could I write the error log in that for loop and how can I check if the database auto commit is enabled?

**Comment by RajithaKumara** [comment]
Oh. I'm really sorry. Replace [this line](https://github.com/orangehrm/orangehrm/blob/master/installer/ApplicationSetupUtility.php#L152) by
```php
set_time_limit(30);
error_log (date("r")." Fill Data Phase $phase - Pending Statement # $c \n",3, self::getErrorLogPath());
error_log (date("r")." ".$dbScriptStatements[$c]."\n",3, self::getErrorLogPath());
```

Refer [this](https://mariadb.com/kb/en/library/server-system-variables/#autocommit) for check auto commit. Sorry for the inconvenience.

**Comment by matthew119427** [comment]
Okay, now it just directed me to a blank page.

**Comment by matthew119427** [comment]
I looked at the logs,
```INSERT INTO ohrm_user_role_screen (user_role_id, screen_id, can_read, can_create, can_update, can_delete) VALUES
(1, @oauth_client_screen_id, 1, 1, 1, 0)
Mon, 04 Nov 2019 16:10:12 -0500 MySQL Event Error:No database selected
Mon, 04 Nov 2019 16:10:12 -0500 Fill Data Phase 1 - Connected to the DB Server
Mon, 04 Nov 2019 16:10:13 -0500 Fill Data Phase 2 - Done
Mon, 04 Nov 2019 16:10:14 -0500 Fill Data Phase 2 - No Errors
Mon, 04 Nov 2019 16:10:14 -0500 Create DB user - Starting
Mon, 04 Nov 2019 16:10:14 -0500 Create DB user - Done
Mon, 04 Nov 2019 16:10:14 -0500 Create DB user - No Errors
Mon, 04 Nov 2019 16:10:14 -0500 Create OrangeHRM user - Starting
Mon, 04 Nov 2019 16:10:15 -0500 Create OrangeHRM user - Done
Mon, 04 Nov 2019 16:10:15 -0500 Create OrangeHRM user - No Errors
Mon, 04 Nov 2019 16:10:17 -0500 Write Conf - Starting
Mon, 04 Nov 2019 16:10:17 -0500 Write Conf - Done
Mon, 04 Nov 2019 16:10:17 -0500 Write Conf - No Errors
``` After a few minutes of installing, we're here now. It did say everything was successfully installed, however I'm attempting to get to the URL and I just keep getting **502 BAD GATEWAY** with no Nginx logs whatsoever.

**Comment by RajithaKumara** [comment]
Hi @matthew119427 
Did you resolve the issue?
You can refer [this comment](https://github.com/orangehrm/orangehrm/issues/608#issuecomment-595004856) to configure Nginx if the issue not yet resolved.

**Comment by diatoz** [comment]
This is still an issue with 4.6.0.1. Did anyone find the solution? I am seeing "GET /symfony/web/index.php/auth/symfony/web/index.php/auth/symfony/web/index.php/auth/symfony/web/index.php/auth/symfony/web/index.php/auth/symfony/web/index.php/auth/symfony/web/index.php/auth/symfony/web/index.php/auth/symfony/web/index.php/auth/symfony/web/index.php/auth/symfony/web/index.php/auth/symfony/web/index.php/auth/symfony/web/index.php/auth/symfony/web/index.php/auth/symfony/web/index.php/auth/symfony/web/index.php/auth/symfony/web/index.php/auth/symfony/web/index.php/auth/symfony/web/index.php/auth/symfony/web/index.php/auth/symfony/web/index.php/auth/symfony/web/index.php/auth/symfony/web/index.php/auth/symfony/web/index.php/auth/login" in nginx.

**Comment by samanthajayasinghe** [comment]
Hi @diatoz 
pls reopen the issue if it's exists on 4.10 latest version
