### ISSUE TITLE
sfConfig::get('ohrm_resource_dir') causes the problem

### ISSUE THREAD

**Issue by ndr-thitinan** [orangehrm/orangehrm#600]
sfConfig::get('ohrm_resource_dir') in many function will make the path error.

For example, 

- symfony/apps/orangehrm/modules/auth/templates/loginSuccess.php will make svg not working if sfConfig::get('ohrm_resource_dir') is right there.
- symfony/apps/orangehrm/lib/helper/OrangeHelper.php: theme_path, plugin_web_path will make the css, and images file path corrupted, and cannot be loaded with MIME something error.

I changed it to "", and it solves the problem.

OrangeHRM v.4.3.4

**Comment by Damith88** [comment]
hi @ndr-thitinan 
have you run `php symfony orangehrm:publish-assest` command?
the above config will be created after running that command.

**Comment by ndr-thitinan** [comment]
I ran it.

**Comment by Damith88** [comment]
ok. thanks for your feedback. we will look into this issue further.

**Comment by reddimohan** [comment]
> sfConfig::get('ohrm_resource_dir') in many function will make the path error.
> 
> For example,
> 
> * symfony/apps/orangehrm/modules/auth/templates/loginSuccess.php will make svg not working if sfConfig::get('ohrm_resource_dir') is right there.
> * symfony/apps/orangehrm/lib/helper/OrangeHelper.php: theme_path, plugin_web_path will make the css, and images file path corrupted, and cannot be loaded with MIME something error.
> 
> I changed it to "", and it solves the problem.
> 
> OrangeHRM v.4.3.4

This worked for me. Many Thanks.

**Comment by reddimohan** [comment]
> > sfConfig::get('ohrm_resource_dir') in many function will make the path error.
> > For example,
> > 
> > * symfony/apps/orangehrm/modules/auth/templates/loginSuccess.php will make svg not working if sfConfig::get('ohrm_resource_dir') is right there.
> > * symfony/apps/orangehrm/lib/helper/OrangeHelper.php: theme_path, plugin_web_path will make the css, and images file path corrupted, and cannot be loaded with MIME something error.
> > 
> > I changed it to "", and it solves the problem.
> > OrangeHRM v.4.3.4
> 
> This worked for me. Many Thanks.

This is not the right solution, we just have to generate the assets and others then everything will start working.

**Comment by ndr-thitinan** [comment]
> > > sfConfig::get('ohrm_resource_dir') in many function will make the path error.
> > > For example,
> > > 
> > > * symfony/apps/orangehrm/modules/auth/templates/loginSuccess.php will make svg not working if sfConfig::get('ohrm_resource_dir') is right there.
> > > * symfony/apps/orangehrm/lib/helper/OrangeHelper.php: theme_path, plugin_web_path will make the css, and images file path corrupted, and cannot be loaded with MIME something error.
> > > 
> > > I changed it to "", and it solves the problem.
> > > OrangeHRM v.4.3.4
> > 
> > 
> > This worked for me. Many Thanks.
> 
> This is not the right solution, we just have to generate the assets and others then everything will start working.

Would you mind sharing the right solution ?
I was just give the temporally solution. I tried php symfony orangehrm:publish-assest, but was not working.

Thanks.

**Comment by RajithaKumara** [comment]
Hi @ndr-thitinan 
Are you using OrangeHRM 4.3.4 from sourceforge releases or clone from this repository?

**Comment by ndr-thitinan** [comment]
@RajithaKumara I did use from sourceforge

**Comment by RajithaKumara** [comment]
Then you don't want to run `php symfony orangehrm:publish-assest`. How about OrangeHRM 4.3.4? Is it working in your environment?

**Comment by ndr-thitinan** [comment]
@RajithaKumara I was working only if I had source code modified.

**Comment by RajithaKumara** [comment]
Great. We'll further investigate this issue. Thanks @ndr-thitinan.

**Comment by RajithaKumara** [comment]
Hi @ndr-thitinan 
This issue seems to me as duplicates of #584 and #611. Any updates of this issue? Can you provide your environment details and `orangehrm.log` file which is in `<orangehrm>/symfony/log/` after removing sensitive data?

**Comment by ndr-thitinan** [comment]
Hi, @RajithaKumara 

I'm now working on the different project.
So, sorry, I cannot provide any more information.

The symptom is the same as #611 , and likely the same as #584 .

**Comment by kavithagurusamy** [comment]
Closing the ticket as no response from the reporter on the problem raised.
