### ISSUE TITLE
Quickstart guide points to non existing resource

### ISSUE THREAD

**Issue by unguul** [orangehrm/orangehrm#602]
The quickstart guide provided with the release of 4.3.4 has links which point to nowhere.

The *prerequisite for installing on Linux* results in 404 and *installing steps for Linux* takes you to a blank page.

**Comment by RajithaKumara** [comment]
Hi @unguul 
Thanks for reporting this issue. For now, you can use [OrangeHRM Opensource wiki](https://github.com/orangehrm/orangehrm/wiki). For the installation process use [this wiki page](https://github.com/orangehrm/orangehrm/wiki/Installation-Guide-(Web)). For more prerequisite requirements are mentioned [here](https://github.com/orangehrm/orangehrm/issues/360#issuecomment-428924316).

**Comment by kavithagurusamy** [comment]
Fixed in OrangeHRM 4.3.5
