### ISSUE TITLE
Allow Employee to file leave request

### ISSUE THREAD

**Issue by jacy** [orangehrm/orangehrm#608]
Isn't it a useful feature that employee able to file leave request seeking approval from his supervisor?

**Comment by Damith88** [comment]
This feature is already available in OrangeHRM product.

**Comment by jacy** [comment]
Ouch, let me check, thanks for the prompt reply.

**Comment by jacy** [comment]
Was struggling to deploy orangehrm-4.3.4 with Nginx into my local PC.  I have installed nginx with php and php-fpm with below nginx settings:

```
server {
                listen 2020;
                root /usr/local/var/www/orangehrm-4.3.4/;
                index  index.php index.html index.htm;
                client_max_body_size 100M;
                location / {
                        try_files $uri $uri/ /index.php?$uri&$args;
                }       
                location ~ \.php$ {
                        include fastcgi.conf;
                        fastcgi_pass 127.0.0.1:9000;
                        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                        include fastcgi_params;
                 }      
                location ~ /images/dummy.jpg {
                   deny all;
                }       
        
        }      
``` 

I was able to finish the web installer, but after that it was unable to login as getting below error:

_Too many redirects occurred trying to open “‎localhost:2020/symfony/web/index.php/auth/symfony/web/index.php/auth/symfony/web/index.php/auth/symfony/web/index.php/auth/symfony/web/index.php/auth/symfony/web/index.php/auth/symfony/web/index.php/auth/symfony/web/index.php/auth/symfony/web/index.php/auth/symfony/web/index.php/auth/symfony/web/index.php/auth/symfony/web/index.php/auth/symfony/web/index.php/auth/symfony/web/index.php/auth/symfony/web/index.php/auth/symfony/web/index.php/auth/login”._ 

Any one can shed lights on how to set it up with nginx as proxy?

**Comment by RajithaKumara** [comment]
Hi @jacy 
Did you resolve the actual issue, you were reported here?
You can refer our Nginx [server.conf](https://github.com/orangehrm/orangehrm-os-dev-environment/blob/master/server/nginx/config/server.conf) in [orangehrm-os-dev-environment repo](https://github.com/orangehrm/orangehrm-os-dev-environment) to more info :relaxed:.

**Comment by jacy** [comment]
@RajithaKumara, yes it is working now after apply the same config as your linked, thanks a lot for the help. Below is the config details just in case someone need it:

```
server {
                listen 2020;
                root /usr/local/var/www/orangehrm-4.3.4/;
                index  index.php index.html index.htm;
                client_max_body_size 100M;
                location / {
                        autoindex on;
                }
                location ~ [^/]\.php(/|$) {
                        fastcgi_split_path_info  ^(.+\.php)(/.+)$;
                        include /usr/local/etc/nginx/fastcgi_params;
                        fastcgi_pass  127.0.0.1:9000;
                        fastcgi_index index.php;
                        fastcgi_param SCRIPT_FILENAME $document_root/$fastcgi_script_name;
                        fastcgi_param PATH_INFO       $fastcgi_path_info;
                }
                location ~ /images/dummy.jpg {
                   deny all;
                }

        }
```

Will be now exploring the system 👍

**Comment by jacy** [comment]
confirmed ESS user able to Apply leaves, thanks all for the help, will close the issue.
