### ISSUE TITLE
Errors Upgrading from 3.3.2 to 4.3.4

### ISSUE THREAD

**Issue by JoGu01** [orangehrm/orangehrm#612]
Hello,

i am trying to upgrade from 3.3.2 to 4.3.4.
I already added some fixes to 4.3.4 found here: #595 
Still getting the following errors at 20% when Applying Database Changes:

```2020-Feb-28 14:37:05 : MySQL Error: Duplicate entry '0' for key 'PRIMARY'. 
Query: ALTER TABLE `hs_hr_emp_member_detail` ADD PRIMARY KEY(`id`);


StackTrace:#0 /var/www/html/orangehrm-4.3.4/upgrader/apps/upgrader/lib/utility/UpgradeUtility.php(61): UpgradeLogger::writeErrorMessage('2020-Feb-28 14:...', true)
#1 /var/www/html/orangehrm-4.3.4/upgrader/apps/upgrader/lib/schemaIncrementTasks/SchemaIncrementTask66.php(64): UpgradeUtility->executeSql('ALTER TABLE `hs...')
#2 /var/www/html/orangehrm-4.3.4/upgrader/apps/upgrader/modules/upgrade/actions/dbChangeControlAction.class.php(30): SchemaIncrementTask66->execute()
#3 /var/www/html/orangehrm-4.3.4/upgrader/cache/upgrader/prod/config/config_core_compile.yml.php(967): dbChangeControlAction->execute(Object(sfWebRequest))
#4 /var/www/html/orangehrm-4.3.4/upgrader/cache/upgrader/prod/config/config_core_compile.yml.php(962): sfExecutionFilter->executeAction(Object(dbChangeControlAction))
#5 /var/www/html/orangehrm-4.3.4/upgrader/cache/upgrader/prod/config/config_core_compile.yml.php(948): sfExecutionFilter->handleAction(Object(sfFilterChain), Object(dbChangeControlAction))
#6 /var/www/html/orangehrm-4.3.4/upgrader/cache/upgrader/prod/config/config_core_compile.yml.php(1044): sfExecutionFilter->execute(Object(sfFilterChain))
#7 /var/www/html/orangehrm-4.3.4/upgrader/apps/upgrader/lib/filter/ActionFilter.php(14): sfFilterChain->execute()
#8 /var/www/html/orangehrm-4.3.4/upgrader/cache/upgrader/prod/config/config_core_compile.yml.php(1044): ActionFilter->execute(Object(sfFilterChain))
#9 /var/www/html/orangehrm-4.3.4/upgrader/cache/upgrader/prod/config/config_core_compile.yml.php(1009): sfFilterChain->execute()
#10 /var/www/html/orangehrm-4.3.4/upgrader/cache/upgrader/prod/config/config_core_compile.yml.php(1044): sfRenderingFilter->execute(Object(sfFilterChain))
#11 /var/www/html/orangehrm-4.3.4/upgrader/cache/upgrader/prod/config/config_core_compile.yml.php(685): sfFilterChain->execute()
#12 /var/www/html/orangehrm-4.3.4/upgrader/cache/upgrader/prod/config/config_core_compile.yml.php(2773): sfController->forward('upgrade', 'dbChangeControl')
#13 /var/www/html/orangehrm-4.3.4/symfony/lib/vendor/symfony/lib/util/sfContext.class.php(179): sfFrontWebController->dispatch()
#14 /var/www/html/orangehrm-4.3.4/upgrader/web/index.php(13): sfContext->dispatch()
#15 {main}
2020-Feb-28 14:37:05 : MySQL Error: Incorrect table definition; there can be only one auto column and it must be defined as a key. 
Query: ALTER TABLE `hs_hr_emp_member_detail` MODIFY COLUMN id INT auto_increment;


StackTrace:#0 /var/www/html/orangehrm-4.3.4/upgrader/apps/upgrader/lib/utility/UpgradeUtility.php(61): UpgradeLogger::writeErrorMessage('2020-Feb-28 14:...', true)
#1 /var/www/html/orangehrm-4.3.4/upgrader/apps/upgrader/lib/schemaIncrementTasks/SchemaIncrementTask66.php(64): UpgradeUtility->executeSql('ALTER TABLE `hs...')
#2 /var/www/html/orangehrm-4.3.4/upgrader/apps/upgrader/modules/upgrade/actions/dbChangeControlAction.class.php(30): SchemaIncrementTask66->execute()
#3 /var/www/html/orangehrm-4.3.4/upgrader/cache/upgrader/prod/config/config_core_compile.yml.php(967): dbChangeControlAction->execute(Object(sfWebRequest))
#4 /var/www/html/orangehrm-4.3.4/upgrader/cache/upgrader/prod/config/config_core_compile.yml.php(962): sfExecutionFilter->executeAction(Object(dbChangeControlAction))
#5 /var/www/html/orangehrm-4.3.4/upgrader/cache/upgrader/prod/config/config_core_compile.yml.php(948): sfExecutionFilter->handleAction(Object(sfFilterChain), Object(dbChangeControlAction))
#6 /var/www/html/orangehrm-4.3.4/upgrader/cache/upgrader/prod/config/config_core_compile.yml.php(1044): sfExecutionFilter->execute(Object(sfFilterChain))
#7 /var/www/html/orangehrm-4.3.4/upgrader/apps/upgrader/lib/filter/ActionFilter.php(14): sfFilterChain->execute()
#8 /var/www/html/orangehrm-4.3.4/upgrader/cache/upgrader/prod/config/config_core_compile.yml.php(1044): ActionFilter->execute(Object(sfFilterChain))
#9 /var/www/html/orangehrm-4.3.4/upgrader/cache/upgrader/prod/config/config_core_compile.yml.php(1009): sfFilterChain->execute()
#10 /var/www/html/orangehrm-4.3.4/upgrader/cache/upgrader/prod/config/config_core_compile.yml.php(1044): sfRenderingFilter->execute(Object(sfFilterChain))
#11 /var/www/html/orangehrm-4.3.4/upgrader/cache/upgrader/prod/config/config_core_compile.yml.php(685): sfFilterChain->execute()
#12 /var/www/html/orangehrm-4.3.4/upgrader/cache/upgrader/prod/config/config_core_compile.yml.php(2773): sfController->forward('upgrade', 'dbChangeControl')
#13 /var/www/html/orangehrm-4.3.4/symfony/lib/vendor/symfony/lib/util/sfContext.class.php(179): sfFrontWebController->dispatch()
#14 /var/www/html/orangehrm-4.3.4/upgrader/web/index.php(13): sfContext->dispatch()
#15 {main}
```

My Config:

> Component | Status
> -- | --
> PHP version | OK (ver 7.0.33-0+deb9u7)
> MySQL Client | OK (ver mysqlnd 5.0.12-dev - 20150407 - $Id: b5c5906d452ec590732a93b051f3827e02749b83 $)
> MySQL Server | OK (ver 5.5.5-10.1.44-MariaDB-0+deb9u1)
> Web Server | OK (ver Apache/2.4.25 (Debian))
> MySQL InnoDB Support | Default
> Write Permissions for "lib/confs" | OK
> Write Permissions for "lib/logs" | OK
> Write Permissions for "symfony/config" | OK
> Write Permissions for "symfony/apps/orangehrm/config" | OK
> Write Permissions for "symfony/cache" | OK
> Write Permissions for "symfony/log" | OK
> Maximum Session Idle Time before Timeout | OK
> Register Globals turned-off | OK
> Memory allocated for PHP script | OK
> Web server allows .htaccess files | OK
> MySQL Event Scheduler status | Disabled. This is required for automatic leave status changes of Leave module.
> cURL status | Enabled
> SimpleXML status | Enabled
> Zip extension status | Enabled

Any hints on what to do?
Regards,
Jörg

**Comment by RajithaKumara** [comment]
Hi @JoGu01 
I tried to reproduce your issue on (Docker environment)
- PHP version - OK (ver 7.0.33)
- MySQL Client - OK (ver mysqlnd 5.0.12-dev - 20150407 - $Id: b5c5906d452ec590732a93b051f3827e02749b83 $)
- MySQL Server - OK (ver 5.5.5-10.1.44-MariaDB-1~bionic)
- Web Server - OK (ver nginx/1.13.12)

But unfortunately, I cannot reproduce it. Can I get the previous log line of the log file you provided? (above line of `Query: ALTER TABLE hs_hr_emp_member_detail ADD PRIMARY KEY(`id`);`).

You can try with [this patch](https://github.com/orangehrm/orangehrm/files/4281987/patch.txt) also. **Don't use this in production instance. Please backup your database when you are upgrading and adding patches.**

**Comment by JoGu01** [comment]
Hi @RajithaKumara 
The line is 
```
2020-Feb-28 15:06:45 : MySQL Error: Duplicate entry '0' for key 'PRIMARY'.
Query: ALTER TABLE `hs_hr_emp_member_detail` ADD PRIMARY KEY(`id`);
```

Will check the Patch tomorrow - we only have the production instance ..

**Comment by RajithaKumara** [comment]
Thank you for your support.

**Comment by JoGu01** [comment]
Hi,
the patch worked. I am on 4.3.4 now. 

Now we are facing the next Problem.
The Frontend does not show any Data that has non-ASCII-Characters (i think) like German Umlauts. (e.g. Jörg)
The Data is still present in the database but not displayed on the Frontend.
The DB-Servers Charachterset is  UTF-8 Unicode (utf8) 
The database seems to be latin1_swedish_ci
Most of the tables have utf8_general_ci
The following tables are on latin1_swedish_ci
```
abstract_display_field
ohrm_employee_event
ohrm_oauth_access_token
ohrm_oauth_authorization_code
ohrm_oauth_client
ohrm_oauth_refresh_token
ohrm_oauth_user
ohrm_work_week
```
Are these settings correct?
Anything i can do about this problem?

Regards,
Jörg

**Comment by RajithaKumara** [comment]
Oops. Settings are okay. But is there special characters in your data? e.g. like ö in Jörg :relaxed:

**Comment by JoGu01** [comment]
Yes, unfortunately there is an ö in Jörg and the bigger problem is that there are more of these umlauts among the colleagues. 😢

**Comment by RajithaKumara** [comment]
Sorry for the inconvenience. Can you try this configuration.

Steps:
1. Open `<orangehrm-4.3.4>/symfony/config/databases.yml`
2. You can find bellow section in `databases.yml` file. (field values may change depending on your database connection)
```yaml
all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=127.0.0.1;port=3306;dbname=orangehrm_v4_3_4'
      username: <username>
      password: <password>
      attributes: { export: tables }
```

3. Modify it like below. Append only `;charset=utf8mb4` at the end of `dsn` line but before `'` :relaxed: 
```yaml
all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=127.0.0.1;port=3306;dbname=orangehrm_v4_3_4;charset=utf8mb4'
      ...
```
4. Finally clear symfony cache. You can do it by executing `php symfony cc` within the `<orangehrm-4.3.4>/symfony` directory **or** by manually deleting directories within `<orangehrm-4.3.4>/symfony/cache/` but **don't delete** `<orangehrm-4.3.4>/symfony/cache` **directory.**

**Comment by JoGu01** [comment]
Yay, I have a first name again.
It all seems to be working just fine now.
Thanks for the support.
Greetings,
Jörg
