### ISSUE TITLE
[Bug - Save/Update Contact Detail] : It is possible to add duplicate email address for email and other email in Contact Detail  

### ISSUE THREAD

**Issue by janakapk** [orangehrm/orangehrm#63]
It is possible to add duplicate email address for email and other email in Contact Detail  

1.Employee A email a@a.com
2.Add employee b email as a@a.com
3.It allow to save

**Comment by janakapk** [comment]
Scenario : 01
1.The fix is not enough. Save contact details issue is in same.
##########
Scenario : 02
1.Employee A work email = a@a.com and b@b.com
2.Should be able to update the employee A as work email = a@a.com and b@b.com

Scenario : 03
1.Once fixed the issue please see the possible scenario from the shared sheet https://docs.google.com/spreadsheets/d/1kpHywG8rp0CKTykGuIGcq04YsAWJKkCF83OG6zOGELw/edit#gid=1131064481

**Comment by janakapk** [comment]
Anyway two employee can't have same email. Please see possible cases when fixing

**Comment by lakshithaorange** [comment]
when adding same email for two employees it gives "{"error":["Work Email Exists"]}"  , I think you even verified this issue before releasing the last build , please verify !
