### ISSUE TITLE
[Bug - Get Employee Detail] : Supervisor Id,Code and reportingMethod  are not showing correctly

### ISSUE THREAD

**Issue by janakapk** [orangehrm/orangehrm#64]
[Bug - Get Employee Detail] : Supervisor Id,Code and reportingMethod  are not showing correctly

1.See the employee detail 
2.Supervisor section shows as bellow 
supervisor": [
      {
        "name": "Janaka Pushpa Kumara",
        "id": "0001",
        "code": "",
        "reportingMethod": ""
3.Id values is incorrect and code and reportingMethod are blank

**Comment by lakshithaorange** [comment]
its showing currently in mine 
  "data": [
    {
      "name": "Hameesh Von Johnson",
      "id": "2",
      "code": "1021",
      "reportingMethod": "Direct"
    }

will check where any defects

**Comment by janakapk** [comment]
Now it's working fine
