### ISSUE TITLE
How to write a new plugin and integrate with OrangeHRM (OpenSource Version)

### ISSUE THREAD

**Issue by vantinhuynh** [orangehrm/orangehrm#655]
**Is your feature request related to a problem? Please describe.**
I want to write a new plugin and integrate it with OrangeHRM (OpenSource Version), How can I do that? Do you have any documents/Guidelines for this?

Example: I want to write "Customize User Roles"

**Describe the solution you'd like**
Please describe the desired behavior.

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.

**Comment by SalouaSahnoun** [comment]
Hello, 
i have the same issue, do you have an answer now?

**Comment by tecnomaster** [comment]
Hi fellows,

I would like to develop new plugins for OrangeHRM, however, I ca'nt find the guide on how to create plugins for 5.X version. Could you please help me on the roadmap for that?

Waiting for your very appreciated support.

Dan
