### ISSUE TITLE
Error while installing [autoload.php file is missing]

### ISSUE THREAD

**Issue by hahmad92** [orangehrm/orangehrm#657]
**Environment details**
OrangeHRM version: OrangeHRM 4.4
OrangeHRM source: Release build from [Sourceforge](https://sourceforge.net/projects/orangehrm) or Git clone
Platform: 64-bit (Windows)
PHP version: PHP 5.2.0
Database and version: [e.g. MySQL 5.7, MariaDB 10.2]
Web server: [e.g. Apache 2.4, Nginx 1.4]
Browser: Chrome

**Describe the bug**
I am getting following error while running installer.

Warning: require(): Filename cannot be empty in D:\server\xampp\htdocs\orangehrm-master\installer\environmentCheck\SystemValidator.php on line 22

Fatal error: require(): Failed opening required '' (include_path='D:\server\xampp\php\PEAR') in D:\server\xampp\htdocs\orangehrm-master\installer\environmentCheck\SystemValidator.php on line 22

**To Reproduce**
Just run the installer when error is produced on system check tab.

**Expected behaviour**
Installer should have run successfully.

**What do you see instead:**
Warning: require(): Filename cannot be empty in D:\server\xampp\htdocs\orangehrm-master\installer\environmentCheck\SystemValidator.php on line 22

Fatal error: require(): Failed opening required '' (include_path='D:\server\xampp\php\PEAR') in D:\server\xampp\htdocs\orangehrm-master\installer\environmentCheck\SystemValidator.php on line 22

If issue related to installation:
SystemValidator.php file is missing from the downloaded zip

**Comment by RajithaKumara** [comment]
Hi @hammadawan50 

Can you update if this issue is duplicate of  #514 or #437?

**Comment by lmidiap** [comment]
Hello this error doesn't appear when you download the zip file for Linux BUT appear when you use the git clone
