### ISSUE TITLE
I got stuck on the "System Check" tab during installation

### ISSUE THREAD

**Issue by Louknows-leadgen** [orangehrm/orangehrm#660]
**Environment details**
OrangeHRM version: **OrangeHRM 4.4**

OrangeHRM source: Release build from https://github.com/orangehrm/orangehrm

Platform: **GNU/Linux**

PHP version: **PHP 5.5.14**

Database and version:  **10.1.6-MariaDB-log - openSUSE package**

Web server: **Apache/2.4.20 (Linux/SUSE)**

**Describe the bug**
 I got stuck with the "System Check" tab of the installer. See link below for the screenshot:
https://i.stack.imgur.com/XFDYc.png

**To Reproduce**
1.) Clone the the repository in your server:
https://github.com/orangehrm/orangehrm.git

2.) Open the URL of your server and navigate to the folder where the repository is cloned.

3.) Click Next on the welcome screen. Then click "I Accept" in License Acceptance.

**Expected behavior**
The System check view should show after clicking the "I Accept" button on the License Acceptance view.

**What do you see instead:**
Empty view. When I tap developers tools, it shows an **Internal Server Error**. The error is in **installerUI.php**. I provided the screenshot on the description and screenshot area. I tried to troubleshoot, and though the error is in installerUI.php, by testing all the require statement, I always get the "Internal Server Error" on the developers tool whenever this line of code in **SystemValidator.php** is present
`require realpath(__DIR__ . "/../../symfony/lib/vendor/autoload.php");`

If issue related to installation:
- log.txt and logInsatall.log were not found inside installer folder

**Screenshots**
https://i.stack.imgur.com/XFDYc.png

**Additional context**
Refer on the "What do you see instead" area. I placed all the details I found so far there.

**Comment by RajithaKumara** [comment]
Hi @Louknows-leadgen 
Can you refer #657 and update here?
Also, OrangeHRM 4.4 not support for PHP 5.5.14

**Comment by Louknows-leadgen** [comment]
I thought it supports PHP greater than 5.3.0 as per on the wiki
https://github.com/orangehrm/orangehrm/wiki/Getting-started

![image](https://user-images.githubusercontent.com/58867348/85890057-34f21a00-b81f-11ea-8a27-62a664d9a95a.png)

**Comment by Louknows-leadgen** [comment]
what PHP version does this support?

**Comment by RajithaKumara** [comment]
Oops. Thanks for raising. We will update the wiki.
Current OrangeHRM 4.4 supporting versions;
**PHP**;
min: 7.0
max: 7.3.17

**MySQL**:
min: 5.5
max: 5.7.30

**MariaDB**:
min: 5.5
max: 10.4.13

**Comment by Louknows-leadgen** [comment]
ok thanks. We'll try to deploy it in an environment with that specs. Also, I have a question. The solution provided on this link
https://github.com/orangehrm/orangehrm/wiki/Development

is to update the composer dependencies. But in my local machine running with XAMPP (Windows), I was not required to do it, but the app runs smoothly.

**Comment by RajithaKumara** [comment]
Please note that this repo contain OrangeHRM source code. If you need to add more features, then you can clone this repo and follow the development guide. But if you want production (release) build you have to download ZIP file from https://sourceforge.net/projects/orangehrm/ or  https://github.com/orangehrm/orangehrm/releases 

And OrangeHRM Open source has two installers, EXE and web installer. If you use EXE (https://github.com/orangehrm/orangehrm/wiki/Installation-Guide--EXE) you don't want any environment setup. Since it installs XAMPP

**Comment by Louknows-leadgen** [comment]
The contents on the zip file of the stable release is just the same with the one on the github repository. What I didn't understand is that, why is it working smoothly (without any configuration) when I use XAMPP, but if run on an actual server with MySQL and PHP, I got this problem.

Now, I tried running this on a server which has the same MySQL version and PHP version of XAMPP, but still got this error.

**Comment by RajithaKumara** [comment]
There are two main changes with this repo, and release ZIP file.
- release contain composer dependencies at `symfony/lib/vendor`
- public assets such as js, css at `symfony/web`

**Comment by githubhair** [comment]
I am running on a mac OS Catalina. I have installed MAMP 5.7. 
I went through the same steps as those mentioned in this bug and I'm seeing the same results (blank screen on the "System Check" tab.
![image](https://user-images.githubusercontent.com/61896772/87602641-98e85f80-c6b4-11ea-8055-fe8343de3771.png)
Seeing the same 500 error 
Any ideas?

**Comment by tolu-six** [comment]
MySQL version on my server is a 5.7.31 and at this stage, I can't do anything because the database is not supprted with all orangeHRM version.

**Comment by RajithaKumara** [comment]
> I went through the similar steps as those mentioned in this bug and I'm seeing the same results (blank screen on the "System Check" tab.
> Seeing the same 500 error
> Any ideas?

Hi
What is your MAMP PHP version? If it 7.4.x version, can you try switching it to 7.3 or lower?

**Comment by RajithaKumara** [comment]
> MySQL version on my server is a 5.7.31 and at this stage, I can't do anything because the database is not supprted with all orangeHRM version.

Can you check #490 and patch your code.

**Comment by tolu-six** [comment]
I have been able to fix the issue by using a lower version of Mysql, since the current version says I should have 5.7.30 but my version of sql is 5.7.31.
Now a new issue, the server uses PHP version 5.6.40 which meets the requirements but I still get syntax error in EmployeeSubscription, line 36 and others with that syntax

**Comment by RajithaKumara** [comment]
@tolu-six What is your OrangeHRM version? Did you successfully installed? If you are using latest OrangeHRM (4.4) you have to setup environment according to https://github.com/orangehrm/orangehrm/issues/660#issuecomment-650336875 version ranges. 4.4 does not support on PHP 5.6.

**Comment by tolu-six** [comment]
I installed a v4.4

**Comment by tolu-six** [comment]
How do we fix the issue of v4.4 not compatible with mysql 5.7.31?

**Comment by RajithaKumara** [comment]
Oops. OrangeHRM 4.4 support PHP 7.0 - 7.3.17

**Comment by RajithaKumara** [comment]
> How do we fix the issue of v4.4 not compatible with mysql 5.7.31?
> Other applications on my server uses the mysql version, so I can’t think of downgrading

Replace 5.7.30 to 5.7.31 [here](https://github.com/orangehrm/orangehrm/blob/master/installer/environmentCheck/system_requirements.yml#L8) in `<orangehrm_root>/installer/environmentCheck/system_requirements.yml`.

**Comment by tolu-six** [comment]
Thanks. It worked

**Comment by apmuthu** [comment]
Just installed OrangeHRM v4.4 on WinXP SP3 with PHP 5.4.
Can Login,
Can change first password.
Installation screenshots attached.
Dashboard does not display thereafter as PHP 7.x's function return values are used and these are not compatible for backporting unless the strict_types declaration and related return types are removed.

[OrangeHRM_4.4_On_PHP_5.4.zip](https://github.com/orangehrm/orangehrm/files/5136390/OrangeHRM_4.4_On_PHP_5.4.zip)

2020-08-27

Platform: WinXP SP3 / XAMPP 1.8.2.5 / PHP 5.4 / MySQL 5
Download [password hash compatibility file](https://raw.githubusercontent.com/ircmaxell/password_compat/master/lib/password.php)
Errors are in `symfony/log/orangehrm.log`

Changed Files for successful install and initial login and first password change:

````
installer/environmentCheck/system_requirements.yml
    Line 2: min: '7.0' => min: '5.3'

installer/SystemConfiguration.php
    Added as first 2 lines for password compatibility:
    // https://github.com/ircmaxell/password_compat/blob/master/lib/password.php
    require_once(realpath(dirname(__FILE__)) . '/../symfony/plugins/orangehrmCorePlugin/lib/utility/password.php');

symfony/plugins/orangehrmCorePlugin/lib/utility/PasswordHash.php
    Added as first 2 lines for password compatibility:
    // https://github.com/ircmaxell/password_compat/blob/master/lib/password.php
    require_once ROOT_PATH.'/symfony/plugins/orangehrmCorePlugin/lib/utility/password.php';

symfony/lib/vendor/myclabs/deep-copy/src/DeepCopy/deep_copy.php
    Reverted to code as of DeepCopy v1.8.1 retaining only the namespace line and the function definition

symfony/apps/orangehrm/lib/utility/myUser.class.php
    Lines 161, 162 changed to place the function call output  as a variable and then using it by making them as:
        $x = $this->getEmployeeNumber();
        return empty($x) || $subscriptionService->isSubscribed($x);

symfony/plugins/orangehrmPimPlugin/lib/dao/EmployeeDao.php
    Lines 2329 to 2340 (reason same as above) made as:
            $x = $empDependent->getName();
            if(!empty($x)){
                $dependent->name = $x;
            }
            $x = $empDependent->getRelationship();
            if(!empty($x)){
                $dependent->relationship = $x;
            }
            $x = $empDependent->getDateOfBirth();
            if(!empty($x)){
                $dependent->date_of_birth = $x;
            }

symfony/plugins/orangehrmPimPlugin/lib/service/EmployeeSubscriptionService.php
    Beyond redemption as the new PHP 7 strict_types declared for function return types
    // https://www.tutorialspoint.com/php7/php7_returntype_declarations.htm
    // https://www.php.net/manual/en/functions.returning-values.php
    This prevents display of dashboard after installation and login and first password cahnge
````

**Comment by RajithaKumara** [comment]
Hi @apmuthu 
We are not encouraged to use PHP versions early 7.0 with OrangeHRM 4.4.
OrangeHRM 4.5 out there, check it out :relaxed:

**Comment by apmuthu** [comment]
Thankyou for stating that you are "not encouraged to use PHP versions early 7.0 with OrangeHRM 4.4". Try to fathom if venture capitalists / upstream dictates or just userbase churn for update services dictated such a decision.

A note to state the last version compatibility for pre PHP 7 versions would be in order in the Readme file. The new constructs used in the newer OrangeHRM versions should also be listed for ease of backporting and maintaining function compatible versions by others.

Since all OSes are now using the latest versions of PHP as driven by PHP owners (Oracle), most applications are forced to become usable in such platforms.

PHP drew a large userbase due to it being a loosely typed language with licence to mix variable types. That has now disappeared with corporate ownership that stresses on `declare(strict_types=1);`

To the extent possible it would be wise to retain backwards compatibility - capability to backport it to older platforms will help retain long term users without having to get into the "latest and greatest bigger version numbers" which does not necessarily translate to any great worthwhile end user gains except being harrassed by "consultants".

**Comment by kavithagurusamy** [comment]
Question in the ticket is addressed.
