### ISSUE TITLE
Unable to Login as Admin ORange HRM

### ISSUE THREAD

**Issue by tjudayasankar** [orangehrm/orangehrm#664]
Hello,

I have downloaded OrangeHRM 4.4 from Source Forge. Accidentally I have changed the Admin user role to Ess. I had created only one Admin account. How can I create a new admin account. Is there any way to create a new admin user.

**Comment by RajithaKumara** [comment]
Hi
You can restore Admin user by running below query in your OrangeHRM database. Assuming your admin user name `Admin`
```sql
UPDATE `ohrm_user` SET `user_role_id`=1 WHERE `user_name`="Admin";
```

**Comment by tjudayasankar** [comment]
Thank you @RajithaKumara but I am unable to find ohrm_user or hs_hr_user.

**Comment by RajithaKumara** [comment]
Did you select the OrangeHRM database before run update query.

**Comment by tjudayasankar** [comment]
Thank you @RajithaKumara I have used the following query. But still receiving the error. Please can you help me out. I apologize if it is going to be a simple syntax error.

`SELECT ohrm_user
UPDATE 'ohrm_user' SET 'user_role_id'=1 'user_name'="Admin";`

Error
Static analysis:

1 errors were found during analysis.

A new statement was found, but no delimiter between it and the previous one. (near "UPDATE" at position 18)
SQL query: Copy Documentation

SELECT ohrm_user UPDATE 'ohrm_user' SET 'user_role_id'=1 WHERE 'user_name'="Admin"
 
MySQL said: Documentation

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'UPDATE 'ohrm_user' SET 'user_role_id'=1 WHERE 'user_name'="Admin"' at line 2

**Comment by tjudayasankar** [comment]
Thank you @RajithaKumara . But this is the error that I receive when I try to execute the code.

`SELECT ohrm_user;
UPDATE 'ohrm_user' SET 'user_role_id'=1 WHERE 'user_name'="Admin";

Error
SQL query: Copy Documentation


SELECT ohrm_user
MySQL said: Documentation

#1054 - Unknown column 'ohrm_user' in 'field list'`

**Comment by RajithaKumara** [comment]
Oo. Actually I don't know your OrangeHRM database. But you can find it by running below queries in your database server.
```sql
SHOW DATABASES;
```
Guess OrangeHRM database from the database list and run below command to select database :smiley: . Let say database name `orangehrm_mysql`
```sql
USE `orangehrm_mysql`;
```
Now you can check whatever the selected database is OrangeHRM one.
```sql
SHOW TABLES;
#or
SHOW TABLES LIKE 'ohrm_user';
```
If you got result for above query, you are ready to run update query.
```sql
UPDATE `ohrm_user` SET `user_role_id`=1 WHERE `user_name`="Admin";
```

**Comment by tjudayasankar** [comment]
Thank you @RajithaKumara . Since I am using phpmyadmin I thought all my tables and databases are open to my naked eye. I was lazy enough that I did not download mysql.  I will download it and work on it and will get back to you. 

Or is there a way to solve it using phpmyadmin?
Please ignore my ignorance I am new to phpmyadmin, mysql and orangehrm but I am working on it.

Thank you,
Tharun

**Comment by RajithaKumara** [comment]
![orangehrm_664](https://user-images.githubusercontent.com/25487187/87548614-60538080-c6ca-11ea-9dce-7fe1e9b3b0f9.png)

1. Select database (click on +)
2. Search `ohrm_user` table
3. Click on `ohrm_user`
4. Double click on `user_role_id` column, `Admin` row and update value as 1

**Comment by SviatoslavBordovski** [comment]
Can someone just set the correct credentials on the frontend?
I am making the the opensource project to demonstrate on the bootcamp and tests are failing now because of this issue.

**Comment by SviatoslavBordovski** [comment]
FYI, valid username is **admin** now

**Comment by RajithaKumara** [comment]
> Can someone just set the correct credentials on the frontend?

You can use Fogot password option at the login screen. But that feature required valid email configuration to send reset password email.

**Comment by tjudayasankar** [comment]
Perfect @RajithaKumara it worked. Thank you.
