### ISSUE TITLE
Create two organization

### ISSUE THREAD

**Issue by tjudayasankar** [orangehrm/orangehrm#666]
Hello,

I am using orangeHRM through XAMPP where I am accessing it through localhost. 

I have already created one organization 'X' in my orangeHRM and added its employees. Now I need to add another organization and add few employees in the same HRM. Basically I need my hrm to handle two organization. Is it possible?

Thank you,
Tharun

**Comment by kavithagurusamy** [comment]
Hi 
In opensource only support to add employees in one country. Do you want to create another country if so you need to use the OrangeHRM enterprise version? 
You can add multiple locations in opensource and add employees to that if it's under the same country.
If you are referring for two organisations then you need to have two instances.

**Comment by tjudayasankar** [comment]
Hi @kavithagurusamy , thank you for replying. I am running two organizations in the same location (in the same city) with two different names. I wanted to use OrangeHRM to manage both the organization.

if I login using AdminA I should manage CompanyA
if I login using AdminB I should manage CompanyB

**Comment by tjudayasankar** [comment]
I have sorted out a way for it.

Thank you,
Tharun
