### ISSUE TITLE
Change URL and Port orangeHRM

### ISSUE THREAD

**Issue by nguyennv94** [orangehrm/orangehrm#670]
I'm using Orange HRM version: 6.5.12. want to change url defautl from https://ip_local to https://ip_local/orange
And change port 80, 443 (Apache ver 2.4.6 )

Thanks,

**Comment by kavithagurusamy** [comment]
Hi,

You are using the Enterprise version for OrangeHRM. Can you please send your query to support@orangehrm.com, One of our support engineers will assist you on this.

github is mainly focused on opensource users and the solutions are different for enterprise to OS.
