### ISSUE TITLE
Leave Lapse Feature

### ISSUE THREAD

**Issue by tjudayasankar** [orangehrm/orangehrm#671]
Hi,
My employees are entitled to take one day casual leave every month. But they cannot carry their unused leaves to the next month. Basically I wanted to lapse the casual leaves of my employees every month. 
i.e a leave should be generated for the month of September on 1st and it should lapse on 31st of September.

Please can you let me know if it is possible to do such things in OrangeHRM. 
Is it possible to write a scheduled stored procedure query?
Thank you,
Tharun

**Comment by kavithagurusamy** [comment]
Hi Tharun

This feature is not available in opensource version. Please contact the sales to check on the customisation via sales@orangehrm.com 

Regards
Kavitha
