### ISSUE TITLE
[Bug - Update Employee] : Following fields are not updating

### ISSUE THREAD

**Issue by janakapk** [orangehrm/orangehrm#68]
[Bug - Update Employee] : Following fields are not updating

otherId
driversLicenseNumber
licenseExpiryDare

**Comment by lakshithaorange** [comment]
there is a bug in the system , sometimes you have to re-search the employee list and check

**Comment by janakapk** [comment]
Still issue is there.

**Comment by lakshithaorange** [comment]
driversLicenseNumber "100100",
licenseExpiryDate "2018-05-24",
otherId  "23423",

its working properly , if you checking the updated results from the system , you have to re search and check, anyway this is the updated results I got !


  "data": {
    "firstName": "Ninatttttt",
    "middleName": "Jane",
    "lastName": "Lewis",
    "code": "1021",
    "employeeId": "3",
    "fullName": "Ninatttttt Jane Lewis",
    "status": null,
    "dob": "2016-05-04",
    "driversLicenseNumber": "100100",
    "licenseExpiryDate": "2018-05-24",
    "maritalStatus": "Other",
    "gender": "Female",
    "otherId": "23423",
    "nationality": "Afghan",
    "unit": null,
    "jobTitle": null,
    "supervisor": null
  }

@janakapk can you share your postman test case ?
