### ISSUE TITLE
Cannot able to login into my android app " it is saying Route Not Found" Contact system administrator

### ISSUE THREAD

**Issue by kavarthapu** [orangehrm/orangehrm#683]
Hi,

@RajithaKumara @Thulana  can you please help me out to resolve this .

I have installed orangehrm 4.5 I my hosted VPS by manually copying the zip file into my public html folder.

I finished my installation and can able to run the application on web without issues.

But while I'm try to access the same from the orangeopensource android app it was saying route not found after logging in and no data is being loaded inside the app.

My URL : 
https://sub.maindomain.com/symfony/web/index.php/auth/login - it is working on web but in mobile it was not working. Below URL was working on my mobile URL instance: 
https://sub.domain.com/symfony/web don't know why ! But it is strange.

Can some one tell me how can I fix this route issue !! Plz ! 

Tried to pullout the code from were the mobile app loading but failed to fair it !

Attaching the images below for the reference.
![Screenshot_2020-09-12-03-24-34-12_161838fdd16d6efc0a6ab51f927dd37f](https://user-images.githubusercontent.com/2521615/93014997-43a4cd80-f5d3-11ea-92f6-56f110c64548.jpg)
![Screenshot_2020-09-12-03-24-43-75_161838fdd16d6efc0a6ab51f927dd37f](https://user-images.githubusercontent.com/2521615/93015001-469fbe00-f5d3-11ea-8d29-002c1a45faf0.jpg)

Note : I have created an sub domain to my main domain and using this application.

**Comment by RajithaKumara** [comment]
Hi @kavarthapu 
This error shows when app failed to JSON Parse the response. Maybe the route not found. Can you try clearing the web application cache.

Cache clear in OrangeHRM 4.5
```
cd <into codebase root directory>
```
```
cd symfony
```
```
php symfony cc
```

**Comment by kavarthapu** [comment]
Hi @RajithaKumara 

Thanks for your response I have done the steps.


But still I'm having the same issue.

![Screenshot_2020-09-14-11-02-19-07_161838fdd16d6efc0a6ab51f927dd37f](https://user-images.githubusercontent.com/2521615/93047343-edd73080-f679-11ea-91a9-9a8c8b3f017a.jpg)
.
![Screenshot_2020-09-14-11-02-25-15_161838fdd16d6efc0a6ab51f927dd37f](https://user-images.githubusercontent.com/2521615/93047339-ea43a980-f679-11ea-886d-26b33286839d.jpg)

**Comment by kavarthapu** [comment]
After the default installation the webpage was loading in http mode not in the Https . So I have added the rewrite to https in it . Is it causing the issue by my chance ? 
But the mobile app requires only https right! 
But if I try with your URL it is working fine ! 
My VPS was hosted on GoDaddy with cent os7 on it ! 

Please help me out to resolve the issue !  @RajithaKumara

**Comment by kavithagurusamy** [comment]
Hi Kavarthapu

Mobile app requires to have the instance with https. Does your login user has an employee assigned? Can you please get the screenshot of user navigator screen and confirm? It seems to be the login user you are trying is not having an employee added.
Can you add a new user account with an employee assigned and access the mobile app.

Please send out an email to ossupport@orangehrm.com if you couldn't resolve the issue.

**Comment by kavarthapu** [comment]
> Hi Kavarthapu
> 
> Mobile app requires to have the instance with https. Does your login user has an employee assigned? Can you please get the screenshot of user navigator screen and confirm? It seems to be the login user you are trying is not having an employee added.
> Can you add a new user account with an employee assigned and access the mobile app.
> 
> Please send out an email to [ossupport@orangehrm.com](mailto:ossupport@orangehrm.com) if you couldn't resolve the issue.

Hi @kavithagurusamy  @RajithaKumara  as said above I have added one employee and to the main user account but still I'm having the same issue ! Is there any specific ports required to be unblocked to make this work ? If have any document how to create an first employee can you share it with me.
Thanks in advance .

**Comment by RajithaKumara** [comment]
Hi @kavarthapu 
If you did some server changes after logged into the mobile app, please Logout and re-login to the mobile app. Since any changes of the server configuration lead to mobile app couldn't found the OrangeHRM APIs.
E.g. You logged into mobile and change some htaccess  configs

Also, can you check `orangehrm.log` which located at `<orangehrm-4.5>/symfony/log/`.

**Comment by kavithagurusamy** [comment]
Closing this ticket as it's forwarded via orangehrm opensource support channel.
