### ISSUE TITLE
[Bug - Save/ Update dependent] - Dependent type is not saving

### ISSUE THREAD

**Issue by janakapk** [orangehrm/orangehrm#69]
[Bug - Save/ Update dependent] - Dependent type is not saving. Need conformation about behavior

**Comment by lakshithaorange** [comment]
As we discussed we are not saving dependent type ( child /other ) , only the relationshipType, 
@samanthajayasinghe can you please clarify this one

**Comment by janakapk** [comment]
This one will be fixed after give the fix for dependent section from application level
