### ISSUE TITLE
[Bug - Update dependent] - Sequence number get as 0 when update dependent 

### ISSUE THREAD

**Issue by janakapk** [orangehrm/orangehrm#70]
[Bug - Update dependent] - Sequence number get as 0 when update dependent 

1.Employee has one dependent
2.Update details with sequence number 2
3.There is no dependent with sequence 2
4.Added new records 
5.Added dependent sequence number 0

**Comment by lakshithaorange** [comment]
fixed ( fixed version - 3.4 alpha 5)
