### ISSUE TITLE
Centos 7 install

### ISSUE THREAD

**Issue by Utente81** [orangehrm/orangehrm#701]
I try to install orangehrm in centos 7 with this prerequisites (apache,php7.2,mariadb), but when the web installation control the prerequisities the directory lib and sinfony we see an error (NO WRITABLE). I change the permission to 755 from 777 and change owner to apache in nobody but the error remaining.

**Comment by RajithaKumara** [comment]
Hi @Utente81 
Did you tried giving permissions to `<orangehrm-directory>/symfony` recursively.

**Comment by Utente81** [comment]
Yes, I try the recurvively permission but the problem remainingInviato dal mio Galaxy
-------- Messaggio originale --------Da: Rajitha Kumara <notifications@github.com> Data: 01/01/21  08:44  (GMT+01:00) A: orangehrm/orangehrm <orangehrm@noreply.github.com> Cc: Utente81 <pietroromeo4@tin.it>, Mention <mention@noreply.github.com> Oggetto: Re: [orangehrm/orangehrm] Centos 7 install (#701) 
Hi @Utente81
Did you tried giving permissions to <orangehrm-directory>/symfony recursively.

**Comment by RajithaKumara** [comment]
Hi @Utente81 
We are using PHP [is_writable](https://www.php.net/manual/en/function.is-writable.php) to check the permission. Can you check you have extracted correctly? Also, can you check `lib/confs`, `lib/logs`, `symfony/config`, `symfony/apps/orangehrm/config`, `symfony/cache`, `symfony/log` directories are exists within orangehrm directory.

**Comment by bishopd** [comment]
Hi, I had the same problem, here is what fixed the bug.

Now disable SELinux temporarily using this below given command.
setenforce 0

**Comment by Utente81** [comment]
Hi, thanks for your comment, when I change selinux from enforcing to disabled and reboot the system, Orange work.
