### ISSUE TITLE
Orange hrm main page error

### ISSUE THREAD

**Issue by JungSis** [orangehrm/orangehrm#711]
I am just trying to access  my main orangehrm cms site.  "my domain url /hrmlive/symfony/web/index.php/auth/login"  it gives me this error, its been working the past months.

ERROR filter.ExceptionCatcherFilter - Uncaught Exception: Doctrine_Record_UnknownPropertyException: Unknown record property / related component "Array" on "Config" in /home2/public_html/hrmlive/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Record/Filter/Standard.php:55

Next DaoException: Unknown record property / related component "Array" on "Config" in /home2/public_html/hrmlive/symfony/plugins/orangehrmCorePlugin/lib/dao/ConfigDao.php:76

Next CoreServiceException: Unknown record property / related component "Array" on "Config" in /home2/public_html/hrmlive/symfony/plugins/orangehrmCorePlugin/lib/service/ConfigService.php:106

**Comment by WayneHoyle** [comment]
Similar issue to what I had when I first installed - have  you checked the version of PHP you are running?
