### ISSUE TITLE
[Bug - Update Employee ]How can apply API when optional fields enable in PIM -> Configuration -> Optional Field 

### ISSUE THREAD

**Issue by janakapk** [orangehrm/orangehrm#73]
[Bug - Update Employee ]How can apply API when optional fields enable in PIM -> Configuration -> Optional Field 

1.Assume SSN,SIN number for personal detail screen
2.How can update them

**Comment by samanthajayasinghe** [comment]
@janakapk We will not consider PIM Optional Field in this stage

**Comment by lakshithaorange** [comment]
SSN and SIN fields were added,
