### ISSUE TITLE
 demo is not available.

### ISSUE THREAD

**Issue by xiaoronglv** [orangehrm/orangehrm#861]
https://opensource-demo.orangehrmlive.com/index.php

username: Admin
password: admin123

this credential doesn't work anymore.

![2021-08-02_20-42-46](https://user-images.githubusercontent.com/1224077/127863783-a7843ff5-51c1-42aa-8d14-bbf6ad801be4.jpg)

**Comment by RajithaKumara** [comment]
Hi @xiaoronglv
Can you check this now. This instance resets hourly.

**Comment by arjunray12** [comment]
username: Admin
password: admin123

this credential doesn't work anymore.

**Comment by ghYura** [comment]
@RajithaKumara could you please provide Demo DB dump or file to deploy it locally to compate with online site od up-to-date version. I need DB demo dump for 4.10 version, please
