### ISSUE TITLE
How can I make description of Comment Mandatory of each entered hours timesheet as we can't Save or submit ?

### ISSUE THREAD

**Issue by mostafa-zaied** [orangehrm/orangehrm#956]
** Using Orangehrm version 4.8  Php7.3 Symfony CLI version v4.18.4**
1- select Project Name
2- select Activity Name
3- If I worked 2 hours I must add Comment (mandatory description) to it

** In bellow image I should add Comment first then press save  **
![image](https://user-images.githubusercontent.com/63561762/137023946-4f2c3201-6a98-4a16-bf24-ce70b7858c9e.png)
OR
Give me message like that if I didn't add the description this hour
![image](https://user-images.githubusercontent.com/63561762/137024101-77ffb118-6f7f-475c-8c48-fd7fa1c9e197.png)
Finally
![image](https://user-images.githubusercontent.com/63561762/137024415-d9e1397a-dd2f-4cbb-a4cd-8bea46c42a32.png)

**Comment by mostafa-zaied** [comment]
MY solution
`/symfony/web/webres_6051af48107ce6.31500353/orangehrmTimePlugin/js/editTimesheet.js`
```
function validateComments() {
    let flag = true;
    for (let i = 0; i < $("tr").length - 2; i++) {
      for (let j = 0; j < 7; j++) {
        let d = new Date($("h3")[2].innerText.split(" ")[4]);
        d.setDate(d.getDate() + j);
        let formatted_date =
          d.getFullYear() + "-" + (d.getMonth() + 1) + "-" + d.getDate();
          let activityId = $(`#initialRows_${i}_projectActivityName option:last`)[0].value
        const time = $(`input#initialRows_${i}_${j}.timeBox`)[0].value;
        if (time) {
          var comment = getComment(
            timesheetId,
            activityId,
            formatted_date,
            employeeId
          );
          if (!comment || /^\s*$/.test(comment)) {
            displayMessages("warning", comment_empty);
            $(`input#initialRows_${i}_${j}.timeBox`).addClass(
              "validation-error"
            );
            flag = false;
          }
        }
      }
    }
    return flag;
  }
```
```
  $("#timesheetForm").submit(function () {
    var commentFlag = validateComments();
    if (!commentFlag) {
      $("#btnSave").attr("disabled", "disabled");
      return false;
    }
    var projectFlag = validateProject();
    if (!projectFlag) {
      $("#btnSave").attr("disabled", "disabled");
      return false;
    }
    var inputFlag = validateInput();
    if (!inputFlag) {
      return false;
    }
    var rowFlag = validateRow();
    if (!rowFlag) {
      return false;
    }
  });
```

**Comment by RajithaKumara** [comment]
Hi @mostafa-zaied 
Is this bug in OrangeHRM 4.8 or you are requesting a feature?

**Comment by mostafa-zaied** [comment]
It is requesting a feature and I solved by this above code if any one need description of comment mandatory of each entered hours.
@RajithaKumara Can you please help here? -> https://github.com/orangehrm/orangehrm/issues/799
Thanks.
