### ISSUE TITLE
[Bug - Add leave types] : API added leave types are bot visible for apply screen 

### ISSUE THREAD

**Issue by janakapk** [orangehrm/orangehrm#97]
[Bug - Add leave types] : API added leave types are bot visible for apply screen 

1.Add Leave Type A from the API
2.User log and go apply
3.He can't see Leave Type A in leave type drop down

**Comment by lakshithaorange** [comment]
@janakapk Hi Janaka , after adding a leave type you have to add entitlements which you can do by using the /api/v1/employee/:id/entitlement with using parameters leavetype and employee id , 
then only those leave types will be appear on apply leave panel,
