### ISSUE TITLE
Weak Password isn't working

### ISSUE THREAD

**Issue by Fliw** [orangehrm/orangehrm#993]
**Environment details**
OrangeHRM version: 4.8
OrangeHRM source: Git clone
Platform: 64-bit (Windows)
PHP version: 7.2.29
Database and version: mySql
Web server: apache

If applicable:
Browser:  chrome

**Describe the bug**
when i login, it's redirect to weak password page, when i change, nothing happen

**To Reproduce**
from login menu, redirected to weakpassword page, change and nothing happen, even button isn't clickable

**Expected behavior**
the password going to change

**What do you see instead:**
nothing, even button isn't clickable

If issue related to installation:
- installer/log.txt
- logInsatall.log

If issue related to any other
- symfony/log/orangehrm.log 

**Screenshots**
![image](https://user-images.githubusercontent.com/56640907/140399705-f371552d-8734-4c1e-89ba-edd1911c4853.png)

**Additional context**

**Comment by mostafa-zaied** [comment]
Yes that happened to me , Try when you initiate the database for first time to add strong password.
Thanks

**Comment by Fliw** [comment]
@mostafa-zaied okay, thanks for the info!
